### ISSUE TITLE
如何配置key.yaml的azrue

### ISSUE THREAD

**Issue by vampire0321** [geekan/MetaGPT#100]
请问配置azrue的key.yaml有样例么，老是提示找不到资源：
openai.error.InvalidRequestError: Resource not found
![image](https://github.com/geekan/MetaGPT/assets/35253455/1852556f-03c4-43eb-b1d4-5b7d882d7e4e)

**Comment by ttmouse** [comment]
OPENAI_API_TYPE: "azure"
OPENAI_API_BASE: "https://****.openai.azure.com/"
OPENAI_API_KEY: '*****'
OPENAI_API_VERSION: "2023-05-15"
DEPLOYMENT_ID: "gpt-35-turbo"
