### ISSUE TITLE
Increment mode quits with ValueError: call with_srcs first

### ISSUE THREAD

**Issue by BakedJesus** [geekan/MetaGPT#1017]
**Bug description**
Increment mode quits with ValueError: call with_srcs first

**Bug solved method**
Python script:
`if __name__ == "__main__":
    repo_existing_path = "./crypto_dash"
    repo: ProjectRepo = generate_repo(idea = "Convert this repo so that it is object-oriented style architecture, complete with beautiful dashboard with many elements",
                                    n_round=50,
                                    run_tests=False,
                                    inc=True,
                                    project_path=repo_existing_path) 
    print(repo) `

Output:
`Traceback (most recent call last):
  File "/home/qavi/repos/meta_generator.py", line 13, in <module>
    print(repo)
  File "/home/qavi/penvs/metaenv/lib/python3.10/site-packages/metagpt/utils/project_repo.py", line 107, in __str__
    srcs_str = f"Srcs({self.srcs.all_files})"
  File "/home/qavi/penvs/metaenv/lib/python3.10/site-packages/metagpt/utils/project_repo.py", line 125, in srcs
    raise ValueError("Call with_srcs first.")
ValueError: Call with_srcs first.`

**Environment information**
- LLM type and model name: GPT-4 turbo-preview
- System version: Ubuntu 23.04
- Python version: conda python 3.10.13

- packages version:
- installation method: pip install metagpt

**Screenshots or logs**

**Comment by iorisa** [comment]
`--project-path` points to an old version project repository generated by MetaGPT.
Importing an external third-party repository requires a reverse-engineer module, which has not been released yet.

**Comment by geekan** [comment]
@BakedJesus Did this answer solve your problem? It means that you need to use the new version to generate and propose incremental requirements
