### ISSUE TITLE
What kind of computer can run this model?

### ISSUE THREAD

**Issue by learningendless** [geekan/MetaGPT#1028]
Can mac studio run this model?
How much memory dose this memory need?

**Comment by devinambron** [comment]
Yes, a Mac Studio with at least 16 GB RAM can run MetaGPT for basic tasks. Depending on what you're utilizing the model for, 32 GB RAM or more might work best.

**Comment by voidking** [comment]
MetaGPT will call the remote LLM during operation, so it requires very few local resources.
If you just run MetaGPT on Mac Stutio, I think 4C8G is completely sufficient. 
If you just run MetaGPT on Linux, I think 1C2G is sufficient.

**Comment by geekan** [comment]
Maybe we need to have a list of different task success rates for different language models. This may be a data set requirement, but it is reasonable

**Comment by xenon0906** [comment]
> Yes, a Mac Studio with at least 16 GB RAM can run MetaGPT for basic tasks. Depending on what you're utilizing the model for, 32 GB RAM or more might work best.

I believe it totally depends on the size of the dataset and number of time the data is gonna be train in the model 
As per my consideration , if you're a college student you can contact your high authorities for using the supercomputer if it's available , it's gonna save you a lot of time.
