### ISSUE TITLE
不能在windows系统运行？

### ISSUE THREAD

**Issue by younggggger** [geekan/MetaGPT#1057]
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\metagpt\softwar │
│ e_company.py:108 in startup                                                                      │
│                                                                                                  │
│   105 │   │   typer.echo("Missing argument 'IDEA'. Run 'metagpt --help' for more information."   │
│   106 │   │   raise typer.Exit()                                                                 │
│   107 │                                                                                          │
│ > 108 │   return generate_repo(                                                                  │
│   109 │   │   idea,                                                                              │
│   110 │   │   investment,                                                                        │
│   111 │   │   n_round,                                                                           │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\metagpt\softwar │
│ e_company.py:32 in generate_repo                                                                 │
│                                                                                                  │
│    29 │   """Run the startup logic. Can be called from CLI or other Python scripts."""           │
│    30 │   from metagpt.config2 import config                                                     │
│    31 │   from metagpt.context import Context                                                    │
│ >  32 │   from metagpt.roles import (                                                            │
│    33 │   │   Architect,                                                                         │
│    34 │   │   Engineer,                                                                          │
│    35 │   │   ProductManager,                                                                    │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\metagpt\roles\_ │
│ _init__.py:16 in <module>                                                                        │
│                                                                                                  │
│   13 from metagpt.roles.engineer import Engineer                                                 │
│   14 from metagpt.roles.qa_engineer import QaEngineer                                            │
│   15 from metagpt.roles.searcher import Searcher                                                 │
│ > 16 from metagpt.roles.sales import Sales                                                       │
│   17 from metagpt.roles.customer_service import CustomerService                                  │
│   18                                                                                             │
│   19                                                                                             │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\metagpt\roles\s │
│ ales.py:14 in <module>                                                                           │
│                                                                                                  │
│   11 from pydantic import Field, model_validator                                                 │
│   12                                                                                             │
│   13 from metagpt.actions import SearchAndSummarize, UserRequirement                             │
│ > 14 from metagpt.document_store.base_store import BaseStore                                     │
│   15 from metagpt.roles import Role                                                              │
│   16 from metagpt.tools.search_engine import SearchEngine                                        │
│   17                                                                                             │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\metagpt\documen │
│ t_store\__init__.py:9 in <module>                                                                │
│                                                                                                  │
│    6 @File    : __init__.py                                                                      │
│    7 """                                                                                         │
│    8                                                                                             │
│ >  9 from metagpt.document_store.faiss_store import FaissStore                                   │
│   10                                                                                             │
│   11 __all__ = ["FaissStore"]                                                                    │
│   12                                                                                             │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\metagpt\documen │
│ t_store\faiss_store.py:15 in <module>                                                            │
│                                                                                                  │
│   12 from langchain.vectorstores import FAISS                                                    │
│   13 from langchain_core.embeddings import Embeddings                                            │
│   14                                                                                             │
│ > 15 from metagpt.document import IndexableDocument                                              │
│   16 from metagpt.document_store.base_store import LocalStore                                    │
│   17 from metagpt.logs import logger                                                             │
│   18 from metagpt.utils.embedding import get_embedding                                           │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\metagpt\documen │
│ t.py:14 in <module>                                                                              │
│                                                                                                  │
│    11 from typing import Optional, Union                                                         │
│    12                                                                                            │
│    13 import pandas as pd                                                                        │
│ >  14 from langchain.document_loaders import (                                                   │
│    15 │   TextLoader,                                                                            │
│    16 │   UnstructuredPDFLoader,                                                                 │
│    17 │   UnstructuredWordDocumentLoader,                                                        │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\docum │
│ ent_loaders\__init__.py:18 in <module>                                                           │
│                                                                                                  │
│    15 │   Document, <name>TextSplitter                                                           │
│    16 """                                                                                        │
│    17                                                                                            │
│ >  18 from langchain.document_loaders.acreom import AcreomLoader                                 │
│    19 from langchain.document_loaders.airbyte import (                                           │
│    20 │   AirbyteCDKLoader,                                                                      │
│    21 │   AirbyteGongLoader,                                                                     │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\docum │
│ ent_loaders\acreom.py:1 in <module>                                                              │
│                                                                                                  │
│ > 1 from langchain_community.document_loaders.acreom import AcreomLoader                         │
│   2                                                                                              │
│   3 __all__ = ["AcreomLoader"]                                                                   │
│   4                                                                                              │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_commu │
│ nity\document_loaders\__init__.py:163 in <module>                                                │
│                                                                                                  │
│   160 │   PyPDFLoader,                                                                           │
│   161 │   UnstructuredPDFLoader,                                                                 │
│   162 )                                                                                          │
│ > 163 from langchain_community.document_loaders.pebblo import PebbloSafeLoader                   │
│   164 from langchain_community.document_loaders.polars_dataframe import PolarsDataFrameLoader    │
│   165 from langchain_community.document_loaders.powerpoint import UnstructuredPowerPointLoader   │
│   166 from langchain_community.document_loaders.psychic import PsychicLoader                     │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_commu │
│ nity\document_loaders\pebblo.py:5 in <module>                                                    │
│                                                                                                  │
│     2                                                                                            │
│     3 import logging                                                                             │
│     4 import os                                                                                  │
│ >   5 import pwd                                                                                 │
│     6 import uuid                                                                                │
│     7 from http import HTTPStatus                                                                │
│     8 from typing import Any, Dict, Iterator, List                                               │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'pwd'

**Comment by geekan** [comment]
Yes. Using the main branch will not have this problem

**Comment by iorisa** [comment]
与 #1127  相同。
已证明windows下可以正常运行。
