### ISSUE TITLE
HumanEval execution

### ISSUE THREAD

**Issue by huangd1999** [geekan/MetaGPT#1062]
Hi everyone,

I want to know whether the tester will execute code locally when I run the script:
```
from metagpt.software_company import generate_repo, ProjectRepo
repo: ProjectRepo = generate_repo("def truncate_number(number: float) -> float: \""" Given a positive floating point number, it can be decomposed into and integer part (largest integer smaller than given number) and decimals (leftover part always smaller than 1). Return the decimal part of the number. >>> truncate_number(3.5) 0.5 \"""")  # or ProjectRepo("<path>")
print(repo)  # it will print the repo structure with files
```

I think running the code in the local terminal or directly reviewing the code with the LLM agent is two different way.

**Comment by geekan** [comment]
Hello, the HumanEval script needs to be further provided by @stellaHSR to support the latest version and is not created by the entry that generates the repo.

**Comment by stellaHSR** [comment]
Hi, thank you for your question. After the upcoming test, the entry point for the evaluation and execution of the iterated version will be provided. We are currently finalizing the changes and will make them available once testing is completed.
