### ISSUE TITLE
bug in extract_state_value_from_output

### ISSUE THREAD

**Issue by haiasd** [geekan/MetaGPT#1067]
![image](https://github.com/geekan/MetaGPT/assets/26181650/3d0c6618-3906-436e-bb36-38f80715238a)
extract_state_value_from_output  function 
这个函数会把-1处理成1，导致react模型无限循环

**Comment by geekan** [comment]
@better629 @garylin2099 noticed that this problem seems to be related to the code on both sides. Can you guys take a look?
