### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by liangjw** [geekan/MetaGPT#107]
每次执行完成后报下面错误， 是BUG还是正常

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000250DE4424C0>
Traceback (most recent call last):
  File "D:\MyData\liangjw75\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\MyData\liangjw75\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\MyData\liangjw75\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "D:\MyData\liangjw75\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by phhh-xh** [comment]
我也是，但是我的代码还没有执行完毕就会报这个错误

**Comment by TerryFYL** [comment]
我的也是，有大佬来解答吗？

**Comment by wangjie5540** [comment]
> 每次执行完成后报下面错误， 是BUG还是正常
> 
> Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x00000250DE4424C0> Traceback (most recent call last): File "D:\MyData\liangjw75\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in **del** self.close() File "D:\MyData\liangjw75\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close self._loop.call_soon(self._call_connection_lost, None) File "D:\MyData\liangjw75\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon self._check_closed() File "D:\MyData\liangjw75\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed raise RuntimeError('Event loop is closed') RuntimeError: Event loop is closed

有全一点的日志么？
个人猜测，如果与asyncio有关的，大概率是网络访问异常导致

**Comment by voidking** [comment]
看上去是windows操作系统需要特殊处理下：https://stackoverflow.com/questions/45600579/asyncio-event-loop-is-closed-when-getting-loop
我查下代码。

**Comment by fwka92** [comment]
got the same issue on windows, but the full stacktrace in my case is an issue with pathlib. the path contains '"' characters and '\n' which are illegal in windows. one needs to remove those characters from all paths ive tried myself but it still crashed at other places in code.

**Comment by Emechiro** [comment]
tengo el mismo problema en windows 10 y 11, alguien tiene alguna solucion ?

**Comment by tt7292000** [comment]
相同的问题，请问有解决吗
same problem, wonder if any solutions?

**Comment by emp1tsu** [comment]
I registered the billing information for the ChatGPT API, and after setting the OPENAI_API_MODEL to "gpt-3.5-turbo", it started working properly.

**Comment by emp1tsu** [comment]
I registered the billing information for the ChatGPT API, and after setting OPENAI_API_MODEL to "gpt-3.5-turbo", the 'Event loop is closed' error has been resolved.

**Comment by 6xshushu** [comment]
> 看上去是windows操作系统需要特殊处理下：https://stackoverflow.com/questions/45600579/asyncio-event-loop-is-closed-when-getting-loop

应该时在调用asyncio.run之前都加上下面的代码？
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

**Comment by zoezhoux** [comment]
> 

I tried "gpt-3.5-turbo", it didn't work for me.

**Comment by DiamondGlassDrill** [comment]
Hi it was merged? But the error still persists? Get the same error with newest version [7da710e]

**Comment by DiamondGlassDrill** [comment]
I solved it with: 
Before: 
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

Solution:
asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())

    if platform.system() == "Windows":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
    asyncio.run(startup(idea, investment, n_round, code_review, run_tests))
