### ISSUE TITLE
AttributeError: 'HumanProvider' object has no attribute 'config'

### ISSUE THREAD

**Issue by Beichen-Ma** [geekan/MetaGPT#1076]
**Bug description**

When I try to use human engagement by running script example/build_customized_multi_agents.py with command python3 examples/build_customized_multi_agents.py --add_human True, got below error: AttributeError: 'HumanProvider' object has no attribute 'config"

**Bug solved method**

**Environment information**

MacOS 14.4, conda python 3.10, OpenAI gpt-4-turbo-preview

- LLM type and model name:
- System version:
- Python version:

- packages version:
- installation method: cd ./MetaGPT and pip install -e .

**Screenshots or logs**

<img width="1717" alt="image" src="https://github.com/geekan/MetaGPT/assets/90386322/efe4ef91-8184-4c2d-b244-930766d5190a">

**Comment by geekan** [comment]
@Beichen-Ma Can you try again?

**Comment by Beichen-Ma** [comment]
That works! Thanks very much.
