### ISSUE TITLE
Scripts for Running HumanEval Benchmark

### ISSUE THREAD

**Issue by oximi123** [geekan/MetaGPT#1088]
Is there a script that can reproduce the results in the paper on HumanEval benchmark?

**Comment by oximi123** [comment]
Is there a script that can reproduce the results in the paper on HumanEval benchmark?

**Comment by jasonzliang** [comment]
Same I would like to get access to the scripts to reproduce humaneval results.

**Comment by duce3790** [comment]
Hi, I would like to ask about the schedule for the release of this script

**Comment by geekan** [comment]
@stellaHSR

**Comment by stellaHSR** [comment]
Thank you for your patience. Due to limited staffing, we are currently working through the test stages and finalizing the scripts. Once everything is validated, we will release the scripts and update this thread as soon as possible.
