### ISSUE TITLE
docs/prd/xxxxxx.json not found

### ISSUE THREAD

**Issue by quarechen** [geekan/MetaGPT#1094]
**Bug description**

Detected source code "docs/prd/20240325023557.json"

**Environment information**

use the example of docker

- LLM type and model name:  gpt-3.5-turbo or GLM-4
- System version: docker ： metagpt/metagpt latest  dcf87e6f98b9ec799bac44bc8c8ff7786fea94bb337d2fbb426da1a7cdbe6470
- Python version: Python 3.9.17

- packages version:
- installation method: 

**Screenshots or logs**

![image](https://github.com/geekan/MetaGPT/assets/30918026/252ec681-63ed-4f93-a59a-97ae6b4564fc)

**Comment by iorisa** [comment]
Same issue regarding exception recovery as #1013: the recovery process didn't restore the context.repo when it was recovering.
