### ISSUE TITLE
报错。请问finished raised InvalidRequestError是什么原因

### ISSUE THREAD

**Issue by SiVeci** [geekan/MetaGPT#110]
tenacity.RetryError: RetryError[<Future at 0x7f83d545af70 state=finished raised InvalidRequestError>
代理是可以访问chatgpt正常使用的

**Comment by geekan** [comment]
Check [FAQ](https://deepwisdom.feishu.cn/wiki/MsGnwQBjiif9c3koSJNcYaoSnu4) 8
