### ISSUE TITLE
作者我遇到这个错误我需要怎么解决，当我更新到3.5.0.post1的时候会出现ModuleNotFoundError: No module named 'google.generativeai' 但是当我下载google.generativeai的时候他又会给我自动升级到 4.25.3然后就出现这个错误

### ISSUE THREAD

**Issue by yxl23** [geekan/MetaGPT#1110]
![image](https://github.com/geekan/MetaGPT/assets/115678682/78f5cb15-c4e7-495a-bae8-b88ac0eadceb)

**Comment by yxl23** [comment]
How do I need to solve this error? When I update to 3.5.0. post1, there will be a ModuleNotFoundError: No module named 'Google. generateai'. However, when I download Google. generateai, it will automatically upgrade to 4.25.3 and then this error will appear

**Comment by geekan** [comment]
What is your installation command? Try this?

`git clone https://github.com/geekan/MetaGPT && cd MetaGPT && pip install --upgrade -e .`

**Comment by better629** [comment]
we use `google-generativeai==0.4.1`.

**Comment by yxl23** [comment]
我按照你的命令执行了，但是还是报这个错
![image](https://github.com/geekan/MetaGPT/assets/115678682/f1cc4f9a-15d4-4a8b-98c9-9c8b59f5b9e1)

**Comment by geekan** [comment]
@yxl23 I suggest providing a more complete execution command, environment, output, etc., so that we may be able to help you locate the problem

**Comment by yxl23** [comment]
解决那个问题了，现在又出现这个问题
![image](https://github.com/geekan/MetaGPT/assets/115678682/52fdd6b2-1556-41ee-96bd-a76791d88c15)

**Comment by yxl23** [comment]
![image](https://github.com/geekan/MetaGPT/assets/115678682/9d88cbe1-478f-4a76-aa50-9427286dd1cd)

**Comment by geekan** [comment]
你可以访问下截图中的 faq url，其中有描述解决方法

**Comment by iorisa** [comment]
这个看着像是网络不通。如果要配代理，config2.yaml里要这样配置：
```yaml
llm:
  api_key: "A....I"
  model: "gemini-pro" # https://ai.google.dev/models/gemini
  api_type: "gemini"
  proxy: "http://xx:xx"
```

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
