### ISSUE TITLE
meta gpt框架中每个Agent，任务完成判断规则学习

### ISSUE THREAD

**Issue by tianzj323** [geekan/MetaGPT#1111]
在现实业务中，一个角色其做事时会按照一定的规则和策略去评判其做事的结果，以便于其做后续的动作。是否可以让一个角色的Agent学习评判事情是否完成的规则或策略。再做具体的工作时候，按照其学习到的评判规则和策略判断其做的事情，是否满足需求。如果可以，实现的逻辑是什么样子的。

**Comment by geekan** [comment]
https://github.com/geekan/MetaGPT/pull/1112

Maybe you could take a look at this?

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
