### ISSUE TITLE
关于狼人项目的跟进

### ISSUE THREAD

**Issue by nameBai** [geekan/MetaGPT#1117]
你们好，我已经根据你们之前的狼人项目进行改进，并做了一些有意思的工作，但是我观察到metagpt新版本有很多激动人心的功能，但狼人项目跟这个版本差异过大，并不能使用这些新功能，因此想问一下关于狼人项目的迁移，近期是否有打算去做呢？
万分感谢。

**Comment by geekan** [comment]
Can you tell us about “interesting jobs”? Then we might know how to modify it

**Comment by iorisa** [comment]
可以提PR，或者把问题代码贴出来，我告你怎么升级到最新metagpt代码。

**Comment by GreBai** [comment]
好的，我先看看，有问题我会提出

**Comment by GreBai** [comment]
> Can you tell us about “interesting jobs”? Then we might know how to modify it

我们打算利用metagpt做一个教学场景的复杂模拟，新的框架调整了角色记忆和环境的逻辑，每个角色使用不用的llm_config以及原生支持各类的商业大模型的特点，这都是原有框架没有的。

**Comment by geekan** [comment]
Do you mean tutorial on werewolf scene? Or it's a real education scene?

**Comment by GreBai** [comment]
我是在狼人杀项目的基础上进行改动，使得他可以模拟较为真实的教育场景，这有助于我们的科研工作，本身已经不是狼人杀的活动了。

**Comment by better629** [comment]
> 你们好，我已经根据你们之前的狼人项目进行改进，并做了一些有意思的工作，但是我观察到metagpt新版本有很多激动人心的功能，但狼人项目跟这个版本差异过大，并不能使用这些新功能，因此想问一下关于狼人项目的迁移，近期是否有打算去做呢？ 万分感谢。

There would be a update from old werewolf into new one. If you have further ideas about this, welcome to discuss.

**Comment by GreBai** [comment]
> > 你们好，我已经根据你们之前的狼人项目进行改进，并做了一些有意思的工作，但是我观察到metagpt新版本有很多激动人心的功能，但狼人项目跟这个版本差异过大，并不能使用这些新功能，因此想问一下关于狼人项目的迁移，近期是否有打算去做呢？ 万分感谢。
> 
> There would be a update from old werewolf into new one. If you have further ideas about this, welcome to discuss.

I'm extremely grateful for your support！
