### ISSUE TITLE
distutils 模块使用问题

### ISSUE THREAD

**Issue by prinspark** [geekan/MetaGPT#1121]
**Bug description**

安装时报错    import distutils.core
ModuleNotFoundError: No module named 'distutils'

**Bug solved method**

我尝试了一下命令得到错误返回
pip3 install python-distutils
ERROR: Could not find a version that satisfies the requirement python-distutils (from versions: none)
ERROR: No matching distribution found for python-distutils

**Environment information**

- LLM type and model name:
- System version:macOS 12
- Python version:3.12

- packages version:
- installation method: pip3 install --upgrade metagpt

**Screenshots or logs**

**Comment by prinspark** [comment]
开始用3.9.6，过程特别慢，命令行最后中断了并提示我用较高版本python，我才换成3.12的。难道再试试3.10？

**Comment by geekan** [comment]
3.9 / 3.10 OK. But if you are interested, you can help us adapt to a higher version of python

**Comment by kjenney** [comment]
Please update the documentation to clearly state that only 3.9 and 3.10 are OK. 3.9+ is all over the documentation including the README
