### ISSUE TITLE
Author, I encountered this issue while incrementing the original code. How do I need to solve it

### ISSUE THREAD

**Issue by yxl23** [geekan/MetaGPT#1127]
![image](https://github.com/geekan/MetaGPT/assets/115678682/cac14907-391c-48df-9048-ec0faa4ff01a)

this is a my command
![image](https://github.com/geekan/MetaGPT/assets/115678682/c2a57248-e16c-4262-b8ad-899435436f73)

**Comment by iorisa** [comment]
Which version is MetaGPT?

**Comment by yxl23** [comment]
I don't know which version it is, but it was cloned using the git command. Can you give me a command pointing to the code path to add it

**Comment by yxl23** [comment]
I don't know which version it is, but it was cloned using the git command. Can you give me a command pointing to the code path to add it

**Comment by iorisa** [comment]
Using git commands like these?
```bash
git clone https://github.com/geekan/MetaGPT.git
cd ./MetaGPT
pip install -e .
```

**Comment by yxl23** [comment]
yes

**Comment by iorisa** [comment]
Could you please provide the error logs from the `logs` folder? 
I noticed that only INFO-level logs are present in your screenshot.
<img width="317" alt="截屏2024-03-28 17 26 11" src="https://github.com/geekan/MetaGPT/assets/46912756/d96628ca-82ea-4d28-83c6-2c6521b5f54c">

**Comment by iorisa** [comment]
Are you running in the Windows Terminal or in a tool like MinGW that simulates a Linux runtime environment?

**Comment by iorisa** [comment]
I tried but couldn't reproduce your issue.
My environment setup:
1. windows 11
2. python 3.9
3. cygwin64
4. virtualenv
5. MetaGPT main branch
<img width="1451" alt="截屏2024-03-29 14 57 14" src="https://github.com/geekan/MetaGPT/assets/46912756/cf68365c-335a-4b10-88a5-2a1beb091fee">

**Comment by yxl23** [comment]
Hello author, I uninstalled the previous version and reinstalled a new one, and the problem was resolved
