### ISSUE TITLE
ITERATIVE PROGRAMMING WITH EXECUTABLE FEEDBACK

### ISSUE THREAD

**Issue by RainingSea** [geekan/MetaGPT#1147]
how the "ITERATIVE PROGRAMMING WITH EXECUTABLE FEEDBACK" in Section 3.3 of the paper is reflected in the code.
I set **run_tests=true**, but it seems the agent did not execute these tests and return the test results to the engineer.

**Comment by stellaHSR** [comment]
Thank you for paying attention. The main branch is updated too quickly and the corresponding code needs to be refactored. However, the corresponding participants don't have enough time to catch up recently. We'll see if this part of the code can be taken over and merged.

**Comment by iorisa** [comment]
The value of `--n-round` is too small; it's exhausted before entering the QA stage. MetaGPT needs to be provided with these parameters: `--run-tests --n-round 20`, giving `--n-round` a larger value.

**Comment by RainingSea** [comment]
ok, I will go try it out, thx
