### ISSUE TITLE
metagpt 0.8.0 and langchain-openai 0.1.1 have conflicting version requirements for openai

### ISSUE THREAD

**Issue by SheldonLiu0412** [geekan/MetaGPT#1171]
**Bug description**

**Bug solved method**

**Environment information**
- System version: macOS 14.4 (23E214)- Python version: 3.10.14

- LLM type and model name:
- System version: macOS 14.4 (23E214)
- Python version: 3.10.14
- MetaGPT version or branch:metagpt 0.8.0 

langchain-openai 0.1.1 requires openai<2.0.0,>=1.10.0, but you have openai 1.6.1 which is incompatible.
metagpt 0.8.0 requires openai==1.6.1, but you have openai 1.16.2 which is incompatible.
- packages version:langchain-openai 0.1.1,metagpt 0.8.0
- installation method: 
pip
**Screenshots or logs**

**Comment by seehi** [comment]
You can manually modify openai version within either one of the two, then use `pip install -e SOURCE_CODE_DIRECTORY`.
Maybe metagpt should use `openai<2.0.0,>=1.6.0` in the new version.
