### ISSUE TITLE
New provider: Amazon Bedrock (AWS)

### ISSUE THREAD

**Issue by dgallitelli** [geekan/MetaGPT#1174]
**Feature description**
Please include support for Amazon Bedrock models. These models can be from Amazon, Anthropic, AI21, Cohere, Mistral, or Meta Llama 2. 

**Your Feature**
1. Create a new LLM Provides under [metagpt/provider](https://github.com/geekan/MetaGPT/tree/db65554c4931d4a95e20331b770cf4f7e5202264/metagpt/provider) for Amazon Bedrock
2. Include it in the [LLMType](https://github.com/geekan/MetaGPT/blob/db65554c4931d4a95e20331b770cf4f7e5202264/metagpt/configs/llm_config.py#L17) available

**Comment by seehi** [comment]
It might be supported later, and if possible, you can also provide a PR.

**Comment by chosenlu** [comment]
could you tell me when will metagpt add bedrock, and how to add provider by myself

**Comment by better629** [comment]
about next week, you can refs any llm provider under `metagpt/provider` and complete methods from `BaseLLM`

**Comment by chosenlu** [comment]
Thank you very much and I look forward to your updates. I have just started to contact metagpt and I am still familiar with some concepts. I will read the code carefully.

I found another problem examples/rag_search.py can not run
it looks like the llama-index update cause
Traceback (most recent call last):
  File "/Users/chosenlu/Job/Python/meta_gpt_agent_newst/user/rag_search/rag_search.py", line 7, in <module>
    from metagpt.rag.engines import SimpleEngine
  File "/Users/chosenlu/Job/Python/meta_gpt_agent_newst/lib/python3.9/site-packages/metagpt/rag/engines/__init__.py", line 3, in <module>
    from metagpt.rag.engines.simple import SimpleEngine
  File "/Users/chosenlu/Job/Python/meta_gpt_agent_newst/lib/python3.9/site-packages/metagpt/rag/engines/simple.py", line 31, in <module>
    from metagpt.rag.factories import (
  File "/Users/chosenlu/Job/Python/meta_gpt_agent_newst/lib/python3.9/site-packages/metagpt/rag/factories/__init__.py", line 3, in <module>
    from metagpt.rag.factories.retriever import get_retriever
  File "/Users/chosenlu/Job/Python/meta_gpt_agent_newst/lib/python3.9/site-packages/metagpt/rag/factories/retriever.py", line 15, in <module>
    from metagpt.rag.retrievers.bm25_retriever import DynamicBM25Retriever
  File "/Users/chosenlu/Job/Python/meta_gpt_agent_newst/lib/python3.9/site-packages/metagpt/rag/retrievers/bm25_retriever.py", line 8, in <module>
    from llama_index.retrievers.bm25 import BM25Retriever
ModuleNotFoundError: No module named 'llama_index.retrievers'

**Comment by chosenlu** [comment]
I resolved 
it looks like I need install:
pip install llama-index-retrievers-bm25
pip install llama-index-embeddings-azure-openai
pip install llama-index-llms-azure-openai
pip install llama-index-embeddings-gemini
pip install llama-index-embeddings-ollama

**Comment by better629** [comment]
Yes, rag is extra module, so you need install it. You can ref to `https://docs.deepwisdom.ai/main/en/guide/get_started/installation.html#install-submodules` if meet problems.

**Comment by chosenlu** [comment]
Thank you！I still waiting the bedrock support，Is the bedrock ok now？

**Comment by better629** [comment]
@chosenlu @dgallitelli 
see the pr https://github.com/geekan/MetaGPT/pull/1231

**Comment by dgallitelli** [comment]
Nice, thank you! I'll give it a try and provide some feedback. Quick question: are the Access key and Secret access key strict requirements? Or can they be inferred from environmental variables and therefore omitted in the LLM config?

**Comment by better629** [comment]
@dgallitelli no, for now, you should config them in LLM config.

**Comment by xdstone1on163** [comment]
this is the sample code error message: 
-----------
Input should be 'openai', 'anthropic', 'claude', 'spark', 'zhipuai', 'fireworks', 'open_llm', 'gemini', 'metagpt', 'azure', 'ollama', 'qianfan', 'dashscope', 'moonshot', 'mistral' or 'yi' [type=enum, input_value='bedrock', input_type=str]
------------


why I am seeing no 'bedrock' support by now?

**Comment by seehi** [comment]
Use the main branch: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration/llm_api_configuration.html

**Comment by qingerVT** [comment]
what does this mean 
"botocore.errorfactory.ValidationException: An error occurred (ValidationException) whe
n calling the InvokeModelWithResponseStream operation: Invocation of model ID anthropi
c.claude-3-opus-20240229-v1:0 with on-demand throughput isn’t supported. Retry your re
quest with the ID or ARN of an inference profile that contains this model"
