### ISSUE TITLE
SoftwareCompany not found

### ISSUE THREAD

**Issue by SheldonLiu0412** [geekan/MetaGPT#1176]
**Bug description**

from metagpt.software_company import SoftwareCompany
SoftwareCompany not found
**Bug solved method**

**Environment information**

- LLM type and model name:
- System version:OS 14.4 (23E214)
- Python version:3.10.14
- MetaGPT version or branch:0.8.0

- packages version:
- installation method: 

**Screenshots or logs**

**Comment by seehi** [comment]
Where did you see the code? The document might not be updated; there is no SoftwareCompany in [software_company.py](https://github.com/geekan/MetaGPT/blob/v0.8-release/metagpt/software_company.py#L45) in 0.8.0.
