### ISSUE TITLE
metagpt generate too many inconsistent invocation code between different source files

### ISSUE THREAD

**Issue by longweiii** [geekan/MetaGPT#1185]
metagpt always generate inconsistent code between different source files. 
For example,
in source file A, it contains a method a(p1,p2),this method have 2 parameters, but in source file B, it will generate invocation code for the method a(p1) which only contains 1 parameters of that method, and sometime in source file A, it will generate invocation code for a non-exist method in other source file, and there are too many such cases in project for me to fix them,
is there any good way to avoid such inconsistent codes？

**Comment by longweiii** [comment]
Add sometime the generated source code will call a non-exist attribute of a object, these inconsistent codes make project unable to run.

**Comment by seehi** [comment]
What's your LLM model, prefer `gpt-4-turbo`

**Comment by longweiii** [comment]
> What's your LLM model, prefer `gpt-4-turbo`
I use this LLM model
![微信图片_20240412104847](https://github.com/geekan/MetaGPT/assets/166496192/3185e372-dd4e-4acb-97d3-fd416d9a0f37)

**Comment by longweiii** [comment]
is gpt-4-turbo-preview different from gpt-4-turbo?

**Comment by seehi** [comment]
[gpt-4-turbo](https://platform.openai.com/docs/models/continuous-model-upgrades) is the latest model. 
You can check [these cases](https://www.deepwisdom.ai/usecases), they are all generated by `metagpt`, sometimes it's neccessary to adjust the code.
