### ISSUE TITLE
Getting Value Error

### ISSUE THREAD

**Issue by Unkownforlife** [geekan/MetaGPT#1196]
I have added the meta-gpt code in Flask and made API's from it. So it works perfectly in 1 or 2 request after it i am getting below error.

Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 38.627(s), this was the 6th time calling it. exp: 1 validation error for WritePRD_AN                                                                                      Value error, Missing fields: {'Programming Language'} [type=value_error, input_value={'Language': 'en_us', 'Or... 'Anything UNCLEAR': ''}, input_type=dict]

**Comment by seehi** [comment]
Wrong answer from LLM. Prefer `gpt-4-turbo`.

**Comment by seehi** [comment]
If the issue is same with [this](https://github.com/geekan/MetaGPT/issues/1194), Pls close one of them.
