### ISSUE TITLE
Support for Cohere API 

### ISSUE THREAD

**Issue by AliArmani3397** [geekan/MetaGPT#1197]
Please add support for Cohere API with all the built in RAG and tool use functionalities. Essentially, RAG and tool use in Cohere are just chat parameters definable by users. More information can be found at https://docs.cohere.com/reference/chat .

**Comment by YangQianli92** [comment]
Cohere API have been added.
Specific code to be merged, the use of the method can be referred to as follows
https://github.com/geekan/MetaGPT/pull/1193
``` python
SimpleEngine.from_docs(
                input_files=[DOC_PATH],
                retriever_configs=[FAISSRetrieverConfig()],
                ranker_configs=[CohereRerankConfig()],
            )

**Comment by YangQianli92** [comment]
> Please add support for Cohere API with all the built in RAG and tool use functionalities. Essentially, RAG and tool use in Cohere are just chat parameters definable by users. More information can be found at https://docs.cohere.com/reference/chat .

Cohere API have been added.
Specific code to be merged, the use of the method can be referred to as follows
https://github.com/geekan/MetaGPT/pull/1193
``` python
SimpleEngine.from_docs(
                input_files=[DOC_PATH],
                retriever_configs=[FAISSRetrieverConfig()],
                ranker_configs=[CohereRerankConfig()],
            )
