### ISSUE TITLE
how do i set up with groq api

### ISSUE THREAD

**Issue by Soundmovin46** [geekan/MetaGPT#1198]
api_type: ""  # or azure / ollama / open_llm etc. Check LLMType for more options
  model: "mixtral-8x7b-32768"  # or gpt-3.5-turbo-1106 / gpt-4-1106-preview
  base_url: " https://api.groq.com/openai/v1"  # or forward url / other llm url
  api_key:

**Comment by seehi** [comment]
api_type: openai
