### ISSUE TITLE
metagpt "Create a 2048 game" report error "Illegal instruction“

### ISSUE THREAD

**Issue by mikevshu** [geekan/MetaGPT#1202]
**Bug description**

![image](https://github.com/geekan/MetaGPT/assets/90680089/40b6b91c-9e2b-4f5b-b925-a700de6d5214)

**Bug solved method**

**Environment information**

- LLM type and model name:
- System version:Linux OpenWrt 5.15.57 #0 SMP Mon Jul 25 02:57:31 2022 x86_64 GNU/Linux
- Python version:Python 3.9.16
- MetaGPT version or branch:

- packages version:
- installation method: 

**Screenshots or logs**

**Comment by seehi** [comment]
Docker? make sure have permissions for the relevant directories. please refer to [the Installation](https://docs.deepwisdom.ai/main/en/guide/get_started/installation.html)
