### ISSUE TITLE
简化安装

### ISSUE THREAD

**Issue by OopsYouDiedE** [geekan/MetaGPT#1208]
我多次尝试按照教程安装Metagpt，安装完毕后总是无法跑完程序，中途报错；
然后我用VScode 自动配置完Docker后，出现路径错误，无法安装playwright等一系列问题；
当然，这可能是我水平不够或是VPN的原因；但这仍然导致我无法跑通metagpt的大部分内容。
因此这里给出建议，可不可以直接搞一个打包好的完整环境能够直接运行所有程序，而不用去单独pip install?
还有一个建议；请在Bilibili和Youtube给出能够在国内完整安装和使用的视频教程；因为很多时候一些细节问题只有在视频中才能讲解清楚。

**Comment by seehi** [comment]
FYI: @voidking

**Comment by voidking** [comment]
https://deepwisdom.feishu.cn/wiki/BgauwZIVDihPNnkvGPbcuadtngs
