### ISSUE TITLE
Fixing existing code does not work again

### ISSUE THREAD

**Issue by AndPim4912** [geekan/MetaGPT#1210]
**Bug description**
I generated metagpt project. But I am not satisfied with dummy logic implementation. I want to apply corrections to generated project
I tried:
--project-path ... --inc
and
--project-path ... only
The docs and resources changes. But the generated code doesn't. The .py code files in project does not change. The new file mentioned in log are not created.
Running metagpt on existing project doesn't call metagpt.actions.write_code:run. Only metagpt.actions.write_code_plan_and_change_an:run.
Does metagpt support applying new requirements to project? 

**Bug solved method**
Have not tried to solve yet.

**Environment information**
Debian, python=3.11.2-1+b1, venv, 
I have this bug as on pip metagpt version, as on newest metagpt github release.

Model gpt-3.5-turbo

**Comment by seehi** [comment]
According to the [document](https://docs.deepwisdom.ai/main/en/guide/in_depth_guides/incremental_development.html#unresolved-issues), there are still some unresolved issues in incremental development.

**Comment by iorisa** [comment]
I've consolidated all the incremental development-related issues into #1498 to make it easier to follow up. Any new issues will be discussed in this newly opened issue, and the old issue will be closed.
