### ISSUE TITLE
data interpreter 论文中部分功能未提供代码实现

### ISSUE THREAD

**Issue by BiqiangWang** [geekan/MetaGPT#1214]
你好，针对论文[paper](https://arxiv.org/abs/2402.18679)中提到的一些功能，阅读代码后有一些疑问：
1. 文中提到工具部分实现了自动更新工具的功能，metaGPT代码中也有ToolRegistry类。但是di部分似乎并没有集成自动根据执行结果总结更新工具的功能？
2. 文中提到的集成外部经验池及后续任务检索经验池的功能。在代码中我只发现了metagpt/ext/werewolf/actions/experience_operation.py中有相关的实现，似乎di部分也没有相关内容？

**Comment by seehi** [comment]
DI的部分代码未开源，请关注后续版本。
