### ISSUE TITLE
Why do you make LLM config part of the package?

### ISSUE THREAD

**Issue by doitslow** [geekan/MetaGPT#1219]
It seems that someone has to install metagpt locally and modify config2.yaml to change llm config. Shouldn't the config path be a configurable variable to role?

**Comment by geekan** [comment]
~/.metagpt/config2.yaml is always first choice. If you're looking for a programable config, you can check this: https://github.com/geekan/MetaGPT/blob/main/tests/metagpt/test_context_mixin.py
