### ISSUE TITLE
How to continue the previous process after Sudden failure/如何继续刚才的失败进程

### ISSUE THREAD

**Issue by zezgithub** [geekan/MetaGPT#122]
Sudden failure（error） near the end of project execution, such as interruption due to network issues. How to continue the previous process after network recovery, instead of completely restarting the project?

项目执行接近尾声的时候突然失败，例如是网络原因导致中断。之后要网络恢复后要如何继续刚才的进程，而不是完全重新开始项目？

**Comment by voidking** [comment]
目前是不支持的

**Comment by Hezhexi2002** [comment]
> 目前是不支持的

后续有计划开发这个功能吗？

**Comment by voidking** [comment]
有的，在roadmap中了
https://github.com/geekan/MetaGPT/blob/main/docs/ROADMAP.md

**Comment by better629** [comment]
refs to `https://docs.deepwisdom.ai/main/en/guide/in_depth_guides/breakpoint_recovery.html`
