### ISSUE TITLE
no found the DAG graph mentioned in the paper(没有找到论文中提到的plan模块中的有向无环图，论文图3)

### ISSUE THREAD

**Issue by xiepeter** [geekan/MetaGPT#1226]
**Feature description**

**Your Feature**

**Comment by xiepeter** [comment]
<img width="940" alt="image" src="https://github.com/geekan/MetaGPT/assets/15033583/d141f922-4159-4fd2-b942-3d39bc3879cb">

**Comment by seehi** [comment]
[Topologically sort](https://github.com/geekan/MetaGPT/blob/main/metagpt/schema.py#L378)
