### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_index.vector_stores'

### ISSUE THREAD

**Issue by zhaoying9105** [geekan/MetaGPT#1232]
llama index == 0.10.0

**Comment by seehi** [comment]
[Installation Doc](https://docs.deepwisdom.ai/main/en/guide/in_depth_guides/rag_module.html#prepare)
[Setup](https://github.com/geekan/MetaGPT/blob/main/setup.py#L31)

**Comment by zhaoying9105** [comment]
> [Installation Doc](https://docs.deepwisdom.ai/main/en/guide/in_depth_guides/rag_module.html#prepare) [Setup](https://github.com/geekan/MetaGPT/blob/main/setup.py#L31)

thx
