### ISSUE TITLE
error exception when install metagpt,I can't finish install

### ISSUE THREAD

**Issue by tiantaiping2024** [geekan/MetaGPT#1233]
**Bug description**

ERROR: Exception:
Traceback (most recent call last):
  File "/Users/moonmovewhilecloudchange/opt/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/Users/moonmovewhilecloudchange/opt/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/Users/moonmovewhilecloudchange/opt/anaconda3/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "/Users/moonmovewhilecloudchange/opt/anaconda3/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/Users/moonmovewhilecloudchange/opt/anaconda3/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/moonmovewhilecloudchange/opt/anaconda3/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 383, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
**Bug solved method**

**Environment information**

- LLM type and model name:
- System version:
- Python version:
- MetaGPT version or branch:

- packages version:
- installation method: 

**Screenshots or logs**

**Comment by tiantaiping2024** [comment]
help me please

**Comment by seehi** [comment]
Try venv to create a clean environment to install, such as
```shell
python3 -m venv .venv
source .venv/bin/activate
pip3 install metagpt
```

**Comment by tiantaiping2024** [comment]
thank you,I did it, but still have some problems, help me pls:
(base) moonmovewhilecloudchange@192 ~ % 
(base) moonmovewhilecloudchange@192 ~ % python3 -m venv .venv
(base) moonmovewhilecloudchange@192 ~ % source .venv/bin/activate 
(.venv) (base) moonmovewhilecloudchange@192 ~ % pip3 install metagpt 
Collecting metagpt
  Using cached metagpt-0.8.1-py3-none-any.whl.metadata (15 kB)
INFO: pip is looking at multiple versions of metagpt to determine which version is compatible with other requirements. This could take a while.
  Using cached metagpt-0.8.0-py3-none-any.whl.metadata (15 kB)
  Using cached metagpt-0.7.7-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.7.6-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.7.4-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.7.3-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.7.2-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.7.1-py3-none-any.whl.metadata (12 kB)
INFO: pip is still looking at multiple versions of metagpt to determine which version is compatible with other requirements. This could take a while.
  Using cached metagpt-0.7.0-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.6.13-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.6.12-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.6.11-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.6.10-py3-none-any.whl.metadata (12 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached metagpt-0.6.9-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.6.8-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.6.7-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.6.6-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.6.5-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.6.4-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.6.3-py3-none-any.whl.metadata (12 kB)
  Using cached metagpt-0.6.2-py3-none-any.whl.metadata (12 kB)
  Downloading metagpt-0.6.1-py3-none-any.whl.metadata (12 kB)
  Downloading metagpt-0.6.0-py3-none-any.whl.metadata (12 kB)
  Downloading metagpt-0.5.2-py3-none-any.whl.metadata (10 kB)
  Downloading metagpt-0.5.1-py3-none-any.whl.metadata (10 kB)
  Downloading metagpt-0.5.0-py3-none-any.whl.metadata (10.0 kB)
  Downloading metagpt-0.4.0-py3-none-any.whl.metadata (9.5 kB)
  Downloading metagpt-0.3.0-py3-none-any.whl.metadata (14 kB)
  Downloading metagpt-0.1-py3-none-any.whl.metadata (7.2 kB)
ERROR: Cannot install metagpt==0.1, metagpt==0.3.0, metagpt==0.4.0, metagpt==0.5.0, metagpt==0.5.1, metagpt==0.5.2, metagpt==0.6.0, metagpt==0.6.1, metagpt==0.6.10, metagpt==0.6.11, metagpt==0.6.12, metagpt==0.6.13, metagpt==0.6.2, metagpt==0.6.3, metagpt==0.6.4, metagpt==0.6.5, metagpt==0.6.6, metagpt==0.6.7, metagpt==0.6.8, metagpt==0.6.9, metagpt==0.7.0, metagpt==0.7.1, metagpt==0.7.2, metagpt==0.7.3, metagpt==0.7.4, metagpt==0.7.6, metagpt==0.7.7, metagpt==0.8.0 and metagpt==0.8.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    metagpt 0.8.1 depends on aiohttp==3.8.6
    metagpt 0.8.0 depends on aiohttp==3.8.6
    metagpt 0.7.7 depends on aiohttp==3.8.4
    metagpt 0.7.6 depends on aiohttp==3.8.4
    metagpt 0.7.4 depends on aiohttp==3.8.4
    metagpt 0.7.3 depends on aiohttp==3.8.4
    metagpt 0.7.2 depends on aiohttp==3.8.4
    metagpt 0.7.1 depends on aiohttp==3.8.4
    metagpt 0.7.0 depends on aiohttp==3.8.4
    metagpt 0.6.13 depends on aiohttp==3.8.4
    metagpt 0.6.12 depends on aiohttp==3.8.4
    metagpt 0.6.11 depends on aiohttp==3.8.4
    metagpt 0.6.10 depends on aiohttp==3.8.4
    metagpt 0.6.9 depends on aiohttp==3.8.4
    metagpt 0.6.8 depends on aiohttp==3.8.4
    metagpt 0.6.7 depends on aiohttp==3.8.4
    metagpt 0.6.6 depends on aiohttp==3.8.4
    metagpt 0.6.5 depends on aiohttp==3.8.4
    metagpt 0.6.4 depends on aiohttp==3.8.4
    metagpt 0.6.3 depends on aiohttp==3.8.4
    metagpt 0.6.2 depends on aiohttp==3.8.4
    metagpt 0.6.1 depends on aiohttp==3.8.4
    metagpt 0.6.0 depends on aiohttp==3.8.4
    metagpt 0.5.2 depends on aiohttp==3.8.4
    metagpt 0.5.1 depends on aiohttp==3.8.4
    metagpt 0.5.0 depends on aiohttp==3.8.4
    metagpt 0.4.0 depends on aiohttp==3.8.4
    metagpt 0.3.0 depends on aiohttp==3.8.4
    metagpt 0.1 depends on aiohttp==3.8.4

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by tiantaiping2024** [comment]
I try to install aiohttp,but failed:
(.venv) (base) moonmovewhilecloudchange@192 ~ % pip3 install aiohttp==3.8.4 
ERROR: Could not find a version that satisfies the requirement aiohttp==3.8.4 (from versions: none)
ERROR: No matching distribution found for aiohttp==3.8.4

**Comment by tiantaiping2024** [comment]
I resolve this issue

**Comment by tiantaiping2024** [comment]
resolved

**Comment by Can1126** [comment]
> 我解决了这个问题

Can you share your workaround, I'm having the same issue
