### ISSUE TITLE
Docker support for MacOS

### ISSUE THREAD

**Issue by uros-mil** [geekan/MetaGPT#1237]
After installing docker image on Mac M2, docker-desktop app shows compatibility issues with AMD64 image.

Does provided docker image work on Mac with ARM processors, and is there some change I need to make to fix this?

I've tried to run `docker build -t metagpt:custom .` but it doesn't work - it's failing to install lib `psutil`. My docker knowledge is not sufficient to further debug this.

**Comment by voidking** [comment]
Currently there is no docker image for Mac M2. 
I tried to use `docker buildx` to build an image that supports arm, but failed.
If there is any progress later, we will reply to this issue again.
