### ISSUE TITLE
希望实现中文版或国际化

### ISSUE THREAD

**Issue by zkewind** [geekan/MetaGPT#1243]
**Feature description**
中文版或或国际化

**Your Feature**
提供中文版，例如提示词，产生的文档，代码注释等，都为中文。
或者提供国际化能力。

**Comment by geekan** [comment]
你好，现在我们还没有这个计划，但是由于没有对语言进行限制，所以你可以尝试使用中文作为输入，一般而言，它可以遵循用户的输入语言进行输出
