### ISSUE TITLE
What is the reason why the author encountered this encoding error when I ran -- run tests? I need to do this to avoid this issue

### ISSUE THREAD

**Issue by yxl23** [geekan/MetaGPT#1244]
![image](https://github.com/geekan/MetaGPT/assets/115678682/364505cd-ed54-416e-9b59-f0b527b72fbf)

![Uploading image.png…]()

**Comment by yxl23** [comment]
![image](https://github.com/geekan/MetaGPT/assets/115678682/8a72b720-57d3-437b-8f8b-772ca1db9bdb)

**Comment by geekan** [comment]
@voidking can you help look into this problem?

**Comment by voidking** [comment]
Please try the latest version. If there are still problems, please reopen this issue again.
