### ISSUE TITLE
question from beginner

### ISSUE THREAD

**Issue by Teddyduann** [geekan/MetaGPT#125]
Hello, I followed the instructions to deploy metagpt on my mac, while my first time testing it appears to not found specific module.

 File "/metagpt/startup.py", line 5, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'

Can anyone help me with this, im not familiar with coding

**Comment by voidking** [comment]
Follow [README](https://github.com/geekan/MetaGPT/blob/main/README.md) `Traditional Installation` section. Install all the dependencies first.

**Comment by Teddyduann** [comment]
Thanks for your soon reply, i reinstalled metagpt and i caught error like following : 

Download error on https://pypi.org/simple/typing-inspect/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002) -- Some packages may not be found!
Couldn't find index page for 'typing-inspect' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002) -- Some packages may not be found!
No local packages or working download links found for typing-inspect==0.8.0
error: Could not find suitable distribution for Requirement.parse('typing-inspect==0.8.0')

**Comment by MachineSaver** [comment]
I just wrote this up incase it'll help you get started on your project.

https://github.com/geekan/MetaGPT/issues/166
