### ISSUE TITLE
使用0.8.1版本时报如下错误日志，切换到0.7.7版本中恢复正常

### ISSUE THREAD

**Issue by nzk1912** [geekan/MetaGPT#1250]
**Bug description**
安装metagpt0.8.1，配置大模型使用阿里通义模型，运行时报如下错误：
```
ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 30.166(s), this was the 1st time calling it. exp: openai.types.completion_usage.CompletionUsage() argument after ** must be a mapping, not CompletionUsage
```

**Bug solved method**
切换metagpt到0.7.7版本，恢复正常

**Environment information**
- LLM type and model name:阿里通义千问，Qwen-72B-Chat
- System version:Red Hat Linux
- Python version:3.10.13
- MetaGPT version or branch:0.8.1 (0.8.0现象相同)

**Comment by chg0901** [comment]
https://github.com/geekan/MetaGPT/issues/1252#issuecomment-2106786292

#1252 

这个可以解决
