### ISSUE TITLE
RAG Embedding LLM + MetaGPT

### ISSUE THREAD

**Issue by Terry-cyx** [geekan/MetaGPT#1256]
I'm going to do a work which need LLM to read PDF. I found it's easy to do in LangChain with RecursiveCharacterTextSplitter and embeddings. But in MetaGPT, it seems hard to do.
I found embedding in config2.yaml, but do not know how to use it.
I'm using zhipuai, and the ZhipuAIEmbeddings, ZhipuAILLM are customized.
Here is my chain:
embedding = ZhipuAIEmbeddings(zhipuai_api_key=api_key)
vectordb = Chroma(persist_directory=persist_directory, embedding_function=embedding)
llm = ZhipuAILLM(model="glm-4", zhipuai_api_key=api_key,temperature=0)
retriever = vectordb.as_retriever(search_type="similarity", search_kwargs={"k": 6})
qa_interface = RetrievalQA.from_chain_type(
    llm,
    chain_type="stuff",
    retriever=retriever,
    return_source_documents=True,
)
I want the function "qa_interface()" instead of self._aask() for compatibility, and sincerely ask for your help

**Comment by seehi** [comment]
Zhipu embedding seems not yet supported by [Llama Index](https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/embeddings), need to create a [custom embedding](https://docs.llamaindex.ai/en/stable/examples/embeddings/custom_embeddings/) and pass to [`embed_model`](https://github.com/geekan/MetaGPT/blob/main/metagpt/rag/engines/simple.py#L82).
For more info, you can take a look at [RAG Module](https://docs.deepwisdom.ai/main/en/guide/in_depth_guides/rag_module.html).

**Comment by geekan** [comment]
@seehi can you add some documentation to clarify this issue?

**Comment by seehi** [comment]
> @seehi can you add some documentation to clarify this issue?

https://github.com/geekan/MetaGPT-docs/pull/151
