### ISSUE TITLE
Resume existing metagpt project, from generated code.

### ISSUE THREAD

**Issue by krish240574** [geekan/MetaGPT#1259]
**Bug description**

If I terminate a metagpt run, and want to add more features to generated code, metagpt starts a new workspace , does not consider already-generated code. 
Is there a way to fix this? Basically "Use the generated code inside  **path** and add to it, integrate changes with existing code in **path**"
This will be tremendously useful, to incrementally develop large applications, given the awesome code-generation, reflecion and review capabilities of metagpt. 
**Bug solved method**

**Environment information**

- LLM type and model name:
- System version:
- Python version:
- MetaGPT version or branch:

- packages version:
- installation method: 

**Screenshots or logs**

**Comment by geekan** [comment]
https://docs.deepwisdom.ai/main/en/guide/in_depth_guides/incremental_development.html#metagpt-options
