### ISSUE TITLE
clone main分支发现所有测试用例不能使用

### ISSUE THREAD

**Issue by kiedeng** [geekan/MetaGPT#1269]
**Bug description**
安装metagpt以后所有测试用例不能使用

**Bug solved method**
测试hello_world.py样例报错，无法执行，可能和llm返回内容相关？？

**Environment information**
- LLM type and model name: gpt-4-turbo （ gpt-3.5-turbo gpt-4-1106-preview都已经测试）
- System version: windows 
- Python version: Python 3.9.19 
- MetaGPT version or branch: 当前main分支

- packages version: 
- installation method:  git clone https://github.com/geekan/MetaGPT.git
**Screenshots or logs**
报错截图：
![image](https://github.com/geekan/MetaGPT/assets/36071456/3891f26b-fb8f-4b91-88f1-f7afa27ece67)

**Comment by kiedeng** [comment]
应该是openai返回格式原因导致，将模型切换为科大讯飞能正常调通（谢谢徐老师）。我应该改哪一步源码才能调通了。或者大佬们啥时候发个修复版本呢

**Comment by garylin2099** [comment]
Thanks for reporting, we determined it is an issue and are looking at it

**Comment by garylin2099** [comment]
Fixed in #1253
