### ISSUE TITLE
OSError in engineer.py when Attempting to Create Directory

### ISSUE THREAD

**Issue by cartpaul13** [geekan/MetaGPT#128]
Title: OSError in engineer.py when Attempting to Create Directory

Issue Description:

When executing the _act_sp method in engineer.py, I am encountering an OSError related to the file path. The full traceback is as follows:

`File "D:\My Projects\metagpt\metagpt\roles\engineer.py", line 140, in _act_sp
    file_path = self.write_file(todo, code)
  File "D:\My Projects\metagpt\metagpt\roles\engineer.py", line 97, in write_file
    file.parent.mkdir(parents=True, exist_ok=True)
  File "D:\anaconda3\envs\llm\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\My Projects\\metagpt\\workspace\\"ai_appointment_scheduler"\n\\"ai_appointment_scheduler"\n'`

It appears that the issue is related to the filename, directory name, or volume label syntax. Any help in resolving this would be appreciated.

Windows 11 and using Powershell with conda

**Comment by zarco67** [comment]
I'm getting this same error

**Comment by voidking** [comment]
What command did you execute? It seems that `\n` is brought when parsing the data.

**Comment by voidking** [comment]
@cartpaul13 @zarco67 Pull the latest code and try again please.
