### ISSUE TITLE
Is there a programming language limitation to generate code to ?

### ISSUE THREAD

**Issue by amitmiran137** [geekan/MetaGPT#129]

**Comment by voidking** [comment]
Currently only Python is supported. Support for other languages is already in the roadmap. Currently you can modify it yourself by searching for `".*(python|pep).*`.

**Comment by u007** [comment]
would love to see support for typescript and nodejs

**Comment by palashjhabak** [comment]
> Currently only Python is supported. Support for other languages is already in the roadmap. Currently you can modify it yourself by searching for `".*(python|pep).*`.

can you elaborate more on this temporary solution?

**Comment by zhic5352** [comment]
> > Currently only Python is supported. Support for other languages is already in the roadmap. Currently you can modify it yourself by searching for `".*(python|pep).*`.
> 
> can you elaborate more on this temporary solution?

Alsoooo looking forward to more detailed guidance.

**Comment by AndryHTC** [comment]
> Currently only Python is supported. Support for other languages is already in the roadmap. Currently you can modify it yourself by searching for `".*(python|pep).*`.

I think the https://github.com/users/geekan/projects/1/views/1?pane=issue&itemId=33737433 task should have ASAP priority. Most of the Devs approaching to MetaGPT are trying other tools, as Fine.dev

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
