### ISSUE TITLE
Validation Error 

### ISSUE THREAD

**Issue by cyborg3poch** [geekan/MetaGPT#1290]
ValidationError: 1 validation error for Config llm   Field required [type=missing, input_value={'PATH': '/Users/psyb0rg/..._INIT_AT_FORK': 'FALSE'}, input_type=dict]     For further information visit https://errors.pydantic.dev/2.7/v/missing

**Comment by usamimeri** [comment]
can you provide the content of your config2.yaml? The error message indicates that the llm field is missing from config2.yaml which should be:

```yaml
llm:
  api_type:…
  api_key:…
```

**Comment by usamimeri** [comment]
> > Can you provide the content of your config2.yaml? The error message indicates that the llm field is missing from config2.yaml which should be:
> > ```yaml
> > llm:
> >   api_type:…
> >   api_key:…
> > ```
> 
> I use Gemini and this is my content but it's still have validation error
> 
> ```
> llm:
>   api_type: "gemini"
>   model: "gemini-pro"
>   api_key: "My_API_Key"
> ```

It works for me. Try to pull the latest code to ensure everything is up-to-date.

**Comment by garylin2099** [comment]
> ValidationError: 1 validation error for Config llm Field required [type=missing, input_value={'PATH': '/Users/psyb0rg/..._INIT_AT_FORK': 'FALSE'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.7/v/missing

Make sure you have updated ~/.metagpt/config2.yaml or config/config2.yaml (for detail please see [here](https://docs.deepwisdom.ai/main/en/guide/get_started/configuration/llm_api_configuration.html)). Can you check if the problem still exists?
