### ISSUE TITLE
redirect Gemini api base url

### ISSUE THREAD

**Issue by jackiezhangcn** [geekan/MetaGPT#1302]
Hello, could someone know how to change the api base url for Gemini ? I tried to config base_url in the config2.yaml file, but no effects, I don't know where (or which file) defined googlegenarative python package to access the original api port.

Appreciated!

**Comment by garylin2099** [comment]
Hi! Can you provide your config file (hide your key), your testing code, and the error logs?

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
