### ISSUE TITLE
建议示例代码和框架代码存放位置分离-保持框架代码的整洁性和易读性

### ISSUE THREAD

**Issue by acemos2048** [geekan/MetaGPT#1308]
**Feature description**
目前0.8.1版本中metagpt/role、metagpt/actions、metagpt/prompts目录下面存在大量example相关的代码。
比如调查员示例(example/research.py)中引用了metagpt/role/researcher。
个人认为:
1. example中的代码是在metagpt上的应用，属于业务代码。
2. metagpt中的代码是框架代码，是所有业务代码的底座

按照现在将example代码放到metagpt目录的做法，后面随着example越来越多metagpt里面的文件会越来越多。
从新手的角度来看代码文件越多，对整个框架的理解越难。
而且现在一个example使用到的role、action、promopt分散在metagpt的目录中，只有通过代码一步步查看才能知道这个example用了哪些role和action。

**Your Feature**
建议将example相关的文件都挪到example目录，metagpt只保留框架相关的代码。
以一个名为research的example为例，所有research相关的代码都放在example/research下面
示例的目录结构建议如下：

├── example
│   └── research   //示例名称文件夹
│       ├── README.md //说明文档
│       ├── actions  
│       │   ├── action1.py
│       │   └── action2.py
│       ├── main.py  //示例入口
│       ├── prompts
│       │   └── prompt.py
│       └── roles
│           ├── role1.py
│           └── role2.py

**Comment by geekan** [comment]
Hello, we will find time to refactor in the next few months.

**Comment by usamimeri** [comment]
这个主意不错，后续会分离example的组件和基础组件
