### ISSUE TITLE
MetaGPT Typescript version

### ISSUE THREAD

**Issue by JamieLee0510** [geekan/MetaGPT#1310]
Hi MetaGPT Team,

I've created a TypeScript version of MetaGPT, which currently includes implementations for Role, Action, and Environment. At present, this version only uses the OpenAI SDK, whereas the official MetaGPT supports multiple LLM models. I plan to continue expanding this version and would welcome any contributions or feedback.

You can find the repository here: [MetaGPT-ts](https://github.com/JamieLee0510/MetaGPT-ts)

Looking forward to your thoughts and contributions!

Best regards,
Jamie

**Comment by geekan** [comment]
Great work!

**Comment by usamimeri** [comment]
厉害啊，这个对学MetaGPT和Typescript都很有帮助！后续可以考虑把这个加到用例中。
