### ISSUE TITLE
[Question] Docker image has not been updated for 3 months

### ISSUE THREAD

**Issue by yhyu13** [geekan/MetaGPT#1317]
Hi,

I just found out that the dokcer image stuck at v0.7.4 for 3 months https://hub.docker.com/r/metagpt/metagpt/tags. Is metagpt still support docker running? The intallation page still mentions docker though. https://docs.deepwisdom.ai/main/en/DataInterpreter/
Would you like to update the docker image to v0.8.1 https://github.com/geekan/MetaGPT/releases/tag/v0.8.1? 

Thanks!

**Comment by voidking** [comment]
Thanks for your reminder. The docker version has been updated.

**Comment by yhyu13** [comment]
Thanks!
