### ISSUE TITLE
Unable to run metagpt

### ISSUE THREAD

**Issue by yousia33** [geekan/MetaGPT#1322]
(metagpt) PS F:\codetest\Metagpt> metagpt "create a 2048 game"
2024-06-05 16:46:27.754 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to f:\codetest\metagpt
╭─────────────────────── Traceback (most recent call last) ────────────────────────╮
│ f:\codetest\metagpt\metagpt\software_company.py:108 in startup                   │
│                                                                                  │
│   105 │   │   typer.echo("Missing argument 'IDEA'. Run 'metagpt --help' for more │
│   106 │   │   raise typer.Exit()                                                 │
│   107 │                                                                          │
│ ❱ 108 │   return generate_repo(                                                  │
│   109 │   │   idea,                                                              │
│   110 │   │   investment,                                                        │
│   111 │   │   n_round,                                                           │
│                                                                                  │
│ f:\codetest\metagpt\metagpt\software_company.py:30 in generate_repo              │
│                                                                                  │
│    27 │   recover_path=None,                                                     │
│    28 ) -> ProjectRepo:                                                          │
│    29 │   """Run the startup logic. Can be called from CLI or other Python scrip │
│ ❱  30 │   from metagpt.config2 import config                                     │
│    31 │   from metagpt.context import Context                                    │
│    32 │   from metagpt.roles import (                                            │
│    33 │   │   Architect,                                                         │
│                                                                                  │
│ f:\codetest\metagpt\metagpt\config2.py:164 in <module>                           │
│                                                                                  │
│   161 │   return result                                                          │
│   162                                                                            │
│   163                                                                            │
│ ❱ 164 config = Config.default()                                                  │
│   165                                                                            │
│                                                                                  │
│ f:\codetest\metagpt\metagpt\config2.py:106 in default                            │
│                                                                                  │
│   103 │   │   dicts = [dict(os.environ)]                                         │
│   104 │   │   dicts += [Config.read_yaml(path) for path in default_config_paths] │
│   105 │   │   final = merge_dict(dicts)                                          │
│ ❱ 106 │   │   return Config(**final)                                             │
│   107 │                                                                          │
│   108 │   @classmethod                                                           │
│   109 │   def from_llm_config(cls, llm_config: dict):                            │
│                                                                                  │
│ F:\anacoda\envs\metagpt\Lib\site-packages\pydantic\main.py:176 in __init__       │
│                                                                                  │
│    173 │   │   """                                                               │
│    174 │   │   # `__tracebackhide__` tells pytest and some other tools to omit t │
│    175 │   │   __tracebackhide__ = True                                          │
│ ❱  176 │   │   self.__pydantic_validator__.validate_python(data, self_instance=s │
│    177 │                                                                         │
│    178 │   # The following line sets a flag that we use to determine when `__ini │
│    179 │   __init__.__pydantic_base_init__ = True  # pyright: ignore[reportFunct │
╰──────────────────────────────────────────────────────────────────────────────────╯
ValidationError: 1 validation error for Config
llm.api_key
  Value error, Please set your API key in config2.yaml [type=value_error,
input_value='YOUR_API_KEY', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error 

# MY config：llm:
  api_type: "qianfan"
  access_key: "XXX"
  secret_key: "XXX"
  model: 'ERNIE-3.5-8K'

**Comment by usamimeri** [comment]
> 
> # MY config：llm:
> api_type: "qianfan" access_key: "GWzMbdC" secret_key: "QUnQH0LRfnHL432X" model: 'ERNIE-3.5-8K'

don't post your key here, revoke it.

**Comment by usamimeri** [comment]
```shell
Value error, Please set your API key in config2.yaml [type=value_error,
input_value='YOUR_API_KEY', input_type=str]
```
indicated that you didn't set your API_KEY in config.yaml. This might because there is also a config.yaml in your Home directory, and MetaGPT read the configuration from there, which overrides your local settings. You can test this with the following code:
```python
from metagpt.const import CONFIG_ROOT
import os
print(CONFIG_ROOT)
print(os.path.exists(CONFIG_ROOT))
```
You can delete it if it exists.

For more information: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py#L98-L106

**Comment by yousia33** [comment]
> ```shell
> Value error, Please set your API key in config2.yaml [type=value_error,
> input_value='YOUR_API_KEY', input_type=str]
> ```
> 
> indicated that you didn't set your API_KEY in config.yaml. This might because there is also a config2.yaml in your Home directory, and MetaGPT read the configuration from there, which overrides your local settings. You can test this with the following code:
> 
> ```python
> from metagpt.const import CONFIG_ROOT
> import os
> print(CONFIG_ROOT)
> print(os.path.exists(CONFIG_ROOT))
> ```
> 
> You can delete it if it exists.
> 
> For more information: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py#L98-L106

Thanks! This helps a lot!
