### ISSUE TITLE
metagpt from pip install is not the latest one

### ISSUE THREAD

**Issue by HeMuling** [geekan/MetaGPT#1326]
从pip install下载的metagpt版本落后于github上的版本

范例文件：`metagpt/utils/token_counter.py`

pip install 下载的metagpt不包含`gpt-4o`，而github上的版本则包含

建议：更新pip源或更改doc中安装方式

**Comment by voidking** [comment]
感谢建议，pip版本是会稍微落后于github main分支。实际上我们的文档中提供了多种安装方式，包括pip安装和github安装，可以参考 https://docs.deepwisdom.ai/main/en/guide/get_started/installation.html
