### ISSUE TITLE
Model general not found in TOKEN_COSTS

### ISSUE THREAD

**Issue by moonlightnoodles** [geekan/MetaGPT#1333]
**Bug description**

when I successfully run some command such as "metagpt "write a snake game", it warns me that "metagpt "write a snake game". Will this warning affect effects of my project?

**Environment information**

- LLM type and model name: spark
- Python version: 3.10
- MetaGPT version or branch: main(?)

- installation method: git clone https://github.com/geekan/MetaGPT.git

**Screenshots or logs**

![image](https://github.com/geekan/MetaGPT/assets/123880310/31c26eee-9026-4007-bb0f-080fed30f290)

**Comment by usamimeri** [comment]
It will not affect your project as it is just a calculate the cost of api call.

**Comment by david-zlj** [comment]
使用阿里云qwen-max模型时，也出现类似错误，估计是个bug
![image](https://github.com/geekan/MetaGPT/assets/42892045/61fd4e1b-8863-45b3-8ec4-edb2f989f448)

**Comment by usamimeri** [comment]
https://github.com/geekan/MetaGPT/pull/1284

@geekan 

> 使用阿里云qwen-max模型时，也出现类似错误，估计是个bug ![image](https://private-user-images.githubusercontent.com/42892045/341329852-61fd4e1b-8863-45b3-8ec4-edb2f989f448.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzE2ODgsIm5iZiI6MTcxODg3MTM4OCwicGF0aCI6Ii80Mjg5MjA0NS8zNDEzMjk4NTItNjFmZDRlMWItODg2My00NWIzLThlYzQtZWRiMmY5ODlmNDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA4MTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmOTQ5YTk4MmUwMTc4YzM1ZmVmOWIyNjFkYTIzMjQyYjNlNzllMGY0MDM5ZDlhYTQyYjkyMDdhZDQ3MGY2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Aln6EqlMDJj_PaMpcKQmFZUt5_oUgsvRXZK-dSRfcBw)

**Comment by geekan** [comment]
https://github.com/geekan/MetaGPT/pull/1284 fixed this

**Comment by Zemelee** [comment]
when you use free models,it will happen.
