### ISSUE TITLE
Not able to run any MetaGPT examples

### ISSUE THREAD

**Issue by amd-srautmar** [geekan/MetaGPT#1345]
Referred Issue #1322 , but not able to resolve the issue. I added azure based api endpoint and api key in config2.yaml

│   105 │   │   typer.echo("Missing argument 'IDEA'. Run 'metagpt --help' for more information."   │
│   106 │   │   raise typer.Exit()                                                                 │
│   107 │                                                                                          │
│ ❱ 108 │   return generate_repo(                                                                  │
│   109 │   │   idea,                                                                              │
│   110 │   │   investment,                                                                        │
│   111 │   │   n_round,                                                                           │
│                                                                                                  │
\metagpt\software_company.py:30 in generate_repo          │
│                                                                                                  │
│    27 │   recover_path=None,                                                                     │
│    28 ) -> ProjectRepo:                                                                          │
│    29 │   """Run the startup logic. Can be called from CLI or other Python scripts."""           │
│ ❱  30 │   from metagpt.config2 import config                                                     │
│    31 │   from metagpt.context import Context                                                    │
│    32 │   from metagpt.roles import (                                                            │
│    33 │   │   Architect,                                                                         │
│                                                                                                  │
\new_meta_env\Lib\site-packages\metagpt-0.8.1-py3.11.egg\metagpt\ │
│ config2.py:164 in <module>                                                                       │
│                                                                                                  │
│   161 │   return result                                                                          │
│   162                                                                                            │
│   163                                                                                            │
│ ❱ 164 config = Config.default()                                                                  │
\new_meta_env\Lib\site-packages\metagpt-0.8.1-py3.11.egg\metagpt\ │
│ config2.py:106 in default                                                                        │
│                                                                                                  │
│   103 │   │   dicts = [dict(os.environ)]                                                         │
│   104 │   │   dicts += [Config.read_yaml(path) for path in default_config_paths]                 │
│   105 │   │   final = merge_dict(dicts)                                                          │
│ ❱ 106 │   │   return Config(**final)                                                             │
│   107 │                                                                                          │
│   108 │   @classmethod                                                                           │
│   109 │   def from_llm_config(cls, llm_config: dict):                                            │
│                                                                                                  │
\new_meta_env\Lib\site-packages\pydantic\main.py:176 in __init__  │
│                                                                                                  │
│    173 │   │   """                                                                               │
│    174 │   │   # `__tracebackhide__` tells pytest and some other tools to omit this function fr  │
│    175 │   │   __tracebackhide__ = True                                                          │
│ ❱  176 │   │   self.__pydantic_validator__.validate_python(data, self_instance=self)             │
│    177 │                                                                                         │
│    178 │   # The following line sets a flag that we use to determine when `__init__` gets overr  │
│    179 │   __init__.__pydantic_base_init__ = True  # pyright: ignore[reportFunctionMemberAccess  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValidationError: 1 validation error for Config
llm
  Field required [type=missing, input_value={'ALLUSERSPROFILE': 'C:\\..._INIT_AT_FORK': 'FALSE'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing

**Comment by voidking** [comment]
Looks like there are some configuration errors with base_url or api_key. You can refer to: https://learn.microsoft.com/en-us/troubleshoot/azure/api-mgmt/availability/unauthorized-errors-invoke-apis

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
