### ISSUE TITLE
use java, but 'Required Python packages' in PM_NODE_AN

### ISSUE THREAD

**Issue by candowu** [geekan/MetaGPT#1347]
metagpt.actions.action_node:_aask_v1:421 - llm raw output:
[CONTENT]
{
    "Required Other language third-party packages": [
        "feign-client",
        "springframework",
        "hystrix",
        "lombok"
    ],
    "Logic Analysis": [...]
    "...":"..."
}
[/CONTENT]

 ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 16.047(s), this was the 1st time calling it. exp: 1 validation error for PM_NODE_AN
  Value error, Missing fields: {'Required Python packages'} [type=value_error, input_value={'Required Other language...nd adjust accordingly."}, input_type=dict]

**Comment by voidking** [comment]
What is your promts? Try this:
```bash
metagpt "write a cli snake game by java"
```

**Comment by candowu** [comment]
I think the problem should be that although the Java language is used, the key: Required Python packages in the output information need to be retained

**Comment by vvvsilla** [comment]
Here is my output. It seems no `Required Python packages` in the output information. Which metagpt version did you use?
[metagpt.log](https://github.com/user-attachments/files/15894612/metagpt.log)

**Comment by voidking** [comment]
Here is my output. It seems no `Required Python packages` in the output information. Which metagpt version did you use?
[metagpt.log](https://github.com/user-attachments/files/15894622/metagpt.log)
