### ISSUE TITLE
Will you add embedding support for Claude api

### ISSUE THREAD

**Issue by chosenlu** [geekan/MetaGPT#1351]
Feature description
The current feature involves adding support for embedding of Claude, a specific software or component, within the existing system. This functionality will enable users to seamlessly integrate and utilize Claude within their workflow.
 
Your Feature
I am proposing the implementation of support for embedding Claude within our system. This can be achieved by updating the codebase to accommodate the necessary requirements for integrating Claude. I will also ensure that the corresponding documentation, tests, and examples are completed to facilitate the verification process by the reviewers.
 
If you have already created a Pull Request for this feature, please provide the URL address for further review.

**Comment by seehi** [comment]
[Anthropic](https://docs.anthropic.com/en/docs/build-with-claude/embeddings) does not offer its own embedding model, are you referring to 'Voyage AI'?

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
