### ISSUE TITLE
    from llama_index.embeddings.gemini import GeminiEmbedding ModuleNotFoundError: No module named 'llama_index.embeddings.gemini'

### ISSUE THREAD

**Issue by ALLISWELL8** [geekan/MetaGPT#1364]
**Bug description**

**Bug solved method**

**Environment information**

- LLM type and model name:
- System version:
- Python version:
- MetaGPT version or branch:

- packages version:
- installation method: 

**Screenshots or logs**

**Comment by voidking** [comment]
What command and config did you use? How to reproduce it?
