### ISSUE TITLE
接入Amazon Bedrock API失败

### ISSUE THREAD

**Issue by wuduher** [geekan/MetaGPT#1370]
**AWS的Claude API不包含在官方文档内，如何接入？**

**
config2.yaml:
llm:
  api_type: 'bedrock'
  model: 'anthropic.claude-3-opus-20240229-v1:0:48k'
  region_name: 'us-west-2' # e.g. us-east-1

报错
ValidationError: 1 validation error for Config
llm.api_type
  Input should be 'openai', 'anthropic', 'claude', 'spark', 'zhipuai',
'fireworks', 'open_llm', 'gemini', 'metagpt', 'azure', 'ollama', 'qianfan',
'dashscope', 'moonshot', 'mistral' or 'yi' [type=enum, input_value='bedrock',
input_type=str]

可是样例里不是有bedrock吗
![image](https://github.com/geekan/MetaGPT/assets/155968160/4a850fef-b759-45a5-851f-618752c5ef13)

**

**Comment by usamimeri** [comment]
尝试更新到最新版本的MetaGPT

**Comment by wuduher** [comment]
> 尝试更新到最新版本的MetaGPT

我是直接拉最新镜像的，这样不属于最新版本吗？

**Comment by usamimeri** [comment]
> > 尝试更新到最新版本的MetaGPT
> 
> 我是直接拉最新镜像的，这样不属于最新版本吗？

目前的镜像对应的是最新的Release版本，也就是4月末的，bedrock那时候还没被支持

**Comment by pzw943969386** [comment]
> > 尝试更新到最新版本的MetaGPT
> 
> 我是直接拉最新镜像的，这样不属于最新版本吗？

直接 pip install git+https://github.com/geekan/MetaGPT.git 拉取最新的代码
