### ISSUE TITLE
问几个问题

### ISSUE THREAD

**Issue by hiro110110** [geekan/MetaGPT#1375]
1.metagpt是通过RoleContext来感知环境做下一步决策，那就表示代码编写完成后根据需求不同流程会自动进行调整，为何我看到每一个示例的代码都不一样，不是应该一套代码解决至少一类问题么。示例都是在生成简单游戏，我认为这应该是同一类，请解答一下为何每一个小游戏都要单独编写？
2.metagpt作为一套多智能体框架，应该多出一些java项目，毕竟java当下还算主流之一，一整套代码应该是包含前端、后台、样式，如果是java+vue+css组合起来的代码如何实现通过agent做测试？
3.针对某些公司肯定有自己公司的代码模板和开发规范，这些数据是不允许外泄的且随着时间的沉淀数据量越来越多、业务量越来越复杂，如何让生成的代码是符合公司规范的呢？如何让生成的代码包含拓展业务的？帮忙用示例说明一下。

**Comment by voidking** [comment]
1. 软件公司可以生成多样的代码，其中游戏是比较有趣的，因此生成的多一些。其他示例也有很多，可以访问 https://www.deepwisdom.ai/ 进行查看
2. 默认是python，想要使用java，直接提示使用java开发就好，例如 `metagpt "write a snake game by java"`。同样的，要指定语言和框架，那么描述清楚使用 java+vue+css 就可以。
3. 防止数据外泄，可以搭建自己的大模型并调用。想要代码符合公司规范，需要自己定制一下提示词，修改[engineer.py](https://github.com/geekan/MetaGPT/blob/main/metagpt/roles/engineer.py)或者自己实现一个Role，要求生成的代码遵循某某某规范。
