### ISSUE TITLE
OPENAI API无法在国内使用，如何自定义添加其他闭源模型的API

### ISSUE THREAD

**Issue by Leekinxun** [geekan/MetaGPT#1377]
如题，如何自定义添加其他闭源模型的API,类似已有的ZHIPUAI那样，应该更改添加哪些步骤的代码，感谢！

**Comment by voidking** [comment]
可以参考这个文档 https://docs.deepwisdom.ai/main/en/guide/get_started/configuration/llm_api_configuration.html

**Comment by xinyuzhidad** [comment]
如何自定义一个provider呢？有没有实例代码？

**Comment by Leekinxun** [comment]
> 可以参考这个文档 https://docs.deepwisdom.ai/main/en/guide/get_started/configuration/llm_api_configuration.html

感谢你的回复，我想了解如何自定义添加未内置的闭源头模型API，例如豆包，混元

**Comment by shenchucheng** [comment]
> > 可以参考这个文档 https://docs.deepwisdom.ai/main/en/guide/get_started/configuration/llm_api_configuration.html
> 
> 感谢你的回复，我想了解如何自定义添加未内置的闭源头模型API，例如豆包，混元

这个目录下除了BaseLLM，所有的provider都可以作为参考代码： https://github.com/geekan/MetaGPT/tree/main/metagpt/provider
正常流程就是自定义自己的 Provider类，补全_achat_completion（非流式）、_achat_completion_stream（流式）等方法，如果要贡献给社区，需要使用register_provider装饰器，添加LLMType枚举，如果配置参数不够，还需要加下config定义。更特殊一点的可以看下HumanProvider，其实只要实现后，aask/ask能有正常返回就可以了

**Comment by better629** [comment]
Since no further responses are needed, we will close it. Please reopen it if necessary.
