### ISSUE TITLE
如何自定义一个provider呢？比如包装文心一言，或者自己自定义的大模型？有没有实例代码？

### ISSUE THREAD

**Issue by xinyuzhidad** [geekan/MetaGPT#1378]
求各位大佬，提供一个provider类，或者该修改哪些模型呢

**Comment by voidking** [comment]
同 #1377

**Comment by Leekinxun** [comment]
同，目前场景是自己封装了一个大模型中间件，包含了所有国内闭源大模型的API，希望可以直接接入，通过更改配置文件实现模型更换，希望有大佬能提供类似的案例或者修改步骤，谢谢佬们
