### ISSUE TITLE
TypeError from 'async for'

### ISSUE THREAD

**Issue by yudizhangzyd** [geekan/MetaGPT#1380]
**Bug description**
ERROR    | metagpt.utils.common:wrapper:631 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/dev_env/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/dev_env/lib/python3.10/site-packages/metagpt/actions/action_node.py", line 420, in _aask_v1
    content = await self.llm.aask(prompt, system_msgs, images=images, timeout=timeout)
TypeError: 'async for' requires an object with __aiter__ method, got bytes

**config as follows**
llm:
  api_type: 'openai' 
  model: 'gpt-3.5-turbo'  
  base_url: 'https://api.openai.com/v1'  
  api_key: '*************'

Does anyone has this issue before? Thanks

**Comment by shenchucheng** [comment]
Is your network able to access the OpenAI API properly? It is recommended to first try verifying this using curl, for example:
```
 curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -d '{
    "stream": true,
    "model": "gpt-3.5-turbo",
    "messages": [{"role": "system", "content": "Hello"}]
  }'
```

**Comment by shenchucheng** [comment]
Closing this issue due to prolonged inactivity. If there's any further information or assistance needed, feel free to reopen the issue or create a new one. Thanks!
