### ISSUE TITLE
关于message pools

### ISSUE THREAD

**Issue by hmppt** [geekan/MetaGPT#1388]
1. 请问不同代理实体之间是怎么实现向消息池检索信息的呢？
我的理解是：任何代理角色都将消息发送到消息池，然后等待其他代理角色去捞这个消息，而不是说直接指派给其他代理？

2. 基于消息池，使得不同代理之间不必串行运行吗？比如A可以一次生成两个不同的消息派送给B和C，然后B和C可以同时工作，然后B可能把消息派送给E，C可能派送给D。

**Comment by shenchucheng** [comment]
1. 智能体之间通过Environment进行交互，最早的基础Environment实现，就是任何代理角色都将消息发送到ENV，然后代理角色可以从ENV中观察自己感兴趣的消息。但是后面为了整体更加灵活，所以做了改造，消息仍然通过Environment交互，但每个代理角色有自己的"信箱"，Environment需要负责实现消息接收/转发逻辑，这样除了群发，也可以私发给某个代理角色。
2. 基于1，已经是可以实现2的需求的，是否串行取决于代理角色的运行的形式，例如软件公司的demo是通过多轮的多个代理角色并发运行实现的，不同轮次之间是串行的，因为软件公司不同智能体之间是按顺序依赖的，每一轮实际只会有一个代理角色在工作，所以看起来像是串行。但实际上，这些代理角色完全是可以并发执行的，**只需要为每个代理角色创建一个处理消息的循环，然后让这些循环并发运行**，就可以实现无依赖关系的代理角色同时工作

**Comment by hmppt** [comment]
感谢回答！
