### ISSUE TITLE
想要更改一些模型比如千帆大模型的请求url

### ISSUE THREAD

**Issue by yuhao382** [geekan/MetaGPT#1392]
因为某些原因，有一些闭源大模型在本地部署，如何更改类似于千帆大模型请求的地址url？

**Comment by shenchucheng** [comment]
正常修改配置中`llm.base_url`的值就可以了。不过看了一下代码，MetaGPT在实现千帆模型支持的时候，没有传递base_url，这个接下来会修复一下，不过在此之前，按照千帆的文档，你可以试着设置一下QIANFAN_BASE_URL或者是直接在代码中执行：
```python
from qianfan.config import get_config

get_config().BASE_URL = "xxxx"
```

**Comment by yuhao382** [comment]
谢谢！
