### ISSUE TITLE
Werewolf game has ended, but the team is still running idle

### ISSUE THREAD

**Issue by yingfeng2016** [geekan/MetaGPT#1399]
**Bug description**
如果n_round和investment都设置较大，观察Moderator已经输出game over，但team的run方法内部仍在无效循环，并遍历运行每个role的run

**Bug solved method**
team的run中，每一次round，遍历所有role，如果所有role的len(self.rc.news) 都等于0，那么跳出循环

**Environment information**
MetaGPT version or branch:master

**Screenshots or logs**
![image](https://github.com/user-attachments/assets/a77002cb-6579-4966-b696-b1b06848c1ef)
![image](https://github.com/user-attachments/assets/9bb56b86-a628-432d-adf8-009294d06d3a)

**Comment by shenchucheng** [comment]
非常感谢，很好的建议，方便的话可以提个PR吗？注意到`Environment.is_idle`应该是可以作为循环退出的依据
