### ISSUE TITLE
Set  custom LLM Rerank like as voyage

### ISSUE THREAD

**Issue by tuanlv14** [geekan/MetaGPT#1401]
**Feature description**
I see embedding Configuration but I did not see any instruction to set  Reranker.

Request. -->
If setting ranker was not avaiable, pls add this one. Pls consider voyage, Cohere and Jina
If setting ranker was avaiable, pls help me with an instructtion like as embedding Configuration.

**Comment by tuanlv14** [comment]
Hi all, anyone can help me to config ranker in metaGPT ? Thanks.

**Comment by seehi** [comment]
Currently, Cohere is available and can be [configured](https://github.com/geekan/MetaGPT/blob/main/metagpt/rag/schema.py#L123), but you need to install `llama-index-postprocessor-colbert-rerank` first.
```python
engine = SimpleEngine.from_docs(input_files=input_files, ranker_configs=[CohereRerankConfig(api_key="YOUR_API_KEY")])
```

Others can also be customized, such as voyage.
```python
from from llama_index.postprocessor.voyageai_rerank import VoyageAIRerank

engine = SimpleEngine.from_docs(input_files=input_files)
engine._node_postprocessors = [VoyageAIRerank(api_key="YOUR_API_KEY")]
```
