### ISSUE TITLE
The EIP currently points to EIP-158, which was never deployed, and should point to EIP-161.

### ISSUE THREAD

**Issue by AnitaLHoward** [geekan/MetaGPT#1403]
The EIP currently points to EIP-158, which was never deployed, and should point to EIP-161.

_Originally posted by @jochem-brouwer in https://github.com/ethereum/EIPs/pull/8738_

**Comment by shenchucheng** [comment]
It looks like this issue was opened in the wrong repository. We are MetaGPT. I'll go ahead and close this issue.
