### ISSUE TITLE
Unable to access the online document via HTTPS

### ISSUE THREAD

**Issue by iridium-soda** [geekan/MetaGPT#1407]
The HTTPS certificate for the online document website (docs.deepwisdom.ai) has expired. As a result, I am unable to access the site safely by default.

Please address this issue at your earliest convenience to ensure secure access to the documentation.

<img width="381" alt="image" src="https://github.com/user-attachments/assets/66611a32-476c-46c3-934a-a069109e887d">

<img width="324" alt="image" src="https://github.com/user-attachments/assets/41121064-c2d0-4097-b715-36852aa4e4f0">

**Comment by voidking** [comment]
Thanks for the feedback. Fixed.
