### ISSUE TITLE
Does MetaGPT suppport upload files

### ISSUE THREAD

**Issue by GlassyAmadeus** [geekan/MetaGPT#1409]
Does MetaGPT suppport upload files through func like openai:

file = client.files.create( 
    file=open("src.zip", "rb"),
    purpose='assistants'
)

**Comment by GlassyAmadeus** [comment]
And in addition, can I use the openai default tools like code_interpreter or file_search in MetaGPT?

**Comment by shenchucheng** [comment]
MetaGPT does not use OpenAI's File API for uploading files, nor does it directly use OpenAI's default tools. Whether this will be supported in the future requires further discussion.
