### ISSUE TITLE
can I let the software company use the third-party package?

### ISSUE THREAD

**Issue by visionKinger** [geekan/MetaGPT#1410]
**Feature description**
user can provide some third-party package for software, like opencv

**Comment by shenchucheng** [comment]
Do you want the software company to use the third-party package you specified to fulfill the requirement? You can try specifying the package you wish to use directly in the IDEA parameter.

**Comment by visionKinger** [comment]
I tried to put the package in the idea,it didn't work> Do you want the software company to use the third-party package you specified to fulfill the requirement? You can try specifying the package you wish to use directly in the IDEA parameter.

**Comment by visionKinger** [comment]
I'm using gpt-4o

**Comment by shenchucheng** [comment]
Could you provide the idea parameter you use? I will try it later.
