### ISSUE TITLE
Security Vulnerability in MetaGPT

### ISSUE THREAD

**Issue by pwntester** [geekan/MetaGPT#1414]
Hi, I would like to report a security vulnerability. I sent an email to the address specified in the security policy but did not get any answers for a month. Can you please enable GitHub's Private Vulnerability Reporting to send the details to?

/cc @geekan @better629 @garylin2099 @orange-crow

**Comment by voidking** [comment]
@pwntester Thanks for your reminder. I'm very sorry, I was busy with other things recently and forgot to reply to the email. I have just replied to your email, please check.
