### ISSUE TITLE
Please add more roles / agents 

### ISSUE THREAD

**Issue by abdshomad** [geekan/MetaGPT#142]
I would suggest to add more roles/agents to make the software development team more complete, such as: Dev Ops, UX, DBA, etc. Here's some suggested agents/roles to add: 

* User Experience (UX) Designer: Focuses on designing the user interface and user experience of the software.
DevOps Engineer: Integrates development and operations processes to facilitate continuous integration and deployment.
* Database Administrator (DBA): Manages and maintains the database systems used by the software.
* Front-end Developer: Specializes in creating the user interface and user interactions of the software.
* Back-end Developer: Handles server-side logic and database interactions to support the software's functionality.
* Systems Administrator: Manages IT infrastructure and ensures smooth operations.

Those roles/agents are responsible to create scripts like: Dockerfile, docker-compose.yaml, helm chart, ansible playbook, nginx / traefik config, terraform, ERD, etc.

**Comment by voidking** [comment]
Good suggestion, some roles already in the roadmap.

**Comment by ChristianWeyer** [comment]
Is there an official and public version of the roadmap @voidking ?

**Comment by better629** [comment]
`https://github.com/geekan/MetaGPT/blob/main/docs/ROADMAP.md`
