### ISSUE TITLE
应用程序提供API接入能力

### ISSUE THREAD

**Issue by 9989836** [geekan/MetaGPT#1423]
请问MetaGPT何时会支持API应用程序的接入,  有具体的时间计划么?

**Comment by iorisa** [comment]
你是在问[DataInterpreter](https://docs.deepwisdom.ai/main/en/guide/use_cases/agent/interpreter/intro.html)吗？

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
