### ISSUE TITLE
Running research example may cause infinite loop 

### ISSUE THREAD

**Issue by tanishq-acu** [geekan/MetaGPT#1425]
**Bug description**
It is currently possible for metagpt.utils.text.generate_prompt_chunk() to create an infinite loop when using a model that is not added to the constants in metagpt.utils.token_counter.py. 

This is because it is possible for max_token to be negative. 

**Bug solved method**
Either increase the default return value for TOKEN_MAX.get() or raise an error if max_token is negative (ie less than TOKEN_MAX.get(model_name,2048) - reserved - 100. 

Ie. add 
`
if max_token < 0:
     raise RuntimeError("Insufficient context length")
`
to metagpt.utils.text.py (line 60).

**Environment information**
- LLM type and model name: Found using gpt-4o-mini.
- Python version: 3.10.11
- MetaGPT version or branch: 0.8.1

**Comment by iorisa** [comment]
You can use `pricing_plan` to fix this, like this:
```yaml
 llm:
  model: "gpt-4o"
  pricing_plan: "gpt-4"
```
This configuration means, use the `gpt-4o` model, but use the `gpt-4` token price to calculate the fee.
More detail: [config2.example.yaml](https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml)
