### ISSUE TITLE
Question,how to resume a project?

### ISSUE THREAD

**Issue by hgftrdw45ud67is8o89** [geekan/MetaGPT#1436]
I have no idea how to resume a project from error.or skip a part with error.

**Comment by hgftrdw45ud67is8o89** [comment]
yeah if has flag to enable.
- I tried  --recover-path and --project-path xxxx "please continue to make app ignoring design error." but it gets affected by the example "make 2048 game",lol

But from my experience pydantic error similar to https://github.com/geekan/MetaGPT/issues/1430 will directly closes the run and fail to make the docs or etc,so its impossible to resume. 
- I tried to make a try catch at action but don't know how to save the PRD/any docs from the project manager before it crashes.

**Comment by iorisa** [comment]
1. The incremental capabilities of metagpt are targeted at the requirements level， you can "write a snake game" first, and add "add moving enemy" as the incremental requirement.
2. If you want to fix a bug, it should be a code-level bug. 

Here are some examples of metagpt [usages](https://docs.deepwisdom.ai/main/en/guide/in_depth_guides/incremental_development.html):

**Comment by hgftrdw45ud67is8o89** [comment]
I tried the incremental way with>metagpt "write the code based on the design" --project-path "pathtoproject"
- I found out 2 problem.
- 1st,the incremental target will overwrite the old target requirement,"eg make a rust calendar cli" and save into requirement.txt Which will make the alice product manager think "make calender cli" is the *key* and use python eg my LLM now shows `  "File list": [
        "main.py",
        "backup_scheduler.py",
        "monitoring.py",
        "encryption.py",
        "settings.py",
        "notifications.py"
    ],`

- 2nd, my simple bug fix by adding Optional in design_plan_an.py doesn't work i still receive `Value error, Missing fields: {'Data structures and interfaces`

I am planning to make new issues/wait bug fix to step by step fix it. I can always volunteer to test the fix and see if it works.

**Comment by iorisa** [comment]
Sorry, I didn't understand what you wanted to do-_-||.

- `requirement.txt` is an input for metagpt, and the old and incremental user requirements are merged and saved in PRD, not in the `requirement.txt`.
- The software company of metagpt is a demo of a standard operating procedure (SOP) for software development. It cannot analyze user requirements, so you must clearly state your goal, not the problem or to-do list.
- The entire SOP of the software company includes designing and coding.
- SOP is a fixed flow. If you want to solve flexible and changing problems, it is recommended to take a look at [DI](https://docs.deepwisdom.ai/main/en/guide/use_cases/agent/interpreter/intro.html).
- I'll recheck #1430

**Comment by hgftrdw45ud67is8o89** [comment]
hmm~ i see.I understand a bit.

So,to do flexible task without messing using the sop flow,we can directly use DI?
So,in my mind the flow is like 
- SOP->llm Answer/Code?
- DI
- Multi agent
- etc?

**Comment by iorisa** [comment]
Sorry for not replying for so long.
If you choose the DI solution, all SOPs can serve as tools for DI. Choosing multiple DI agents is certainly because they need to perform memory isolation or require the use of different toolkits.

**Comment by iorisa** [comment]
I've consolidated all the incremental development-related issues into #1436 to make it easier to follow up. Any new issues will be discussed in this newly opened issue, and the old issue will be closed.
