### ISSUE TITLE
Issue loading deepwisdom.ai/

### ISSUE THREAD

**Issue by chasemcdo** [geekan/MetaGPT#1448]
**Bug description**

Website is down. Getting a 404 when trying to visit the root of the site

**Bug solved method**

**Environment information**

- LLM type and model name:
- System version:
- Python version:
- MetaGPT version or branch:

- packages version:
- installation method: 

**Screenshots or logs**

**Comment by iorisa** [comment]
[https://docs.deepwisdom.ai/](https://docs.deepwisdom.ai/), not `https://www.deepwisdom.ai/`

**Comment by chasemcdo** [comment]
> https://docs.deepwisdom.ai/, not `https://www.deepwisdom.ai/` You can visit it from [README](https://github.com/geekan/MetaGPT)

The unprefixed site is what is linked to from the GitHub repo and from various spots on the docs.* site.

wasn’t there a version of the site that was built using MetaGPT that was hosted there?

**Comment by better629** [comment]
online doc site:
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
