### ISSUE TITLE
如何绘制一个折线图或柱状图

### ISSUE THREAD

**Issue by ZTurboX** [geekan/MetaGPT#1449]
如何根据输入数据，绘制折线图或者柱状图

**Comment by iorisa** [comment]
让agent写代码，写完运行就能得到图。
<img width="379" alt="截屏2024-08-15 11 58 59" src="https://github.com/user-attachments/assets/b96875f2-164f-4a23-acf4-87e3a5598177">

**Comment by ZTurboX** [comment]
> 让agent写代码，写完运行就能得到图。 <img alt="截屏2024-08-15 11 58 59" width="379" src="https://private-user-images.githubusercontent.com/46912756/358118234-b96875f2-164f-4a23-acf4-87e3a5598177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTg3ODUsIm5iZiI6MTcyMzY5ODQ4NSwicGF0aCI6Ii80NjkxMjc1Ni8zNTgxMTgyMzQtYjk2ODc1ZjItMTY0Zi00YTIzLWFjZjQtODdlM2E1NTk4MTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA1MDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MTIyODUyM2RkYzAyOWE3YTlhZGZkYzk0MWZhNGU0NTNiMTkxMWZiZThjNDQyODA1NGRiOWRlY2M3NmUwNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F_JY8V_ESURR9E8KQ5kyOat51NhF1WypwN06LICoBZY">

这个agent要怎么实现

**Comment by iorisa** [comment]
就是[Data Interpreter](https://docs.deepwisdom.ai/main/en/DataInterpreter/)

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
