### ISSUE TITLE
Python3.12.5 removed distutils which blocked metagpt installation.

### ISSUE THREAD

**Issue by todjiang** [geekan/MetaGPT#1451]
**Bug description**
  ModuleNotFoundError: No module named 'distutils'

**Bug solved method**

**Environment information**

python 3.12.5

- LLM type and model name:
- System version:
- Python version:
- MetaGPT version or branch:

- packages version:
- installation method: 

**Screenshots or logs**

**Comment by iorisa** [comment]
There are many problems with the dependency packages in Python 12, so it is recommended to use Python 3.9 to 3.11.

**Comment by savelkouls** [comment]
Should remove compatibility with 3.12 from pip, as there is none.

**Comment by todjiang** [comment]
> Should remove compatibility with 3.12 from pip, as there is none.

Yes, I followed the guide and switched to 3.9 with conda env...
