### ISSUE TITLE
生成flask项目的问题

### ISSUE THREAD

**Issue by Admin6016** [geekan/MetaGPT#1456]
生成flask项目，运行测试代码会一直卡着，服务器也没关闭，导致后续流程无法继续

**Comment by iorisa** [comment]
“运行测试代码”是指QAEngineer运行它写的单测代码？

**Comment by Admin6016** [comment]
不是 是他的 ```app.py``` 代码，会一直卡在 ```running at locahost:5000``` 这里不动，猜测是代码没有运行完毕所以没有继续。但是这类代码本身就是阻塞性的。能否加个超时关闭机制之类的呢

**Comment by iorisa** [comment]
这个问题没涉及MetaGPT的bug，所以先关闭了。如果你还有任何问题，可以重新打开这个issue或新建Issue继续提问。

**Comment by iorisa** [comment]
这个问题没涉及MetaGPT的bug，所以先关闭了。如果你还有任何问题，可以重新打开这个issue或新建Issue继续提问。
