### ISSUE TITLE
Review about MetaGPT

### ISSUE THREAD

**Issue by Kashif-Raza6** [geekan/MetaGPT#146]
I have created 5 projects using metagpt and in first go `cli_snake_game` worked only and all the remaining get stuck. Let me share one example over here:
I have asked it to create a portfolio website for a developer and it created the all the project and when I tested the project I uses the old modules syntax that is creating a lot of trouble. One error I want to share here:
![image](https://github.com/geekan/MetaGPT/assets/96944736/abfde1f6-4ebc-416a-bc46-2c97ebed0be5)

for this code I have selected code_review to `True`. For a single project it cost you around 2-3$  and at the end when you see a lot of error its disgusting. There should be web search option to get the latest information and then it should create the project.

**Comment by voidking** [comment]
It seems like that some dependencies are missing.
Did you execute `pip install -r requirements.txt` first?

**Comment by Kashif-Raza6** [comment]
Yes I have installed the requirements. In some projects I have experience it writes version of some libraries that version can not be installed.

**Comment by voidking** [comment]
Not all the platforms and not all the python versions have specific libraries.
Maybe you can give promt like `write a cli snake game with python version 3.9.7` to specify a version.

**Comment by geekan** [comment]
Automatic debugging will be supported as soon as possible
