### ISSUE TITLE
software development SOPs in the paper

### ISSUE THREAD

**Issue by lxlhero** [geekan/MetaGPT#1466]
is there any code and reference for software development SOPs described in metagpt paper? I read the document and no example is suitable for software development SOPs, which includes  Product Manager, Architect, Project Manager, Engineer, and QA Engineer. Any one any idea? would it be available sooner

**Comment by iorisa** [comment]
Please follow these steps:
1. [install metagpt](https://docs.deepwisdom.ai/main/en/guide/get_started/installation.html)
2. [config LLM](https://docs.deepwisdom.ai/main/en/guide/get_started/configuration/llm_api_configuration.html)
3. [run software company](https://docs.deepwisdom.ai/main/en/guide/get_started/quickstart.html): `metagpt "write a cli blackjack game"`

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
