### ISSUE TITLE
how to retry an action in by-order mode

### ISSUE THREAD

**Issue by chenk-gd** [geekan/MetaGPT#1468]
There are multiple actions in a role and these actions are excuted in by-order mode. But sometimes the action may fail and  need to be retried. Check the result of previous action in the _think method to see if it is succeeded. If not, set the todo variable to the previous action and increase rc.max_react_loop by 1? Is there a better way to do this?

**Comment by garylin2099** [comment]
Hi, when designing by-order mode, we didn't expect it to handle situation where one of the actions may fail. However, your approach does seem plausible. An alternative might be moving the retry logic inside of the action. In this way, you don't need to modify Role's _think method.
