### ISSUE TITLE
使用DataInterpreter时，能否自己决定运行的环境

### ISSUE THREAD

**Issue by PengJinEd2020** [geekan/MetaGPT#1479]
自己使用conda控制环境，创建了一个叫“metagpt”的环境用来运行DataInterpreter脚本，它会创建并运行一个jupyternotebook。

以下是我的问题：
当前版本能否自己决定运行的这个jupyternotebook所依赖的环境，我尝试让大模型自己打印运行的环境，发现就是安装metagpt的这个环境

为什么想自己决定运行的环境：一些文件的读取依赖特定版本的joblib，metagpt和那个版本的joblib没法一起安装在一个环境，并且未来做复杂的数据分析工作，也需要安装特定版本的第三方包， metagpt对自身依赖的特别是numpy版本限制太严格，导致会跟我做数据分析的环境产生冲突

**Comment by seehi** [comment]
当前还不支持选择运行环境。可以试着改变kernel，FYI：https://janakiev.com/blog/jupyter-virtual-envs/

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
