### ISSUE TITLE
多个不同大模型的使用 

### ISSUE THREAD

**Issue by lonelysheeep** [geekan/MetaGPT#1480]
在使用数据分析功能的时候，如果想plan时使用一个智能体，编写代码时使用另一个智能体，除了修改config2.yaml的内容外，还需要怎么修改代码实现吗？具体要修改哪一个文件？

**Comment by seehi** [comment]
DI写代码用到[WriteAnalysisCode](https://github.com/geekan/MetaGPT/blob/main/metagpt/roles/di/data_interpreter.py#L55)
Action可以设置LLM（[example](https://github.com/geekan/MetaGPT/blob/main/examples/debate_simple.py)）

**Comment by lonelysheeep** [comment]
我看DI的action里有ReviewConst、ExecuteNbCode、CheckData,、WriteAnalysisCode，是不是只有CheckData,、WriteAnalysisCode用到了LLM，把这个设置了就可以了吧？还是只用设置WriteAnalysisCode的LLM？另外还有一个问题是DI最后输出的是可视化图，请问有没有办法既输出可视化图，又可以总结出结论（文本输出），还是说DI目前无法给出总结的结论输出。

**Comment by seehi** [comment]
需要定制的Action就要修改。
可以尝试修改prompt让DI输出你想要的内容。

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
