### ISSUE TITLE
关于Engineer和QaEngineer这两个角色的两个问题。

### ISSUE THREAD

**Issue by estuday** [geekan/MetaGPT#1481]
您好，
在Engineer的参数中，有一个n_borg，这个参数的说明是人数。但在具体的代码中，我没找到这个参数的具体作用，是指最多生成5个代码文件、设置任务运行的线程数？还是什么？
在运行最基本的 metagpt "生成一个2048小游戏" 这行命令的时候，我手动将代码中run_tests的默认值设置为了True，但最后tests文件夹中还是什么都没有，请问这可能是什么原因导致的？

**Comment by seehi** [comment]
[FAQ](https://github.com/geekan/MetaGPT/blob/main/docs/FAQ-EN.md)有关于n_borg的说明。
如果需要运行tests，需要增加[n_round](https://github.com/geekan/MetaGPT/blob/main/metagpt/software_company.py#L19)，可以多看下debug日志
