### ISSUE TITLE
希望可以增加Qwen2.5的模型支持

### ISSUE THREAD

**Issue by IcarusAegis** [geekan/MetaGPT#1483]
19日阿里发布了新的qwen2.5系列模型，希望增加对该系列模型的支持，该系列模型提升非常大。

**Comment by seehi** [comment]
当前已支持Qwen系列模型，可查看[文档](https://docs.deepwisdom.ai/main/en/guide/get_started/configuration/llm_api_configuration.html#aliyun-dashscope-api)。
希望的支持是增加计费吗，相关的计费，这篇[文章](https://qwenlm.github.io/zh/blog/qwen2.5/)有写。

**Comment by IcarusAegis** [comment]
> 当前已支持Qwen系列模型，可查看[文档](https://docs.deepwisdom.ai/main/en/guide/get_started/configuration/llm_api_configuration.html#aliyun-dashscope-api)。 希望的支持是增加计费吗，相关的计费，这篇[文章](https://qwenlm.github.io/zh/blog/qwen2.5/)有写。

感谢回答，我以为需要在token_counter中增加具体的适配才能使用，现在已经尝试了是可以使用的，非常感谢。
