### ISSUE TITLE
In the example file stream_output_via_api.py, all data from the setting context is None

### ISSUE THREAD

**Issue by pzw943969386** [geekan/MetaGPT#1484]
I reinstalled the metagpt package using git and modified the log function to obtain streaming output. 
However, I am currently unable to retrieve any data,
stream_pipe = stream_pipe_var.get(None)
always returns None, even though the context has been set. 
When I used the metagpt package installed in June, I was able to get streaming data.

**Comment by pzw943969386** [comment]
I am using the current version of metagpt and running the stream_output_via_api.py file. However, the streaming data obtained through the log settings is all None.

**Comment by seehi** [comment]
Using the main branch, the output of stream_output_via_api.py is normal.
```shell
 curl http://127.0.1.1:7860/v1/chat/completions -X POST -H "Content-Type: application/json" -d '{"model": "write_tutorial","stream": true,"messages": [{"role": "user","content": "Write a tutorial about MySQL"}]}'
```

**Comment by pzw943969386** [comment]
def stream_pipe_log(content):
    print(content, end="")
    stream_pipe = stream_pipe_var.get(None)
    if stream_pipe:
        print(f'{content=}')
        stream_pipe.set_message(content)

Hello, thank you for your response. If you log within this method, you'll notice that the content is empty, and I am unable to retrieve any streaming data. However, in the version I installed via Git in June, there was data output.
