### ISSUE TITLE
关于角色Role.py中STATE_TEMPLATE状态提示词模板的疑问？

### ISSUE THREAD

**Issue by chris666-sys** [geekan/MetaGPT#1489]
这里的`stage`是否和`state`是相同的意思？因为全篇关键词是`state`如果使用`state`描述是否会更好一些？谢谢各位！

![image](https://github.com/user-attachments/assets/a7f890ab-5c9e-4130-89ff-469dc2cf40b4)

![image](https://github.com/user-attachments/assets/9bc5fb3a-f6c7-423c-8d2b-9b11889f4ff9)

**Comment by seehi** [comment]
表达同一个意思，应该没什么影响，保持一致可能更好一些

**Comment by chris666-sys** [comment]
好的，谢谢！
