### ISSUE TITLE
关于ML-Benchmark的一些细节

### ISSUE THREAD

**Issue by acmisxuyutian** [geekan/MetaGPT#1493]
在进行Completion rate (CR)的计算时，似乎需要知道任务分解的参考答案。但是你们提供的数据集di_dataset/ml_benchmark，似乎并没有这方面的数据。我想知道你们是如何进行计算的，因为我想在你们的benchmark上评测一下。
![image](https://github.com/user-attachments/assets/3450741a-f4ea-4cb5-ac17-816e8e37f25c)
你们仅提供了User Requirement，我想知道User Requirement对应的T个任务是什么？
![image](https://github.com/user-attachments/assets/3eaa6057-79b0-48a8-b8d4-68aaf774fe79)

**Comment by stellaHSR** [comment]
Thank you for your question. For example, in 04_titanic, T includes data analysis, data preprocessing, feature engineering, modeling, and prediction. The agent is required to complete these critical steps during task decomposition and execution. Other tasks, such as data visualization and feature importance analysis, are considered non-essential. While we allow the agent to generate these, they will not be included in the T calculation.

**Comment by stellaHSR** [comment]
不是的，每个数据集的T steps都在User requirement里给出了，你可以直接从User requirement列里看到。我们原始描述也是：

> In the task requirments description, there were T steps.

为了方便社区测评，我们后续更新[README](https://github.com/geekan/MetaGPT/blob/main/examples/di/README.md)，具体补充每个数据集的T任务步骤。

**Comment by acmisxuyutian** [comment]
您现在能将这八个数据集的原始描述给我吗？因为，我现在下载的版本没有这部分描述。

**Comment by stellaHSR** [comment]
https://github.com/geekan/MetaGPT/blob/main/examples/di/README.md

**Comment by acmisxuyutian** [comment]
![image](https://github.com/user-attachments/assets/2d504e2f-c47a-4c49-aef2-40b3f91f4a08)
还有一点疑问是，您是如何判断AutoGen和OpenInterpreter有没有包含T个步骤中的某个步骤的呢？我能想象到的就是人工。对于TaskWeaver和您提出的Data Interpreter由于存在任务分解步骤，应该能够根据任务类型直接判断。

**Comment by acmisxuyutian** [comment]
我就是从此处下载的数据集。但是没有您提到的关于T个步骤的描述。[image]

**Comment by acmisxuyutian** [comment]
> 你可以使用：https://github.com/geekan/MetaGPT/blob/main/examples/di/README.md 或者在原始论文最后一页

抱歉，我误会了。我以为您之前的回复是说，User requirement直接包含了data analysis, data preprocessing, feature engineering, modeling, and prediction这样的描述。原来是
![image](https://github.com/user-attachments/assets/7023fc16-15ec-484d-ad73-68b55bbe6e8e)

**Comment by stellaHSR** [comment]
是的，部分baselines需要通过人工review生成的代码和运行日志，进行完成度的测评。显而易见，这个动作是比较容易标准化的，且不容易产生歧义。

> ![image](https://private-user-images.githubusercontent.com/113601978/374575203-2d504e2f-c47a-4c49-aef2-40b3f91f4a08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTQzNjIsIm5iZiI6MTcyODM5NDA2MiwicGF0aCI6Ii8xMTM2MDE5NzgvMzc0NTc1MjAzLTJkNTA0ZTJmLWM0N2EtNGM0OS1hZWYyLTQwYjNmOTFmNGEwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMzI3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTIxYTE2MDc0YjFmNWYwN2Q1ZTJlY2E3Zjk3M2E0YTdjNGQ0MWVjZDZhNjkxNjA5MDRjMWE0NWEyZDEzODc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tbWu41R2YCFtlHUqHT8_AzU4GSO4GlQs27OLXZXom3Q) 还有一点疑问是，您是如何判断AutoGen和OpenInterpreter有没有包含T个步骤中的某个步骤的呢？我能想象到的就是人工。对于TaskWeaver和您提出的Data Interpreter由于存在任务分解步骤，应该能够根据任务类型直接判断。

**Comment by acmisxuyutian** [comment]
> 是的，部分baselines需要通过人工review生成的代码和运行日志，进行完成度的测评。显而易见，这个动作是比较容易标准化的，且不容易产生歧义。
> 
> > ![image](https://private-user-images.githubusercontent.com/113601978/374575203-2d504e2f-c47a-4c49-aef2-40b3f91f4a08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTQzNjIsIm5iZiI6MTcyODM5NDA2MiwicGF0aCI6Ii8xMTM2MDE5NzgvMzc0NTc1MjAzLTJkNTA0ZTJmLWM0N2EtNGM0OS1hZWYyLTQwYjNmOTFmNGEwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMzI3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTIxYTE2MDc0YjFmNWYwN2Q1ZTJlY2E3Zjk3M2E0YTdjNGQ0MWVjZDZhNjkxNjA5MDRjMWE0NWEyZDEzODc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tbWu41R2YCFtlHUqHT8_AzU4GSO4GlQs27OLXZXom3Q) 还有一点疑问是，您是如何判断AutoGen和OpenInterpreter有没有包含T个步骤中的某个步骤的呢？我能想象到的就是人工。对于TaskWeaver和您提出的Data Interpreter由于存在任务分解步骤，应该能够根据任务类型直接判断。

好的，明白了，感谢解答！因为，我准备用您的benchmark评测，但是怕你们有自动化的方法，担心由于我人工造成什么偏见（但是，确实这些需求很难产生歧义，都有较高的辨识度）。
