### ISSUE TITLE
Installation issue on Wnd11 miniconda (Python 3.10)

### ISSUE THREAD

**Issue by HuangKaibo2017** [geekan/MetaGPT#150]
[requirements.txt](https://github.com/geekan/MetaGPT/files/12288657/requirements.txt)
Dear Geekan,
I fixed this installation by changed the requirements.txt. I like your idea, so send it back you. Hope that helps.

**Comment by martcpp** [comment]
Also need a windows setup file for command line

**Comment by better629** [comment]
Since no further responses are needed, we will close it. Please reopen it if necessary.
