### ISSUE TITLE
希望取得联系

### ISSUE THREAD

**Issue by JimmyMa99** [geekan/MetaGPT#151]
尊敬的[MetaGPT](https://github.com/geekan/MetaGPT) 应用开发者，我是 InternLM 社区开发者&志愿者尖米, 大佬开源的工作对我的启发很大，希望可以探讨使用 InternLM 实现[MetaGPT](https://github.com/geekan/MetaGPT) 的可能性和实现路径，我的微信是mzm312，希望可以取得联系进行更深度的交流；

**Comment by AIwem** [comment]
借个楼，中文readme页面微信账号异常了，没法添加，开个qq群也许更便捷？

**Comment by voidking** [comment]
> 借个楼，中文readme页面微信账号异常了，没法添加，开个qq群也许更便捷？

现在qq的用户没有那么多了，所以主要还是微信。新的入群方式已更新到中文README页面。

**Comment by voidking** [comment]
> 尊敬的[MetaGPT](https://github.com/geekan/MetaGPT) 应用开发者，我是 InternLM 社区开发者&志愿者尖米, 大佬开源的工作对我的启发很大，希望可以探讨使用 InternLM 实现[MetaGPT](https://github.com/geekan/MetaGPT) 的可能性和实现路径，我的微信是mzm312，希望可以取得联系进行更深度的交流；

已转运营同学，后续会同学加微信沟通哈~

**Comment by better629** [comment]
Since no further responses are needed, we will close it. Please reopen it if necessary.
