### ISSUE TITLE
Can we add a directory , that contains the models to task' s auto allocation function? 

### ISSUE THREAD

**Issue by CoderYiFei** [geekan/MetaGPT#1518]
For some relatively difficult tasks, more complex models such as o1-preview or Claude 3.5 Sonnet will be automatically called. 
For example, code review tasks or architecture tasks (unless the user specifies not to use them). 

If it is a relatively simple task, such as writing code for a text classification model or writing a function for a simple crawler, etc., a faster domestic model such as DeepSeek v2.5 can be automatically selected. 

The function is to automatically prioritize the allocation of large models according to the task difficulty (assuming that the user has several large models).

**Comment by geekan** [comment]
This feature is planned and expected to be available in the coming months, but is not available yet.
