### ISSUE TITLE
[Very important] can metagpt add a directory to collect useful news , to let it envole it automatically

### ISSUE THREAD

**Issue by CoderYiFei** [geekan/MetaGPT#1519]
For example, there are many AI news per week on internet.
metagpt should download some news , 
and analyze if the news or open source project or a new arxiv paper useful , 
for metagpt to evolve.
then metagpt will design a short term roadmap for itself, 
if Alexander Wu choose "accept", then metagpt will automatically develop a new branch that finished the roadmap.
if Alexander Wu choose "accept" again , metagpt will  automatically test itself , and merge it to main branch.

these are AI news examples :
[video] https://www.bilibili.com/video/BV1wk2UYaEWm?spm_id_from=333.788.player.switch&vd_source=97ab50b6d1c6cd0cf34537c8b367dece

[news] https://d.aigclink.ai/fe1ce99bc6a64266aa1ee5479c8e6da6?v=8f252a54730e49f4b8caf897b7ae49f6
....

**Comment by geekan** [comment]
This is a very good idea. But unfortunately, the current Code Agent is not yet able to complete such complex functions.
