### ISSUE TITLE
Fails to write basic rock paper scissors game

### ISSUE THREAD

**Issue by RasmusN** [geekan/MetaGPT#152]
I prompted it to _create a CLI based rock paper scissors game_, however, it failed to do so. I've heard good things about MetaGPT, is there something I'm doing wrong?

`python startup.py "create a CLI based rock paper scissors game"`

This is the code output:

```python
## main.py
from game import Game

def main():
    game = Game()
    game.display_instructions()

    while True:
        game.get_user_input()
        game.get_computer_choice()
        game.play_round()
        game.update_score()

        play_again = input("Do you want to play again? (yes/no): ").lower()
        if play_again != "yes":
            break

        # Clear console
        os.system('cls' if os.name == 'nt' else 'clear')

if __name__ == "__main__":
    main()
```
As you can see, it failes to import os. 

I'm using GPT4

**Comment by voidking** [comment]
We cannot guarantee that the output code will run directly. In most cases, it needs to be modified and debugged.
You can give more specific promt to get better results. For example, `create a CLI based rock paper scissors game based on python3.9.7 which can run on macos and no bugs`. 
There is some work in roadmap to improve the first-run success rate.

**Comment by better629** [comment]
Since no further responses are needed, we will close it. Please reopen it if necessary.
