### ISSUE TITLE
Can you add number of code lines that metagpt can maintain now , to readme

### ISSUE THREAD

**Issue by CoderYiFei** [geekan/MetaGPT#1520]
Could you add the medium lines that new version's MetaGPT can maintained ?
its better to show a change figure in readme.md
from 2023.07 to now , the number of code lines that metagpt can maintain from 2000 to ....(maybe 10k? 20k?)

**Comment by geekan** [comment]
Our metrics are not yet available to the public, and some metrics may be updated in version 1.0.
