### ISSUE TITLE
Dynamic sop(team)  ,  instead of a given sop(team) , should be designed 

### ISSUE THREAD

**Issue by CoderYiFei** [geekan/MetaGPT#1521]
sometimes , sop(team) is changing soon.
for example , if I want to design a text classification model
my sop(team) might only be Engineer + Project Manager + boss + QA 

Different user request , will lead to different sop(team) 
Different sop(team)  , will lead to different code repo dynamically

**Comment by geekan** [comment]
In a real-life scenario, you will have a team and distribute requirements freely, activating each member dynamically. In 1.0 we will see this feature.
