### ISSUE TITLE
[very important] streaming video/audio information to llm ,  should be supported.

### ISSUE THREAD

**Issue by CoderYiFei** [geekan/MetaGPT#1528]
The metagpt 's system needs to have the capability to support streaming video/audio input. 
For example, in a game, it should be able to stream the screen information to a large world model (LWM). The LWM would then need to control the keyboard and mouse to simulate the game's operation, identify issues during gameplay, modify the code, and then restart the game, repeating this process iteratively. 
This function should be add to game design task's sop(team)....

**Comment by geekan** [comment]
This work is being done and will be open sourced later
