### ISSUE TITLE
o1-mini 模型报错

### ISSUE THREAD

**Issue by MiangChen** [geekan/MetaGPT#1531]
**Bug description**

当model: "o1-mini"的时候, 会出现bug,
```
Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 86.782(s), this was the 1st time calling it. exp: Error code: 400 - {'error': {'message': "Unsupported value: 'messages[0].role' does not support 'system' with this model.     (request id: 20241022224433123206060zGFL5WKQ) (request id: 2024102222443296560188YMHkpVsa) (request id: 2024102222443292570479MKCUGfgl) (request id: 20241022224431807183774j4pHfuUY)", 'type': 'invalid_request_error', 'param': 'messages[0].role', 'code': 'unsupported_value'}}
```

**Bug solved method**

**Environment information**

- LLM type and model name: OpenAI  o1-mini
- System version: win11
- Python version: 3.10
- MetaGPT version or branch:  main

- packages version: 
- installation method:  pip install 

**Screenshots or logs**

![image](https://github.com/user-attachments/assets/7d6f335f-f330-4fcb-864b-b69977795765)

**Comment by better629** [comment]
refs to `https://docs.deepwisdom.ai/main/en/guide/get_started/configuration/llm_api_configuration.html#steps`

**Comment by geekan** [comment]
I feel it should be made into a default configuration that can be triggered by the model name.
