### ISSUE TITLE
Can metagpt support AI based search enginee Tavily

### ISSUE THREAD

**Issue by CoderYiFei** [geekan/MetaGPT#1534]
Maybe add TAVILY_API_KEY in [config2.example.yaml](https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml)
and its calling in necessary places

refering:
https://docs.tavily.com/docs/python-sdk/tavily-search/examples

**Comment by geekan** [comment]
Looks good. If you are interested, you can raise a PR.
