### ISSUE TITLE
Actual incremental work rather than based on an existing metagpt platform 

### ISSUE THREAD

**Issue by LimFang** [geekan/MetaGPT#1537]
Can MetaGPT be utilized for incremental work where the related files and documents are organized according to the company's rules and structures, rather than based on an existing platform developed by MetaGPT? Many files and pieces of work already exist in our database. 
How can we directly make incremental developments with such data that is not well organized the same as a meatgpt project?

**Comment by geekan** [comment]
Available in version 1.0.
