### ISSUE TITLE
Mac pip install error

### ISSUE THREAD

**Issue by syw2014** [geekan/MetaGPT#1538]
**Bug description**

when install metagpt with the command: "pip install metagpt", found the error bellow

Collecting fire==0.4.0 (from metagpt)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/11/07/a119a1aa04d37bc819940d95ed7e135a7dcca1c098123a3764a6dcace9e7/fire-0.4.0.tar.gz (87 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

**Bug solved method**

**Environment information**

- LLM type and model name:
- System version: macos 15.0.1
- Python version: 3.11.4
- MetaGPT version or branch:
metagpt-0.8.1-py3-none-any.whl

- packages version:
- installation method: 

**Screenshots or logs**

**Comment by voidking** [comment]
Try this:
```bash
python -m pip install pip

pip install setuptools
```

**Comment by corrosive4354** [comment]
First, make sure setuptools is installed:
Run the following command in the terminal to ensure that setuptools is installed and is the latest version:

pip install --upgrade setuptools
Second, reinstall metagpt:
After installing setuptools, try to install metagpt again:

pip install metagpt

If it still doesn't work, try to redeploy your development environment using the [servbay](servbay.com) tool.

**Comment by syw2014** [comment]
Fix bugs with the command bellow:
pip install metagpt --use-pep517

好好学习的郝 ***@***.***> 于2024年10月25日周五 10:02写道：
