### ISSUE TITLE
ollama llm vision api call error:     async for raw_chunk in stream_resp: TypeError: 'async for' requires an object with __aiter__ method, got bytes

### ISSUE THREAD

**Issue by ten2mushi** [geekan/MetaGPT#1539]
**Bug description**
when running any vision llm call (like example/llm_vision.py)
there seems to be an issue with async def _achat_completion_stream(self, messages: list[dict], timeout: int = USE_CONFIG_TIMEOUT) -> str: method

**Bug solved method**
No solve yet

**Environment information**
system metal, llm ollama, Python 3.10.13

- LLM type and model name: ollama, llava latest
- System version: 
- Python version: Python 3.10.13
- MetaGPT version or branch: main

- packages version: /
- installation method: from source

**Screenshots or logs**
.....
    do = self.iter(retry_state=retry_state)
    return fut.result()
    return self.__get_result()
    raise self._exception
    result = await fn(*args, **kwargs)
    return await self._achat_completion_stream(messages, timeout=self.get_timeout(timeout))
    async for raw_chunk in stream_resp: (HERE)
TypeError: 'async for' requires an object with __aiter__ method, got bytes

**Comment by EvensXia** [comment]
@ten2mushi
Thank you for your feedback!

To better understand and reproduce the issue, could you please provide more complete code? Specifically, a minimal reproducible code snippet or sample project would greatly help us in identifying the problem more efficiently. Thank you for your cooperation!

**Comment by EvensXia** [comment]
Hi @ten2mushi,

I've reproduced this error, and it appears to be a conflict between the Ollama streaming call stack and async handling. Setting `stream: false` in `config2.yaml::llm` should help prevent this error.

**Comment by ten2mushi** [comment]
Thanks for looking into it!

I've tested the change in config (stream set to false) in a fresh install of the repo.
This throws another error when running llm_vision.py:

    assert assist_msg.get("role", None) == "assistant"
AssertionError

**Comment by geekan** [comment]
@better629 @EvensXia Can you guys take a look?

**Comment by geekan** [comment]
I just merged the related PR, you can try again.
