### ISSUE TITLE
A verifier is needed ...... after AFlow Sela and FACT

### ISSUE THREAD

**Issue by CoderYiFei** [geekan/MetaGPT#1550]
AFlow is used for workflow construction;
Sela handles the tasks related to AutoML; 
FACT is responsible for multi-fact incremental retrieval. 

It seems that a verifier, 
that all of its indicators tops arxiv metrics just like AFlow Sela and FACT, is needed,

to verify whether the result of execution of code ,
meets the user's requirement documentation.

Then Programer will only need to ask questions....
FACT will help to search useful information,  
AFlow generate good workflow , based on PRD and FACT's searching,
Sela generate useful ml agents code , based on workflow, PRD and FACT's searching.
Finally "verifier" will run code and will review result , and will update PRD , to start next loop.

**Comment by geekan** [comment]
You have good intuition. I'm curious what your background is?
