### ISSUE TITLE
About testing and generated documents

### ISSUE THREAD

**Issue by lily-toru** [geekan/MetaGPT#1551]
1. Why are there no contents in tests and test_outputs in the generated code directory? How do you generate relevant documents and code? (生成的代码目录下，为什么tests和test_outputs里面没有内容？如果想要生成相关文档，该如何操作呢？)

2. The generated documents, such as those in the PRD directory, are in MD format. Is it possible to create documents in Word format? (已生成的文档，如prd目录下的文档，是md格式的。请问是否可以生成word格式的文档。)

**Comment by geekan** [comment]
Thank you for your question. Just ask in **English** is ok.

**Comment by iorisa** [comment]
1. When executing the `metagpt` command, add the `--run-tests` parameter, and also set a larger number for the `--n-round` parameter, such as 99, to enter the unit testing phase. [See more...](https://docs.deepwisdom.ai/main/en/guide/get_started/quickstart.html#usage )

2. Markdown documents are relatively easy to convert into PDF, Word, and other document formats, and Markdown is a browser-friendly document format, so we choose to generate Markdown documents. You can use `Pandoc` to convert Markdown to Word, but this functionality has not been integrated into MetaGPT."
For example:
```python
import pypandoc

output = pypandoc.convert_file('input.md', 'docx', outputfile='output.docx')
assert output == ""

```
or 
```bash
pandoc input.md -o output.docx
```

**Comment by lily-toru** [comment]
1. It is directly added after the metagpt command, just like this [metagpt "Write a xxx function" -- run tests]?
However, after running, there's still no content in the "tests" and "test_outputs" folders.
Can you provide an example of a command that includes setting the --n-round parameter?

**Comment by geekan** [comment]
I feel it would be more efficient to discuss this issue in version 1.0. The current design will actually be obsolete in version 1.0.

**Comment by lily-toru** [comment]
> I feel it would be more efficient to discuss this issue in version 1.0. The current design will actually be obsolete in version 1.0.

That is to say, in the current version, there will no further updates regarding the test section.
May I ask will the version 1.0 be released soon?

**Comment by geekan** [comment]
@lily-toru Yes. 1.0 will be available in the coming weeks.
