### ISSUE TITLE
[Two problems ] AttributeError: 'OpenAIResponse' object has no attribute 'decode'

### ISSUE THREAD

**Issue by MoonCapture** [geekan/MetaGPT#1565]
Bug description

Thanks to all the authors for their contributions.
I had two problems with it:
1. I downloaded the latest version of MetaGPT using git `pip install --upgrade git+https://github.com/geekan/MetaGPT.git` and got the following error when calling it. It is worth noting that the version before I used `pip install metagpt` did not have this error.

`from metagpt.llm import LLM
import asyncio
llm = LLM()
await llm.aask("hi")`
![image](https://github.com/user-attachments/assets/43763cbc-6747-4cb6-8c21-57b2dd5a76c8)

2.An error occurred when I was trying to reproduce SELA using deepseek-coder and could not recognize the model. This process uses the version of pip install metagpt. It is worth noting that the version before I used pip install metagpt did not have this error.

This process uses the version of pip install metagpt.
`2024-11-0116:53:40.467
INFO
metagpt.const:get metagpt package root:29 Package root set to d:\Python\06Ideas Test\02-AIGC
2024-11-0116:54:49.998
WARNING
tenacity.after:log_it:44 Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text'after 66.641(s),this was the 1st time calling it.
2024-11-0116:55:56.876
WARNING
tenacity.after:log_it:44 Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion text'after 133.531(s),this was the 2nd time calling it.
2024-11-0116:57:03.649
WARNING
tenacity.after:log_it:44-Finished call to 'metagpt.provider.openai_api.openAILLM.acompletion_text'after 200.297(s),this was the 3rd time calling it.
2024-11-0116:58:12.811
WARNING
tenacity.after:log_it:44
Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text'after 269.453(s),this was the 4th time calling it.`
git version：
![image](https://github.com/user-attachments/assets/7b731551-9365-4d34-827b-395824a79a22)

Environment information

LLM type and model name: ollama and model: gpt-4o-min, deepseek-coder, GLM-4-Flash
System version:
Python version: 3.9
MetaGPT version or branch: 0.8.1 and the ‘git’ version.

I'm sure it's not a network problem in FAQ5.8
Help is urgently needed, thank you very much!

**Comment by better629** [comment]
@MoonCapture Can you share your content inside config2.yaml to reproduce the problem?

**Comment by MoonCapture** [comment]
> Can you share your content inside config2.yaml to reproduce the problem?


`llm:


  api_type: 'zhipuai'
  api_key: 'XXX'
  base_url: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
  model: 'GLM-4-Flash'

  api_type: 'openai'
  model: 'deepseek-chat' # or deepseek-chat / deepseek-coder
  base_url: 'https://api.deepseek.com/v1'     
  api_key: 'sk-XXX' 



  api_type: 'moonshot'
  base_url: 'https://api.moonshot.cn/v1'
  api_key: 'sk-XXX'
  model: 'moonshot-v1-8k'
`

**Comment by MoonCapture** [comment]
`
llm:

api_type: 'zhipuai'
api_key: 'XXX'
base_url: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
model: 'GLM-4-Flash'

api_type: 'openai'
model: 'deepseek-chat' # or deepseek-chat / deepseek-coder
base_url: 'https://api.deepseek.com/v1'
api_key: 'sk-XXX'

api_type: 'moonshot'
base_url: 'https://api.moonshot.cn/v1'
api_key: 'sk-XXX'
model: 'moonshot-v1-8k'
`

**Comment by Shen-Yukang** [comment]
Hello, I also met the same kind error today. and I use metagpt ability by using "git clone" command to download the raw Repo

**Comment by iorisa** [comment]
Solving

**Comment by better629** [comment]
@MoonCapture I have tested `ask_and_print("what's your name?", llm, "I'm a helpful AI assistant.")` in `examples/hello_world.py` with main branch using `moonshot`. It works well. 
And the problem is a privious PR which influences the `GeneralAPIRequestor` that used in `zhipu` provider. @iorisa is working on it now.

**Comment by iorisa** [comment]
The problem has been solved, you can update the code from the main branch and try it again.
If you still have any issues, you can reopen this issue or create a new one to provide feedback on the problem.
