### ISSUE TITLE
Prompt word switching between Chinese and English?

### ISSUE THREAD

**Issue by RyanOvO** [geekan/MetaGPT#1576]
When writing code from the data_interpreter agent, it is very important to split the userrequirement into sub-tasks as follows:

![image](https://github.com/user-attachments/assets/83e92911-6cc8-484f-9528-e8a0b1690492)

But now the output prompt words are in English, and read the source code, basically are English prompt words, please ask, for the need for Chinese scenes, how to deal with?

![bda7f93612ed91991fff30b40ff5be4](https://github.com/user-attachments/assets/e6479742-29aa-42b4-aae1-b542c4ff81c2)

eg:
![1730869541315](https://github.com/user-attachments/assets/4674e00d-b406-4465-bc6f-e21eb45e7d38)
![image](https://github.com/user-attachments/assets/71122ef8-5f7a-4c80-9ba7-d11bcb2099ef)

How to solve it?

**Comment by geekan** [comment]
Hello, waiting for our 1.0 version, we have fixed this issue.

**Comment by RyanOvO** [comment]
> Hello, plz wait for our 1.0 version, we have fixed this issue.

As for prompt, I suggest that all modules should consider switching between English and Chinese for the prompt word, after all, there should be many such scenarios

**Comment by geekan** [comment]
This idea has crossed my mind numerous times throughout history. But I still haven't done this because, like the game text, it's a bit cumbersome to maintain. I'm not sure whether this idea is effective in the end, and since subtle differences in prompt words can lead to huge differences in effects, our approaches are quite different in the end.

**Comment by RyanOvO** [comment]
> This idea has crossed my mind numerous times throughout history. But I still haven't done this because, like the game text, it's a bit cumbersome to maintain. I'm not sure whether this idea is effective in the end, and since subtle differences in prompt words can lead to huge differences in effects, our approaches are quite different in the end.

So, will you handle it?When will it be resolved?
