### ISSUE TITLE
每次都会报这个pydantic异常

### ISSUE THREAD

**Issue by firewolf189** [geekan/MetaGPT#158]
每次都会报这个pydantic异常，这哪里参数有问题

By following this development plan, the pet insurance product will be well-positioned to meet the needs of pet owners and compete effectively in the market. The focus on user experience, coverage options, and customer support will help differentiate the product from competitors and drive customer satisfaction.
Traceback (most recent call last):
  File "/Users/chencheng/miniconda3/envs/chatglm/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/Users/chencheng/ai/cctest/metagpt/metagpt/metagpt/actions/action.py", line 62, in _aask_v1
    instruct_content = output_class(**parsed_data)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 6 validation errors for system_design
Implementation approach
  field required (type=value_error.missing)
Python package name
  field required (type=value_error.missing)
File list
  field required (type=value_error.missing)
Data structures and interface definitions
  field required (type=value_error.missing)
Program call flow
  field required (type=value_error.missing)
Anything UNCLEAR
  field required (type=value_error.missing)

**Comment by voidking** [comment]
参考下faq8 https://deepwisdom.feishu.cn/wiki/MsGnwQBjiif9c3koSJNcYaoSnu4

**Comment by geekan** [comment]
This problem actually comes from the poor Instruction Following of gpt-3.5-turbo. gpt-4 basically does not have this problem
