### ISSUE TITLE
About SELA & AFLOW examples

### ISSUE THREAD

**Issue by RyanOvO** [geekan/MetaGPT#1581]
About SELA & AFLOW , Can the official provide enough examples, as follows:
![image](https://github.com/user-attachments/assets/863e875b-422c-4b1d-b5c4-134e9f896847)

**Comment by garylin2099** [comment]
Hi, thanks for the suggestion! We are restructuring SELA to make it capable of accepting any text requirement just like DI, and will provide the example accordingly. In the meantime, can you try following the [README](https://github.com/geekan/MetaGPT/tree/main/metagpt/ext/sela) and see if it works for you?

**Comment by RyanOvO** [comment]
> Hi, thanks for the suggestion! We are restructuring SELA to make it capable of accepting any text requirement just like Data Interpreter, and will provide the example accordingly. In the meantime, can you try following the [README](https://github.com/geekan/MetaGPT/tree/main/metagpt/ext/sela) and see if it works for you?

ok. Looking forward to your updated version of SELA
