### ISSUE TITLE
Embedding model

### ISSUE THREAD

**Issue by RyanOvO** [geekan/MetaGPT#1582]
The example provided now is based on web api, but in many scenarios, it is also possible to directly specify the embedding model path to call, is it supported now?If so, what should be done in RAG?eg:
![image](https://github.com/user-attachments/assets/4701d657-b858-4a7d-961e-2105edd394e6)

**Comment by voidking** [comment]
@seehi @geekan

**Comment by 1840me** [comment]
Do you mean using a local path for the embedding? Such as
```python
from metagpt.rag.engines import SimpleEngine

from llama_index.embeddings.huggingface import HuggingFaceEmbedding


def get_local_embedding(model_name: str = "/path/to/embedding_model") -> HuggingFaceEmbedding:
    return HuggingFaceEmbedding(model_name=model_name)


SimpleEngine.from_docs(
    input_dir="/path/to/data",
    embed_model=get_local_embedding()
)

```

**Comment by RyanOvO** [comment]
> Do you mean using a local path for the embedding? Such as
> 
> ```python
> from metagpt.rag.engines import SimpleEngine
> 
> from llama_index.embeddings.huggingface import HuggingFaceEmbedding
> 
> 
> def get_local_embedding(model_name: str = "/path/to/embedding_model") -> HuggingFaceEmbedding:
>     return HuggingFaceEmbedding(model_name=model_name)
> 
> 
> SimpleEngine.from_docs(
>     input_dir="/path/to/data",
>     embed_model=get_local_embedding()
> )
> ```

bingo, But I didn't find this usage in RAG's documentation. i will try.
