### ISSUE TITLE
使用web_brower_engine_selenium出现的The process started from chrome location /opt/google/chrome/chrome is no longer running问题

### ISSUE THREAD

**Issue by QiMingChina** [geekan/MetaGPT#1584]
## 问题描述
使用web_brower_engine_selenium工具进行页面抓取
![image](https://github.com/user-attachments/assets/0d23dbc9-a6a7-4ab3-8d92-df18dcce8ae6)

## 版本信息
ChromeDriver 119.0.6045.105 (配置在/usr/bin/chromedriver)
Google Chrome 119.0.6045.199

**Comment by shenchucheng** [comment]
deepin 桌面版，ChromeDriver 119.0.6045.105，Google Chrome 119.0.6045.199，无法复现这个问题， 能提供更详细的复现信息吗，比如使用的Linux版本，机器的资源信息等。或者尝试用playwright呢？
