### ISSUE TITLE
使用web_browser_engine_selenium+chrome出现大量页面未关闭的情况

### ISSUE THREAD

**Issue by QiMingChina** [geekan/MetaGPT#1585]
# 异常描述
<img width="938" alt="a03496e9de82d63cc52544c27956596" src="https://github.com/user-attachments/assets/9cab7747-7488-4cd5-b3c7-3bfe00e8a3f7">

# 版本信息
Google Chrome 119.0.6045.199 
ChromeDriver 119.0.6045.105 
metagpt 0.8

**Comment by shenchucheng** [comment]
由https://github.com/geekan/MetaGPT/issues/1584导致
