### ISSUE TITLE
是否可以考虑支持Deepseek模型？

### ISSUE THREAD

**Issue by 3-body** [geekan/MetaGPT#1586]
是否可以考虑支持Deepseek模型？目前最有性价比的模型啊。

**Comment by voidking** [comment]
Deepseek后续会支持的。

**Comment by ZONGEZE** [comment]
好像已经是支持的？可以用OpenAI的接口
  api_type: "openai"  # or azure / ollama / groq etc.
  model: "deepseek-coder"  # or gpt-3.5-turbo
  base_url: "https://api.deepseek.com/v1"  # or forward url / other llm url
  api_key: "sk-"

**Comment by voidking** [comment]
deepseek接口兼容openai，确实是可以直接使用。
https://api-docs.deepseek.com/zh-cn/

**Comment by DanteAndroid** [comment]
请考虑添加DeepSeek配置到文档里：https://docs.deepwisdom.ai/main/zh/guide/get_started/configuration/llm_api_configuration.html#%E6%9C%88%E4%B9%8B%E6%9A%97%E9%9D%A2-moonshot-kimi-api
感谢！
