### ISSUE TITLE
Two questions about DI

### ISSUE THREAD

**Issue by kirainy** [geekan/MetaGPT#1591]
Hello, thank you for the excellent code and paper. Regarding DI, I have the following two questions: 1. Are the codes or logs generated after DI work placed in a certain folder like MetaGpt? 2. Is there any implementation code for the evaluation indicator CS mentioned in the paper?
Looking Forward to your answer!

**Comment by krish240574** [comment]
1. Look at save_history(role = <the DI variable>)  - from metagpt.utils.recovery_util import save_history, also in examples/di/data_visualization.py
2. Don't know, sorry.

**Comment by kirainy** [comment]
thanks for your reply！
