### ISSUE TITLE
如何使用自定义tool

### ISSUE THREAD

**Issue by ZTurboX** [geekan/MetaGPT#1594]
如何通过用户输入，调用自定义tool

**Comment by voidking** [comment]
目前不支持通过用户输入调用自定义tool。如果想自定义tool并调用，需要修改代码和配置文件。

**Comment by ZTurboX** [comment]
> 目前不支持通过用户输入调用自定义tool。如果想自定义tool并调用，需要修改代码和配置文件。

是类似这样修改吗？https://docs.deepwisdom.ai/main/zh/guide/tutorials/create_and_use_tools.html；看了DataInterpreter的源码，想通过llm plan自定义tool的执行，但不需要llm自动生成代码，是要修改WriteAnalysisCode吗

**Comment by voidking** [comment]
是的，除了那份文档，也可以参考下调研员的实现，也是自定义tool很好的例子 https://github.com/geekan/MetaGPT/blob/main/examples/research.py
