### ISSUE TITLE
RAG error

### ISSUE THREAD

**Issue by RyanOvO** [geekan/MetaGPT#1595]
When using RAG, the import package starts throwing errors.
metagpt: 0.8.1

![image](https://github.com/user-attachments/assets/d062a2c0-eba9-48e4-9698-51ad0ac70306)
![image](https://github.com/user-attachments/assets/d6321e1f-8294-4178-90cf-1075a68e9658)

**Comment by 1840me** [comment]
It looks like there's an error with Milvus. You could [try the main branch](https://docs.deepwisdom.ai/main/en/guide/get_started/installation.html#install-in-development-mode), as the dependency on Milvus has been [removed](https://github.com/geekan/MetaGPT/blob/main/setup.py#L46).

**Comment by RyanOvO** [comment]
> It looks like there's an error with Milvus. You could [try the main branch](https://docs.deepwisdom.ai/main/en/guide/get_started/installation.html#install-in-development-mode), as the dependency on Milvus has been [removed](https://github.com/geekan/MetaGPT/blob/main/setup.py#L46).


But we still need milvus.

![image](https://github.com/user-attachments/assets/93802d22-5df3-4d2a-aa7c-d15a08f784fe)
![image](https://github.com/user-attachments/assets/d0ec61c2-1377-4bb9-8596-85bf616fa884)
![image](https://github.com/user-attachments/assets/d164e243-cc2f-4a11-b742-f73a531a4b17)
