### ISSUE TITLE
summarize_code这个action有问题

### ISSUE THREAD

**Issue by lessoly** [geekan/MetaGPT#1596]
**Bug description**

我在运行generate_repo的代码时，发现运行到SummarizeCode时，被直接跳过进入下一轮的QaEngineer，因此我调试了代码，发现下图中的这行代码将加载进来的代码块(main.py,calculator.py)(我的demo是让metagpt写一个计算器)被从self.summarize_todos中pop出去了，因此在之后act时，没有办法从self.summarize_todos加载到任何东西，就会直接跳过
<img width="870" alt="1" src="https://github.com/user-attachments/assets/9d6c8dcb-d32a-4a5d-8a1c-6aa85c695f56">

我并不知道自己的判断是否正确，因为我仅仅运行了一个demo，对其他代码都不太了解，希望能得到解答
**Environment information**

- LLM type and model name:
- System version:
- Python version:
- MetaGPT version or branch:

- packages version:
- installation method: 

**Screenshots or logs**

**Comment by voidking** [comment]
不好意思，SummarizeCode 已经废弃了，在流程中不起作用，代码还没删，后续会删掉。
