### ISSUE TITLE
Use gpt-3.5-turbo-16k to write a cli-snake-game , but got 2 same file .

### ISSUE THREAD

**Issue by wkmcyz** [geekan/MetaGPT#160]
Model: gpt-3.5-turbo-16k.
Question: After execution, two identical files were generated.
Note: Below is the command-line output, from which you can see that the contents of Game.py and Snake.py are the same. It is not clear whether this is an issue with the gpt model or a problem within the code itself (such as some caching, etc.).

```
(metagpt_env_2) (base) wkm•~/code/metagpt(main⚡)» python startup.py "Write a cli snake game"                                                                    [20:27:33]
2023-08-08 20:36:52.676 | INFO     | metagpt.config:__init__:44 - Config loading done.
2023-08-08 20:36:54.406 | INFO     | metagpt.software_company:invest:39 - Investment: $3.0.
2023-08-08 20:36:54.406 | INFO     | metagpt.roles.role:_act:167 - Alice(Product Manager): ready to WritePRD
## Original Requirements:
The boss wants a command-line interface (CLI) snake game.

## Product Goals:
- Create a fun and engaging snake game that can be played in the command-line interface.
- Provide a challenging gameplay experience with increasing difficulty levels.
- Implement intuitive controls and smooth gameplay mechanics.

## User Stories:
- As a player, I want to be able to control the snake using arrow keys to navigate through the game.
- As a player, I want to see my current score and high score displayed on the screen.
- As a player, I want the game to become progressively more difficult as I score higher.
- As a player, I want to be able to pause and resume the game at any time.
- As a player, I want to be able to restart the game after losing.

## Competitive Analysis:
- Python Snake Game: A simple snake game implemented in Python with basic gameplay mechanics.
- CLI Snake: A command-line interface snake game with customizable difficulty levels.
- Snake CLI: A snake game with a minimalistic design and smooth controls.
- Terminal Snake: A snake game with retro graphics and challenging gameplay.
- Snake Game: A classic snake game with intuitive controls and multiple game modes.
- Snake CLI Pro: An advanced command-line interface snake game with power-ups and special abilities.
- Snake Master: A highly addictive snake game with stunning graphics and immersive gameplay.

## Competitive Quadrant Chart:
```mermaid
quadrantChart
    title Reach and engagement of snake games
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 Python Snake Game: [0.3, 0.6]
    quadrant-2 CLI Snake: [0.45, 0.23]
    quadrant-3 Snake CLI: [0.57, 0.69]
    quadrant-4 Terminal Snake: [0.78, 0.34]
    quadrant-1 Snake Game: [0.4, 0.34]
    quadrant-2 Snake CLI Pro: [0.35, 0.78]
    quadrant-3 Snake Master: [0.6, 0.7]
    "Our Target Product": [0.5, 0.6]
```

## Requirement Analysis:
The product should be a command-line interface (CLI) snake game with intuitive controls, increasing difficulty levels, and the ability to pause, resume, and restart the game.

## Requirement Pool:
```python
[
    ("Implement arrow key controls for the snake movement", "P0"),
    ("Display current score and high score on the screen", "P1"),
    ("Increase the speed of the snake as the score increases", "P1"),
    ("Implement pause and resume functionality", "P2"),
    ("Allow the player to restart the game after losing", "P2")
]
```

## UI Design draft:
The game will have the following elements and functions:
- Snake: A series of characters representing the snake's body, moving on the screen.
- Food: A character representing the food that the snake needs to eat to grow.
- Score: Displayed on the screen, showing the current score and high score.
- Controls: Arrow keys to navigate the snake.
- Pause/Resume: Pressing a specific key to pause or resume the game.
- Restart: Pressing a specific key to restart the game after losing.

The style of the game will be minimalistic, with clear and easy-to-read characters. The layout will be centered on the screen, with the snake and food displayed in a grid-like format.

## Anything UNCLEAR:
There are no unclear points.
2023-08-08 20:37:19.073 | INFO     | metagpt.roles.role:_act:167 - Bob(Architect): ready to WriteDesign
## Implementation approach:
For the implementation of the CLI snake game, we will use the following open-source tools:

1. `curses` library: This library provides a terminal-independent way to create text-based user interfaces. It allows us to control the terminal screen, handle keyboard input, and create interactive CLI applications.

2. `random` module: This module will be used to generate random positions for the food in the game.

3. `time` module: This module will be used to control the speed of the game and introduce delays between each frame.

4. `sys` module: This module will be used to handle system-level operations, such as exiting the game.

## Python package name:
```python
"cli_snake_game"
```

## File list:
```python
[
    "main.py",
]
```

## Data structures and interface definitions:
```mermaid
classDiagram
    class Game {
        -int score
        -int high_score
        -int speed
        -bool game_over
        -bool paused
        -Snake snake
        -Food food
        +start_game(): None
        +update(): None
        +handle_input(): None
        +draw(): None
        +game_over_screen(): None
        +pause(): None
        +resume(): None
        +restart(): None
    }

    class Snake {
        -List[Tuple[int, int]] body
        -Tuple[int, int] head
        -Tuple[int, int] direction
        +move(): None
        +change_direction(): None
        +grow(): None
        +check_collision(): bool
    }

    class Food {
        -Tuple[int, int] position
        +generate_position(): None
    }
    
    class Screen {
        -int width
        -int height
        -curses.window window
        +init(): None
        +draw_border(): None
        +draw_snake(): None
        +draw_food(): None
        +draw_score(): None
        +refresh(): None
        +close(): None
    }
    
    class InputHandler {
        -curses.window window
        +get_input(): int
    }
    
    Game "1" -- "1" Snake: has
    Game "1" -- "1" Food: has
    Game "1" -- "1" Screen: has
    Game "1" -- "1" InputHandler: has
```

## Program call flow:
```mermaid
sequenceDiagram
    participant M as Main
    participant G as Game
    participant S as Snake
    participant F as Food
    participant SC as Screen
    participant IH as InputHandler

    M->>G: G.start_game()
    G->>SC: SC.init()
    G->>F: F.generate_position()
    G->>SC: SC.draw_border()
    G->>SC: SC.draw_snake()
    G->>SC: SC.draw_food()
    G->>SC: SC.draw_score()
    G->>SC: SC.refresh()
    loop
        G->>IH: IH.get_input()
        G->>G: G.handle_input()
        G->>S: S.move()
        G->>S: S.change_direction()
        G->>S: S.grow()
        G->>S: S.check_collision()
        G->>F: F.generate_position()
        G->>SC: SC.draw_snake()
        G->>SC: SC.draw_food()
        G->>SC: SC.draw_score()
        G->>SC: SC.refresh()
        G->>G: G.update()
    end
    G->>G: G.game_over_screen()
    G->>G: G.pause()
    G->>G: G.resume()
    G->>G: G.restart()
    G->>SC: SC.close()
```

## Anything UNCLEAR:
The requirements and implementation approach are clear.
2023-08-08 20:37:47.605 | INFO     | metagpt.utils.mermaid:mermaid_to_file:38 - Generating /Users/wkm/code/metagpt/workspace/cli_snake_game/resources/competitive_analysis.pdf..
file:///Users/wkm/.nvm/versions/node/v13.14.0/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:260
      const svg = container.getElementsByTagName?.('svg')?.[0]
                                                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
2023-08-08 20:37:47.865 | INFO     | metagpt.utils.mermaid:mermaid_to_file:38 - Generating /Users/wkm/code/metagpt/workspace/cli_snake_game/resources/competitive_analysis.svg..
file:///Users/wkm/.nvm/versions/node/v13.14.0/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:260
      const svg = container.getElementsByTagName?.('svg')?.[0]
                                                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
2023-08-08 20:37:47.938 | INFO     | metagpt.utils.mermaid:mermaid_to_file:38 - Generating /Users/wkm/code/metagpt/workspace/cli_snake_game/resources/competitive_analysis.png..
file:///Users/wkm/.nvm/versions/node/v13.14.0/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:260
      const svg = container.getElementsByTagName?.('svg')?.[0]
                                                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
2023-08-08 20:37:48.011 | INFO     | metagpt.actions.design_api:_save_prd:110 - Saving PRD to /Users/wkm/code/metagpt/workspace/cli_snake_game/docs/prd.md
2023-08-08 20:37:48.015 | INFO     | metagpt.utils.mermaid:mermaid_to_file:38 - Generating /Users/wkm/code/metagpt/workspace/cli_snake_game/resources/data_api_design.pdf..
file:///Users/wkm/.nvm/versions/node/v13.14.0/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:260
      const svg = container.getElementsByTagName?.('svg')?.[0]
                                                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
2023-08-08 20:37:48.124 | INFO     | metagpt.utils.mermaid:mermaid_to_file:38 - Generating /Users/wkm/code/metagpt/workspace/cli_snake_game/resources/data_api_design.svg..
file:///Users/wkm/.nvm/versions/node/v13.14.0/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:260
      const svg = container.getElementsByTagName?.('svg')?.[0]
                                                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
2023-08-08 20:37:48.217 | INFO     | metagpt.utils.mermaid:mermaid_to_file:38 - Generating /Users/wkm/code/metagpt/workspace/cli_snake_game/resources/data_api_design.png..
file:///Users/wkm/.nvm/versions/node/v13.14.0/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:260
      const svg = container.getElementsByTagName?.('svg')?.[0]
                                                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
2023-08-08 20:37:48.293 | INFO     | metagpt.utils.mermaid:mermaid_to_file:38 - Generating /Users/wkm/code/metagpt/workspace/cli_snake_game/resources/seq_flow.pdf..
file:///Users/wkm/.nvm/versions/node/v13.14.0/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:260
      const svg = container.getElementsByTagName?.('svg')?.[0]
                                                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
2023-08-08 20:37:48.363 | INFO     | metagpt.utils.mermaid:mermaid_to_file:38 - Generating /Users/wkm/code/metagpt/workspace/cli_snake_game/resources/seq_flow.svg..
file:///Users/wkm/.nvm/versions/node/v13.14.0/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:260
      const svg = container.getElementsByTagName?.('svg')?.[0]
                                                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
2023-08-08 20:37:48.443 | INFO     | metagpt.utils.mermaid:mermaid_to_file:38 - Generating /Users/wkm/code/metagpt/workspace/cli_snake_game/resources/seq_flow.png..
file:///Users/wkm/.nvm/versions/node/v13.14.0/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:260
      const svg = container.getElementsByTagName?.('svg')?.[0]
                                                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
2023-08-08 20:37:48.528 | INFO     | metagpt.actions.design_api:_save_system_design:119 - Saving System Designs to /Users/wkm/code/metagpt/workspace/cli_snake_game/docs/system_design.md
2023-08-08 20:37:48.531 | INFO     | metagpt.roles.role:_act:167 - Eve(Project Manager): ready to WriteTasks
## Required Python third-party packages:

```python
"""
curses
"""
```

## Required Other language third-party packages:

```python
"""
No other language third-party packages required.
"""
```

## Full API spec:

```python
"""
openapi: 3.0.0
info:
  title: Snake Game API
  description: API for controlling the Snake Game
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /game/start:
    post:
      summary: Start a new game
      responses:
        '200':
          description: Game started successfully
  /game/move:
    post:
      summary: Move the snake in a specific direction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                direction:
                  type: string
                  enum:
                    - up
                    - down
                    - left
                    - right
              required:
                - direction
      responses:
        '200':
          description: Snake moved successfully
  /game/pause:
    post:
      summary: Pause the game
      responses:
        '200':
          description: Game paused successfully
  /game/resume:
    post:
      summary: Resume the game
      responses:
        '200':
          description: Game resumed successfully
  /game/restart:
    post:
      summary: Restart the game
      responses:
        '200':
          description: Game restarted successfully
"""
```

## Logic Analysis:

```python
[
    ("main.py", "Main"),
    ("game.py", "Game"),
    ("snake.py", "Snake"),
    ("food.py", "Food"),
    ("screen.py", "Screen"),
    ("input_handler.py", "InputHandler")
]
```

## Task list:

```python
[
    "main.py",
    "game.py",
    "snake.py",
    "food.py",
    "screen.py",
    "input_handler.py"
]
```

## Shared Knowledge:

```python
"""
The 'game.py' file contains the main logic for the Snake Game.
"""
```

## Anything UNCLEAR:

No unclear requirements or implementation approach mentioned.
2023-08-08 20:38:03.166 | INFO     | metagpt.actions.write_code:run:77 - Writing main.py..
## Code: main.py

```python
import curses
import time
import sys
from game import Game
from screen import Screen
from input_handler import InputHandler

def main(stdscr):
    screen = Screen(stdscr)
    input_handler = InputHandler(stdscr)
    game = Game(screen, input_handler)

    game.start_game()

    while True:
        game.handle_input()
        game.update()
        game.draw()
        time.sleep(0.1)

        if game.game_over:
            game.game_over_screen()
            game.pause()
            game.restart()

if __name__ == "__main__":
    curses.wrapper(main)
```

2023-08-08 20:38:08.168 | INFO     | metagpt.actions.write_code:run:77 - Writing game.py..
## Code: game.py

```python
import curses
import time
import sys
from screen import Screen
from input_handler import InputHandler
from snake import Snake
from food import Food


class Game:
    def __init__(self, screen: Screen, input_handler: InputHandler):
        self.screen = screen
        self.input_handler = input_handler
        self.snake = Snake()
        self.food = Food()
        self.score = 0
        self.high_score = 0
        self.speed = 1
        self.game_over = False
        self.paused = False

    def start_game(self):
        self.screen.init()
        self.food.generate_position()
        self.screen.draw_border()
        self.screen.draw_snake(self.snake.body)
        self.screen.draw_food(self.food.position)
        self.screen.draw_score(self.score, self.high_score)
        self.screen.refresh()

    def handle_input(self):
        key = self.input_handler.get_input()

        if key == curses.KEY_UP:
            self.snake.change_direction("up")
        elif key == curses.KEY_DOWN:
            self.snake.change_direction("down")
        elif key == curses.KEY_LEFT:
            self.snake.change_direction("left")
        elif key == curses.KEY_RIGHT:
            self.snake.change_direction("right")
        elif key == ord("p"):
            self.pause()
        elif key == ord("r"):
            self.restart()

    def update(self):
        if not self.paused:
            self.snake.move()

            if self.snake.check_collision():
                self.game_over = True
                return

            if self.snake.head == self.food.position:
                self.snake.grow()
                self.score += 1
                self.speed += 0.1
                self.food.generate_position()

            self.screen.draw_snake(self.snake.body)
            self.screen.draw_food(self.food.position)
            self.screen.draw_score(self.score, self.high_score)
            self.screen.refresh()

    def draw(self):
        if self.game_over:
            self.game_over_screen()
        elif self.paused:
            self.screen.draw_pause()
            self.screen.refresh()

    def game_over_screen(self):
        self.screen.draw_game_over()
        self.screen.refresh()

    def pause(self):
        self.paused = True

    def resume(self):
        self.paused = False

    def restart(self):
        self.score = 0
        self.speed = 1
        self.snake.reset()
        self.food.generate_position()
        self.game_over = False
        self.paused = False
        self.screen.clear()
        self.screen.draw_border()
        self.screen.draw_snake(self.snake.body)
        self.screen.draw_food(self.food.position)
        self.screen.draw_score(self.score, self.high_score)
        self.screen.refresh()


def main(stdscr):
    screen = Screen(stdscr)
    input_handler = InputHandler(stdscr)
    game = Game(screen, input_handler)

    game.start_game()

    while True:
        game.handle_input()
        game.update()
        game.draw()
        time.sleep(0.1)

        if game.game_over:
            game.game_over_screen()
            game.pause()
            game.restart()


if __name__ == "__main__":
    curses.wrapper(main)
```

2023-08-08 20:38:28.540 | INFO     | metagpt.actions.write_code:run:77 - Writing snake.py..
## Code: snake.py

```python
import curses
import time
import sys
from screen import Screen
from input_handler import InputHandler
from snake import Snake
from food import Food


class Game:
    def __init__(self, screen: Screen, input_handler: InputHandler):
        self.screen = screen
        self.input_handler = input_handler
        self.snake = Snake()
        self.food = Food()
        self.score = 0
        self.high_score = 0
        self.speed = 1
        self.game_over = False
        self.paused = False

    def start_game(self):
        self.screen.init()
        self.food.generate_position()
        self.screen.draw_border()
        self.screen.draw_snake(self.snake.body)
        self.screen.draw_food(self.food.position)
        self.screen.draw_score(self.score, self.high_score)
        self.screen.refresh()

    def handle_input(self):
        key = self.input_handler.get_input()

        if key == curses.KEY_UP:
            self.snake.change_direction("up")
        elif key == curses.KEY_DOWN:
            self.snake.change_direction("down")
        elif key == curses.KEY_LEFT:
            self.snake.change_direction("left")
        elif key == curses.KEY_RIGHT:
            self.snake.change_direction("right")
        elif key == ord("p"):
            self.pause()
        elif key == ord("r"):
            self.restart()

    def update(self):
        if not self.paused:
            self.snake.move()

            if self.snake.check_collision():
                self.game_over = True
                return

            if self.snake.head == self.food.position:
                self.snake.grow()
                self.score += 1
                self.speed += 0.1
                self.food.generate_position()

            self.screen.draw_snake(self.snake.body)
            self.screen.draw_food(self.food.position)
            self.screen.draw_score(self.score, self.high_score)
            self.screen.refresh()

    def draw(self):
        if self.game_over:
            self.game_over_screen()
        elif self.paused:
            self.screen.draw_pause()
            self.screen.refresh()

    def game_over_screen(self):
        self.screen.draw_game_over()
        self.screen.refresh()

    def pause(self):
        self.paused = True

    def resume(self):
        self.paused = False

    def restart(self):
        self.score = 0
        self.speed = 1
        self.snake.reset()
        self.food.generate_position()
        self.game_over = False
        self.paused = False
        self.screen.clear()
        self.screen.draw_border()
        self.screen.draw_snake(self.snake.body)
        self.screen.draw_food(self.food.position)
        self.screen.draw_score(self.score, self.high_score)
        self.screen.refresh()


def main(stdscr):
    screen = Screen(stdscr)
    input_handler = InputHandler(stdscr)
    game = Game(screen, input_handler)

    game.start_game()

    while True:
        game.handle_input()
        game.update()
        game.draw()
        time.sleep(0.1)

        if game.game_over:
            game.game_over_screen()
            game.pause()
            game.restart()


if __name__ == "__main__":
    curses.wrapper(main)
```
2023-08-08 20:38:50.483 | INFO     | metagpt.actions.write_code:run:77 - Writing food.py..
## Code: food.py

```python
class Food:
    def __init__(self):
        self.position = (0, 0)

    def generate_position(self):
        # Generate random position for the food
        # Set self.position to the generated position
        pass
```

2023-08-08 20:38:53.777 | INFO     | metagpt.actions.write_code:run:77 - Writing screen.py..
## Code: screen.py

```python
import curses

class Screen:
    def __init__(self, stdscr):
        self.stdscr = stdscr
        self.width = 0
        self.height = 0
        self.window = None

    def init(self):
        self.stdscr.clear()
        self.height, self.width = self.stdscr.getmaxyx()
        self.window = curses.newwin(self.height, self.width, 0, 0)
        self.window.timeout(100)

    def draw_border(self):
        self.window.border()

    def draw_snake(self, body):
        for x, y in body:
            self.window.addch(y, x, curses.ACS_BLOCK)

    def draw_food(self, position):
        x, y = position
        self.window.addch(y, x, curses.ACS_DIAMOND)

    def draw_score(self, score, high_score):
        score_text = f"Score: {score} High Score: {high_score}"
        self.window.addstr(0, self.width - len(score_text) - 1, score_text)

    def draw_pause(self):
        pause_text = "PAUSED"
        self.window.addstr(self.height // 2, (self.width - len(pause_text)) // 2, pause_text)

    def refresh(self):
        self.window.refresh()

    def clear(self):
        self.window.clear()

    def close(self):
        curses.endwin()
```

Explanation:
- The `Screen` class is responsible for managing the terminal screen and drawing the game elements.
- The `__init__` method initializes the screen attributes and sets the default values.
- The `init` method clears the screen, gets the screen dimensions, and creates a new window using the curses library.
- The `draw_border` method draws a border around the game area.
- The `draw_snake` method takes a list of coordinates representing the snake's body and draws each segment on the screen.
- The `draw_food` method takes the position of the food and draws it on the screen.
- The `draw_score` method takes the current score and high score and displays them on the screen.
- The `draw_pause` method displays a "PAUSED" message in the center of the screen.
- The `refresh` method updates the screen with the latest changes.
- The `clear` method clears the screen.
- The `close` method ends the curses library and restores the terminal to its original state.
2023-08-08 20:39:09.163 | INFO     | metagpt.actions.write_code:run:77 - Writing input_handler.py..
## Code: input_handler.py
```python
import curses

class InputHandler:
    def __init__(self, stdscr):
        self.stdscr = stdscr

    def get_input(self):
        key = self.stdscr.getch()
        return key
```
-----
The code above implements the `InputHandler` class, which is responsible for handling user input in the snake game. It uses the `curses` library to read keyboard input from the terminal.

The `InputHandler` class has a constructor that takes the `stdscr` parameter, which is the standard screen object provided by the `curses` library.

The `get_input` method reads a single character of input from the user and returns it. It uses the `getch` method of the `stdscr` object to read the input.

The code is PEP8 compliant, modular, easy to read and maintain.
2023-08-08 20:39:15.569 | INFO     | metagpt.roles.engineer:_act_sp:148 - Done /Users/wkm/code/metagpt/workspace/cli_snake_game/cli_snake_game generating.
(metagpt_env_2) (base) wkm•~/code/metagpt(main⚡)»                                                                                                               [20:41:34]

```

**Comment by voidking** [comment]
We cannot guarantee that the generated code is completely correct. In most cases, it needs to be modified and debugged.
There is some work in roadmap to reduce the possibility of errors.

**Comment by geekan** [comment]
This problem actually comes from the poor Instruction Following of gpt-3.5-turbo. gpt-4 basically does not have this problem
