### ISSUE TITLE
Cannot run/no response when running

### ISSUE THREAD

**Issue by zerd1y** [geekan/MetaGPT#1605]
**I pasted the full script from Multiagent-Debate on pycharm，and tried to run the script code on cmd/anaconda prompt, but no response**

**Screenshots**
<img width="861" alt="image" src="https://github.com/user-attachments/assets/ea803e24-4b92-4f58-a6f7-f30a060c2618">
![image](https://github.com/user-attachments/assets/27a43a8c-0443-41cf-9b4a-7f869c9089ce)
![image](https://github.com/user-attachments/assets/e5382d26-14d5-4ce9-9467-a4e6ecb8eb39)
![image](https://github.com/user-attachments/assets/2ed1af5d-fdc1-4f41-a58b-6f428d50c779)

**Comment by voidking** [comment]
First you need to install metagpt correctly. Please refer to: https://docs.deepwisdom.ai/main/en/guide/get_started/installation.html#install-in-development-mode

**Comment by zerd1y** [comment]
> First you need to install metagpt correctly. Please refer to: https://docs.deepwisdom.ai/main/en/guide/get_started/installation.html#install-in-development-mode

Thank you very much for your answer. I guess I had some minor problems when I first installed it. I will troubleshoot the problem and continue to try your project.

**Comment by zerd1y** [comment]
> > First you need to install metagpt correctly. Please refer to: https://docs.deepwisdom.ai/main/en/guide/get_started/installation.html#install-in-development-mode
> 
> Thank you very much for your answer. I guess I had some minor problems when I first installed it. I will troubleshoot the problem and continue to try your project.

I have successfully run the project code, thank you again for your reply
