### ISSUE TITLE
如何实现Action结果校验

### ISSUE THREAD

**Issue by QiMingChina** [geekan/MetaGPT#1610]
如何实现Action结果校验。
场景：action1的结果是一个理想应该是一个json，但是llm回复不是一个标准json，导致action2解析出现问题导致报错。
如果实现一个循环，定义一个check函数检测Action的结果（按照某自定义规则），定义最大重试次数，如果llm返回正确则进入下一个action2，如果返回错误，check函数会返回reson（错误原因），将错误原因加入到对话中，再给llm重新生成。

**Comment by voidking** [comment]
这个功能已经有了，在配置文件中开启 repair_llm_output ，具体配置为：
```yaml
repair_llm_output: true
```
代码实现：https://github.com/geekan/MetaGPT/blob/main/metagpt/utils/repair_llm_raw_output.py
