### ISSUE TITLE
VS在测试use_off_the_shelf_agent程序时报错，跟write

### ISSUE THREAD

**Issue by deger2012** [geekan/MetaGPT#1623]
**Bug description**
在VS在2022上测试use_off_the_shelf_agent程序时报错,报错如图

**Bug solved method**

**Environment information**

- LLM type and model name:
- System version:windows 11
- Python version:3.11.7
- MetaGPT version or branch: master

- packages version:
- installation method: 

**Screenshots or logs**
![111](https://github.com/user-attachments/assets/049d83a5-9944-4d91-9ec4-ae2aa6ef9fd3)

**Comment by iorisa** [comment]
Fixed.
Pull the code again and try it please.
If you still have questions, you can reopen this issue or start a new one.

**Comment by deger2012** [comment]
> 固定。请再次拉取代码并尝试一下。如果您仍有疑问，可以重新打开此问题或开始新的问题。
可以了 谢谢
