### ISSUE TITLE
`AttributeError: 'NoneType' object has no attribute 'api_type'` !

### ISSUE THREAD

**Issue by Hongcheng-Gao** [geekan/MetaGPT#1626]
When i running `python -m examples.aflow.optimize --dataset MATH`, it appear `AttributeError: 'NoneType' object has no attribute 'api_type'` ![image](https://github.com/user-attachments/assets/f90efa34-810f-4ea2-93f0-b1900a480dc9)

**Comment by shenchucheng** [comment]
The models have not been configured. Please follow the instructions at [https://github.com/geekan/MetaGPT/tree/main/examples/aflow#quick-start](https://github.com/geekan/MetaGPT/tree/main/examples/aflow#quick-start) to complete the configuration and then try again.

**Comment by shenchucheng** [comment]
The merged PR [https://github.com/geekan/MetaGPT/pull/1632](https://github.com/geekan/MetaGPT/pull/1632) raises exceptions more elegantly and introduces the `--opt_model_name` and `--exec_model_name` options to allow the passing of custom models.
