### ISSUE TITLE
ModuleNotFoundError: No module named 'fire'

### ISSUE THREAD

**Issue by Teddyduann** [geekan/MetaGPT#163]
Traceback (most recent call last):
  File "/Users/shuyuanduann/metagpt/startup.py", line 5, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'

**Comment by fbaptista** [comment]
did you run pip install requirements before?

**Comment by MachineSaver** [comment]
I just wrote this up incase it'll help you get started on your project.

https://github.com/geekan/MetaGPT/issues/166

**Comment by coolxeo** [comment]
I manage to fix it:
1. First I did `pip install -r requirements.txt`
2. It was still failing when running with an error about bs4 (BeautifulSoup). I fixed with `pip install BeautifulSoup4`

I am using Python 3.11.2
