### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by danielalexandrou27** [geekan/MetaGPT#165]
Hey i keep trying to install metagpt and whenever i run the installation command (python setup.py install) i get this error :

all other previous commands that were listed to run in the traditional installation instructions ran fine
can anyone help me out with this?

running install
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-21676.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\Lib\site-packages\

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.

**Comment by MachineSaver** [comment]
I just wrote this up incase it'll help you get started on your project.

https://github.com/geekan/MetaGPT/issues/166

**Comment by voidking** [comment]
Sets the current user's writable permissions to directory `C:\Program Files\WindowsApps`.
Or try in cloud environment: [MetaGPT quickstart](https://deepwisdom.feishu.cn/wiki/CyY9wdJc4iNqArku3Lncl4v8n2b)

**Comment by GAN-007** [comment]
hello : help: what could be the issue when clearly i have metagpt in my pip list : metagpt-env) ┌─[sisu@]─[~/Desktop/PROJECTS/AI/fuse ]
└──╼ $metagpt generate "Write a poem about a cat"
bash: metagpt: command not found
(metagpt-env) ┌─[✗]─[sisu@parrot]─[~/Desktop/PROJECTS/AI/fuse ]
└──╼ $pip install metagpt
Requirement already satisfied: metagpt in ./metagpt-env/lib/python3.9/site-packages (0.1)
Requirement already satisfied: PyYAML==6.0 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (6.0)
Requirement already satisfied: tenacity==8.2.2 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (8.2.2)
Requirement already satisfied: faiss-cpu==1.7.4 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (1.7.4)
Requirement already satisfied: tiktoken==0.3.3 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.3.3)
Requirement already satisfied: pydantic==1.10.7 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (1.10.7)
Requirement already satisfied: duckduckgo-search==2.9.4 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (2.9.4)
Requirement already satisfied: openai==0.27.8 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.27.8)
Requirement already satisfied: channels==4.0.0 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (4.0.0)
Requirement already satisfied: fire==0.4.0 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.4.0)
Requirement already satisfied: aiohttp==3.8.4 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (3.8.4)
Requirement already satisfied: loguru==0.6.0 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.6.0)
Requirement already satisfied: pandas==1.4.1 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (1.4.1)
Requirement already satisfied: pytest==7.2.2 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (7.2.2)
Requirement already satisfied: tqdm==4.64.0 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (4.64.0)
Requirement already satisfied: langchain==0.0.231 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.0.231)
Requirement already satisfied: setuptools==65.6.3 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (65.6.3)
Requirement already satisfied: openpyxl in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (3.1.2)
Requirement already satisfied: meilisearch==0.21.0 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.21.0)
Requirement already satisfied: numpy==1.24.3 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (1.24.3)
Requirement already satisfied: python-docx==0.8.11 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.8.11)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (4.0.3)
Requirement already satisfied: frozenlist>=1.1.1 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (1.3.1)
Requirement already satisfied: yarl<2.0,>=1.0 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (1.9.2)
Requirement already satisfied: attrs>=17.3.0 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (3.3.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (6.0.4)
Requirement already satisfied: Django>=3.2 in ./metagpt-env/lib/python3.9/site-packages (from channels==4.0.0->metagpt) (4.2.6)
Requirement already satisfied: asgiref<4,>=3.5.0 in ./metagpt-env/lib/python3.9/site-packages (from channels==4.0.0->metagpt) (3.7.2)
Requirement already satisfied: requests>=2.29.0 in ./metagpt-env/lib/python3.9/site-packages (from duckduckgo-search==2.9.4->metagpt) (2.31.0)
Requirement already satisfied: diskcache>=5.6.1 in ./metagpt-env/lib/python3.9/site-packages (from duckduckgo-search==2.9.4->metagpt) (5.6.3)
Requirement already satisfied: click>=8.1.3 in ./metagpt-env/lib/python3.9/site-packages (from duckduckgo-search==2.9.4->metagpt) (8.1.7)
Requirement already satisfied: termcolor in ./metagpt-env/lib/python3.9/site-packages (from fire==0.4.0->metagpt) (2.3.0)
Requirement already satisfied: six in ./metagpt-env/lib/python3.9/site-packages (from fire==0.4.0->metagpt) (1.16.0)
Requirement already satisfied: openapi-schema-pydantic<2.0,>=1.2 in ./metagpt-env/lib/python3.9/site-packages (from langchain==0.0.231->metagpt) (1.2.4)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in ./metagpt-env/lib/python3.9/site-packages (from langchain==0.0.231->metagpt) (2.0.21)
Requirement already satisfied: langchainplus-sdk<0.0.21,>=0.0.20 in ./metagpt-env/lib/python3.9/site-packages (from langchain==0.0.231->metagpt) (0.0.20)
Requirement already satisfied: numexpr<3.0.0,>=2.8.4 in ./metagpt-env/lib/python3.9/site-packages (from langchain==0.0.231->metagpt) (2.8.7)
Requirement already satisfied: dataclasses-json<0.6.0,>=0.5.7 in ./metagpt-env/lib/python3.9/site-packages (from langchain==0.0.231->metagpt) (0.5.14)
Requirement already satisfied: camel-converter[pydantic] in ./metagpt-env/lib/python3.9/site-packages (from meilisearch==0.21.0->metagpt) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.1 in ./metagpt-env/lib/python3.9/site-packages (from pandas==1.4.1->metagpt) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./metagpt-env/lib/python3.9/site-packages (from pandas==1.4.1->metagpt) (2023.3.post1)
Requirement already satisfied: typing-extensions>=4.2.0 in ./metagpt-env/lib/python3.9/site-packages (from pydantic==1.10.7->metagpt) (4.8.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in ./metagpt-env/lib/python3.9/site-packages (from pytest==7.2.2->metagpt) (1.1.3)
Requirement already satisfied: packaging in ./metagpt-env/lib/python3.9/site-packages (from pytest==7.2.2->metagpt) (23.2)
Requirement already satisfied: tomli>=1.0.0 in ./metagpt-env/lib/python3.9/site-packages (from pytest==7.2.2->metagpt) (2.0.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in ./metagpt-env/lib/python3.9/site-packages (from pytest==7.2.2->metagpt) (1.3.0)
Requirement already satisfied: iniconfig in ./metagpt-env/lib/python3.9/site-packages (from pytest==7.2.2->metagpt) (2.0.0)
Requirement already satisfied: lxml>=2.3.2 in ./metagpt-env/lib/python3.9/site-packages (from python-docx==0.8.11->metagpt) (4.9.3)
Requirement already satisfied: regex>=2022.1.18 in ./metagpt-env/lib/python3.9/site-packages (from tiktoken==0.3.3->metagpt) (2023.10.3)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in ./metagpt-env/lib/python3.9/site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.231->metagpt) (0.9.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in ./metagpt-env/lib/python3.9/site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.231->metagpt) (3.20.1)
Requirement already satisfied: sqlparse>=0.3.1 in ./metagpt-env/lib/python3.9/site-packages (from Django>=3.2->channels==4.0.0->metagpt) (0.4.4)
Requirement already satisfied: certifi>=2017.4.17 in ./metagpt-env/lib/python3.9/site-packages (from requests>=2.29.0->duckduckgo-search==2.9.4->metagpt) (2023.7.22)
Requirement already satisfied: idna<4,>=2.5 in ./metagpt-env/lib/python3.9/site-packages (from requests>=2.29.0->duckduckgo-search==2.9.4->metagpt) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./metagpt-env/lib/python3.9/site-packages (from requests>=2.29.0->duckduckgo-search==2.9.4->metagpt) (2.0.6)
Requirement already satisfied: greenlet!=0.4.17 in ./metagpt-env/lib/python3.9/site-packages (from SQLAlchemy<3,>=1.4->langchain==0.0.231->metagpt) (3.0.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in ./metagpt-env/lib/python3.9/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.231->metagpt) (1.0.0)
Requirement already satisfied: et-xmlfile in ./metagpt-env/lib/python3.9/site-packages (from openpyxl->metagpt) (1.1.0)
(metagpt-env) ┌─[sisu@]─[~/Desktop/PROJECTS/AI/fuse ]
└──╼ $metagpt generate "Write a poem about a cat"
bash: metagpt: command not found
(metagpt-env) ┌─[✗]─[sisu@]─[~/Desktop/PROJECTS/AI/fuse ]
└──╼ $

**Comment by nickbrigham** [comment]
> hello : help: what could be the issue when clearly i have metagpt in my pip list : metagpt-env) ┌─[sisu@]─[~/Desktop/PROJECTS/AI/fuse ] └──╼ $metagpt generate "Write a poem about a cat" bash: metagpt: command not found (metagpt-env) ┌─[✗]─[sisu@parrot]─[~/Desktop/PROJECTS/AI/fuse ] └──╼ $pip install metagpt Requirement already satisfied: metagpt in ./metagpt-env/lib/python3.9/site-packages (0.1) Requirement already satisfied: PyYAML==6.0 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (6.0) Requirement already satisfied: tenacity==8.2.2 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (8.2.2) Requirement already satisfied: faiss-cpu==1.7.4 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (1.7.4) Requirement already satisfied: tiktoken==0.3.3 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.3.3) Requirement already satisfied: pydantic==1.10.7 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (1.10.7) Requirement already satisfied: duckduckgo-search==2.9.4 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (2.9.4) Requirement already satisfied: openai==0.27.8 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.27.8) Requirement already satisfied: channels==4.0.0 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (4.0.0) Requirement already satisfied: fire==0.4.0 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.4.0) Requirement already satisfied: aiohttp==3.8.4 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (3.8.4) Requirement already satisfied: loguru==0.6.0 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.6.0) Requirement already satisfied: pandas==1.4.1 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (1.4.1) Requirement already satisfied: pytest==7.2.2 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (7.2.2) Requirement already satisfied: tqdm==4.64.0 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (4.64.0) Requirement already satisfied: langchain==0.0.231 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.0.231) Requirement already satisfied: setuptools==65.6.3 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (65.6.3) Requirement already satisfied: openpyxl in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (3.1.2) Requirement already satisfied: meilisearch==0.21.0 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.21.0) Requirement already satisfied: numpy==1.24.3 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (1.24.3) Requirement already satisfied: python-docx==0.8.11 in ./metagpt-env/lib/python3.9/site-packages (from metagpt) (0.8.11) Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (4.0.3) Requirement already satisfied: frozenlist>=1.1.1 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (1.4.0) Requirement already satisfied: aiosignal>=1.1.2 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (1.3.1) Requirement already satisfied: yarl<2.0,>=1.0 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (1.9.2) Requirement already satisfied: attrs>=17.3.0 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (23.1.0) Requirement already satisfied: charset-normalizer<4.0,>=2.0 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (3.3.0) Requirement already satisfied: multidict<7.0,>=4.5 in ./metagpt-env/lib/python3.9/site-packages (from aiohttp==3.8.4->metagpt) (6.0.4) Requirement already satisfied: Django>=3.2 in ./metagpt-env/lib/python3.9/site-packages (from channels==4.0.0->metagpt) (4.2.6) Requirement already satisfied: asgiref<4,>=3.5.0 in ./metagpt-env/lib/python3.9/site-packages (from channels==4.0.0->metagpt) (3.7.2) Requirement already satisfied: requests>=2.29.0 in ./metagpt-env/lib/python3.9/site-packages (from duckduckgo-search==2.9.4->metagpt) (2.31.0) Requirement already satisfied: diskcache>=5.6.1 in ./metagpt-env/lib/python3.9/site-packages (from duckduckgo-search==2.9.4->metagpt) (5.6.3) Requirement already satisfied: click>=8.1.3 in ./metagpt-env/lib/python3.9/site-packages (from duckduckgo-search==2.9.4->metagpt) (8.1.7) Requirement already satisfied: termcolor in ./metagpt-env/lib/python3.9/site-packages (from fire==0.4.0->metagpt) (2.3.0) Requirement already satisfied: six in ./metagpt-env/lib/python3.9/site-packages (from fire==0.4.0->metagpt) (1.16.0) Requirement already satisfied: openapi-schema-pydantic<2.0,>=1.2 in ./metagpt-env/lib/python3.9/site-packages (from langchain==0.0.231->metagpt) (1.2.4) Requirement already satisfied: SQLAlchemy<3,>=1.4 in ./metagpt-env/lib/python3.9/site-packages (from langchain==0.0.231->metagpt) (2.0.21) Requirement already satisfied: langchainplus-sdk<0.0.21,>=0.0.20 in ./metagpt-env/lib/python3.9/site-packages (from langchain==0.0.231->metagpt) (0.0.20) Requirement already satisfied: numexpr<3.0.0,>=2.8.4 in ./metagpt-env/lib/python3.9/site-packages (from langchain==0.0.231->metagpt) (2.8.7) Requirement already satisfied: dataclasses-json<0.6.0,>=0.5.7 in ./metagpt-env/lib/python3.9/site-packages (from langchain==0.0.231->metagpt) (0.5.14) Requirement already satisfied: camel-converter[pydantic] in ./metagpt-env/lib/python3.9/site-packages (from meilisearch==0.21.0->metagpt) (3.0.3) Requirement already satisfied: python-dateutil>=2.8.1 in ./metagpt-env/lib/python3.9/site-packages (from pandas==1.4.1->metagpt) (2.8.2) Requirement already satisfied: pytz>=2020.1 in ./metagpt-env/lib/python3.9/site-packages (from pandas==1.4.1->metagpt) (2023.3.post1) Requirement already satisfied: typing-extensions>=4.2.0 in ./metagpt-env/lib/python3.9/site-packages (from pydantic==1.10.7->metagpt) (4.8.0) Requirement already satisfied: exceptiongroup>=1.0.0rc8 in ./metagpt-env/lib/python3.9/site-packages (from pytest==7.2.2->metagpt) (1.1.3) Requirement already satisfied: packaging in ./metagpt-env/lib/python3.9/site-packages (from pytest==7.2.2->metagpt) (23.2) Requirement already satisfied: tomli>=1.0.0 in ./metagpt-env/lib/python3.9/site-packages (from pytest==7.2.2->metagpt) (2.0.1) Requirement already satisfied: pluggy<2.0,>=0.12 in ./metagpt-env/lib/python3.9/site-packages (from pytest==7.2.2->metagpt) (1.3.0) Requirement already satisfied: iniconfig in ./metagpt-env/lib/python3.9/site-packages (from pytest==7.2.2->metagpt) (2.0.0) Requirement already satisfied: lxml>=2.3.2 in ./metagpt-env/lib/python3.9/site-packages (from python-docx==0.8.11->metagpt) (4.9.3) Requirement already satisfied: regex>=2022.1.18 in ./metagpt-env/lib/python3.9/site-packages (from tiktoken==0.3.3->metagpt) (2023.10.3) Requirement already satisfied: typing-inspect<1,>=0.4.0 in ./metagpt-env/lib/python3.9/site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.231->metagpt) (0.9.0) Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in ./metagpt-env/lib/python3.9/site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.231->metagpt) (3.20.1) Requirement already satisfied: sqlparse>=0.3.1 in ./metagpt-env/lib/python3.9/site-packages (from Django>=3.2->channels==4.0.0->metagpt) (0.4.4) Requirement already satisfied: certifi>=2017.4.17 in ./metagpt-env/lib/python3.9/site-packages (from requests>=2.29.0->duckduckgo-search==2.9.4->metagpt) (2023.7.22) Requirement already satisfied: idna<4,>=2.5 in ./metagpt-env/lib/python3.9/site-packages (from requests>=2.29.0->duckduckgo-search==2.9.4->metagpt) (3.4) Requirement already satisfied: urllib3<3,>=1.21.1 in ./metagpt-env/lib/python3.9/site-packages (from requests>=2.29.0->duckduckgo-search==2.9.4->metagpt) (2.0.6) Requirement already satisfied: greenlet!=0.4.17 in ./metagpt-env/lib/python3.9/site-packages (from SQLAlchemy<3,>=1.4->langchain==0.0.231->metagpt) (3.0.0) Requirement already satisfied: mypy-extensions>=0.3.0 in ./metagpt-env/lib/python3.9/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.231->metagpt) (1.0.0) Requirement already satisfied: et-xmlfile in ./metagpt-env/lib/python3.9/site-packages (from openpyxl->metagpt) (1.1.0) (metagpt-env) ┌─[sisu@]─[~/Desktop/PROJECTS/AI/fuse ] └──╼ $metagpt generate "Write a poem about a cat" bash: metagpt: command not found (metagpt-env) ┌─[✗]─[sisu@]─[~/Desktop/PROJECTS/AI/fuse ] └──╼ $

Just had the same issue. Every time I try to use metagpt, I have to uninstall and reinstall it, then figure out how to solve whatever the newest install issue is. Moving on to other platforms.
