### ISSUE TITLE
If You'd Rather Not Install Before Running

### ISSUE THREAD

**Issue by MachineSaver** [geekan/MetaGPT#166]
# If you are having installation problems and just want to run the project without worrying about your environment issues.
I ran this project on replit so you don't have to setup on your own computer before testing.
[METAGPT REPLIT](https://replit.com/@aspiringrdvrk/MetaGPT-1)
You can fork it here and run the commands from the shell.

## Make sure before entering your prompt and running the project you do the following:
1. Edit the API_KEY value under config>key.yaml
 ![image](https://github.com/geekan/MetaGPT/assets/64045074/c699485d-bfd6-489d-a319-9b3189d967b2)
2. Open the Shell
![image](https://github.com/geekan/MetaGPT/assets/64045074/d8ccee19-fe5d-4002-8e92-19cdf43fb00b)
3. Run the program:
![image](https://github.com/geekan/MetaGPT/assets/64045074/57e1f84b-11b0-4069-ab69-c07f97270a64)

**Comment by cristinaisart** [comment]
Hi follow me on onlyfans :[ ](https://onlyfans.com/cristinaenarte)

**Comment by voidking** [comment]
Good job! 
There is a similar job at [MetaGPT quickstart](https://deepwisdom.feishu.cn/wiki/CyY9wdJc4iNqArku3Lncl4v8n2b).

**Comment by MachineSaver** [comment]
Thanks! I didn't realize that other resource existed. The more ways for people to experience these awesome tools the better. Thanks for building such a cool project @geekan.

**Comment by dahifi** [comment]
I'd save my API key in Replit secrets, it gets pulled in from the environment without having it visible to the rest of your team.

**Comment by MachineSaver** [comment]
Good call! Thank you for the heads up. I thought I had deleted it in all the places it needed to be deleted.On Aug 9, 2023, at 6:27 AM, BCM ***@***.***> wrote:﻿
I'd save my API key in Replit secrets, it gets pulled in from the environment without having it visible to the rest of your team.

**Comment by Tian90coder** [comment]
> Couldn't make it work from the fork. Got this ModuleNotFoundError
> 
> ~/MetaGPT$ python startup.py "Write a cli snake game based on pygame" Traceback (most recent call last): File "/home/runner/MetaGPT/startup.py", line 7, in from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager, QaEngineer File "/home/runner/MetaGPT/metagpt/roles/**init**.py", line 9, in from metagpt.roles.role import Role File "/home/runner/MetaGPT/metagpt/roles/role.py", line 15, in from metagpt.config import CONFIG File "/home/runner/MetaGPT/metagpt/config.py", line 13, in from metagpt.utils.singleton import Singleton File "/home/runner/MetaGPT/metagpt/utils/**init**.py", line 9, in from metagpt.utils.read_document import read_docx File "/home/runner/MetaGPT/metagpt/utils/read_document.py", line 9, in import docx File "/home/runner/MetaGPT/venv/lib/python3.10/site-packages/docx.py", line 30, in from exceptions import PendingDeprecationWarning ModuleNotFoundError: No module named 'exceptions'

+ 1

**Comment by DBRenny** [comment]
I get the following error when I go to your replit:

  File ".gitignore", line 4
    __pycache__/
                ^
SyntaxError: invalid syntax

It looks like a neat way to try it, thanks for sharing! I am looking forward to testing it out.

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
