### ISSUE TITLE
Feature: Add support for custom models localhost e.g. TheBloke/WizardCoder-15B-1.0-GPTQ

### ISSUE THREAD

**Issue by miguelgargallo** [geekan/MetaGPT#168]
Possibility to avoid using paid apis, and use TheBloke/WizardCoder-15B-1.0-GPTQ for example

![image](https://github.com/geekan/MetaGPT/assets/5947268/cb5b42b0-a31c-4acb-97e4-0d2e58ccefb2)

I am sure here we all know this but I put the source in case someone don't know https://huggingface.co/TheBloke/WizardCoder-15B-1.0-GPTQ

**Comment by cristinaisart** [comment]
Petite and Puertorrican girl here[ ](https://onlyfans.com/cristinaenarte)
Also, this everything look so interested, I don't understand but I get what are you guys talking, meta, chat gpt, how to that how to this, lol. I wish I knew how to code

**Comment by geekan** [comment]
code llama / llama2 / wizard coder will be integrated

**Comment by j-loquat** [comment]
Would be great to be able to assign multiple local models to the different agents. For example, run llama2 on gpu and assign it to CEO and other managers agents, and run a code-focused local model on cpu and assign it to the engineer agent, etc.

**Comment by j-loquat** [comment]
One thing to consider with local LLM agents is that we should keep the prompts shorter than for OpenAI and reduce the temperature to perhaps lower than 0.5. Lower temp and shorter prompts makes a huge difference in local response times as per GPT4All project.

**Comment by better629** [comment]
refs to `https://docs.deepwisdom.ai/main/en/guide/tutorials/integration_with_open_llm.html`
