### ISSUE TITLE
关于自动生成的项目的完整性

### ISSUE THREAD

**Issue by Lucas66Zhang** [geekan/MetaGPT#17]
我自己在本地测试了几次，生成的项目都不能直接执行，会有各种问题，比如写命令行贪吃蛇，curses库总是抛出错误：
  File "/*****", line 28, in _draw_snake
    self.screen.addch(position[0], position[1], "O")
_curses.error: add_wch() returned ERR
我注意到该仓库长期规划中会添加测试角色，所以我想问下当前自动生成的项目无法完整执行是否是正常情况😂谢谢！

**Comment by geekan** [comment]
是用4还是3.5？

**Comment by Lucas66Zhang** [comment]
4

**Comment by geekan** [comment]
进群，发一下log

**Comment by cc-qq-gg** [comment]
> 进群，发一下log

请问怎么加群

**Comment by geekan** [comment]
@cc-qq-gg https://github.com/geekan/MetaGPT/blob/main/docs/resources/MetaGPT-WeChat-Personal.jpeg

**Comment by WangShuXian6** [comment]
Python 的 Windows 版不包括 [curses](https://docs.python.org/zh-cn/3/library/curses.html#module-curses) 模块。

所以你得用其他模块写游戏
例如：用pygame 写一个贪吃蛇游戏，要图形化界面，兼容windows11。
这个我测试过，完美运行。
