### ISSUE TITLE
Can it be made into a chat GPT plugin?

### ISSUE THREAD

**Issue by rectinajh** [geekan/MetaGPT#172]
Very cool application.Can it be made into a chat GPT plugin?

**Comment by voidking** [comment]
No plans at the moment. we will consider your suggestion.

**Comment by CodeFromAnywhere** [comment]
I can help if you want...

**Comment by voidking** [comment]
> I can help if you want...

Great! Looking forward to your work.

**Comment by better629** [comment]
Since no further responses are needed, we will close it. Please reopen it if necessary.
