### ISSUE TITLE
tenacity.RetryError: RetryError[<Future at 0x1fa21db8190 state=finished raised APIConnectionError>]

### ISSUE THREAD

**Issue by QichangZheng** [geekan/MetaGPT#176]
It seems that the program cannot connect to openai, but I can access GPT4 locally.

**Comment by voidking** [comment]
Please refer to faq8 https://deepwisdom.feishu.cn/wiki/MsGnwQBjiif9c3koSJNcYaoSnu4
Or try the cloud environment https://deepwisdom.feishu.cn/wiki/CyY9wdJc4iNqArku3Lncl4v8n2b

**Comment by QichangZheng** [comment]
Thanks a lot! solved with OPENAI_API_BASE = "https://api.openai-forward.com/v1"

**Comment by CatherineWWJ** [comment]
tenacity.RetryError: RetryError[<Future at 0x1d829ab8a10 state=finished raised AuthenticationError>] How to solve this error?
