### ISSUE TITLE
Specify Directory of pdf documents as Knowledge Base

### ISSUE THREAD

**Issue by alphomeg** [geekan/MetaGPT#178]
Hi, how can we specify any folder which includes pdf documents as a knowledge base and create a new Role of Document Controller to extract specific information from within the documents in KB?

Any help would be highly appreciated

Thanks much appreciated

**Comment by voidking** [comment]
@geekan @wangjie5540

**Comment by wangjie5540** [comment]
I think knowledge-base is a good idea, maybe importing knowledge-base as a tool or a skill for roles to choose is a feasible

**Comment by alphomeg** [comment]
Hi @wangjie5540 thank you for your response, i'm specifically referring to this part of the code in `search_kb.py` inside examples folder.

**Comment by geekan** [comment]
DATA_PATH = PROJECT_ROOT / 'data'
@alphomeg

**Comment by iorisa** [comment]
The MetaGPT has provided a knowledge base tool in `metagpt/document_store`. 
The usage method can refer to the unit test code in `tests/metagpt/document_store` and `examples/search_kb.py`.
