### ISSUE TITLE
No module 'fire'

### ISSUE THREAD

**Issue by rummozKitchen** [geekan/MetaGPT#184]
Having an issue after cloning the repository,

This is the error:

`python startup.py "Write a cli snake game"
Traceback (most recent call last):
  File "C:\Users\shahzer.baig\Desktop\MetaGPT\startup.py", line 5, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'
`

**Comment by voidking** [comment]
Follow Traditional Installation section in [README](https://github.com/geekan/MetaGPT/blob/main/README.md) .

**Comment by rrbaker** [comment]
Depending on your setup, you may also want to make sure you're using the right pip for your environment. (I made this mistake at first and had the same error.)

`which pip` or maybe `which pip3`
