### ISSUE TITLE
usd gpt3.5, always have longth problem

### ISSUE THREAD

**Issue by zhlei07** [geekan/MetaGPT#185]
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, you requested 4847 tokens (3347 in the messages, 1500 in the completion). Please reduce the length of the messages or completion.

**Comment by gertsbergchaim** [comment]
Use "gpt-3.5-turbo-16k-0613" for the model

**Comment by xilin123** [comment]
I  also ran into this issue, but it's been fixed for now.
Solution: You can determine whether the following model configuration type is correct:
```
OPENAI_API_MODEL: "gpt-3.5-turbo-16k"
```

**Comment by caguevara11** [comment]
> I also ran into this issue, but it's been fixed for now. Solution: You can determine whether the following model configuration type is correct:
> 
> ```
> OPENAI_API_MODEL: "gpt-3.5-turbo-16k"
> ```

In my case, the problem is not related to mistyping

**Comment by zhlei07** [comment]
> 

problem solve,thank you.

**Comment by zhlei07** [comment]
> > I also ran into this issue, but it's been fixed for now. Solution: You can determine whether the following model configuration type is correct:
> > ```
> > OPENAI_API_MODEL: "gpt-3.5-turbo-16k"
> > ```
> 
> In my case, the problem is not related to mistyping

problem solve,thank you.
