### ISSUE TITLE
Require open source llms like ChatGLM, ChatRWKV, MPT-30b support.

### ISSUE THREAD

**Issue by stc2001** [geekan/MetaGPT#19]
Whether it is possible to deploy open source llms like ChatGLM, ChatRWKV, MPT-30b support to the project MetaGPT ?

**Comment by geekan** [comment]
Sure. It should be very easy to implement a provider or provide an OpenAI-compatible API, which requires development

**Comment by better629** [comment]
`https://docs.deepwisdom.ai/main/en/guide/tutorials/integration_with_open_llm.html`
