### ISSUE TITLE
mac运行程序失败，liunx ubuntu运行程序失败

### ISSUE THREAD

**Issue by jellzone** [geekan/MetaGPT#2]
mac 运行报下面这个错误，liunx运行也报错，错误类似也是缺少依赖
<img width="566" alt="image" src="https://github.com/geekan/MetaGPT/assets/5356500/4572a90e-fad6-4931-8c1c-a9af86c7be39">

**Comment by geekan** [comment]
这个看起来似乎是连接PYPI的SSL过程失败了，装的库是https://github.com/chroma-core/chroma

或许你要尝试使用清华源 `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple`
