### ISSUE TITLE
Other Programming Languages

### ISSUE THREAD

**Issue by zerofill** [geekan/MetaGPT#20]
Right now, python language is hard coded. It would be nice if, it took the language from the initial prompt, or took the programming language as a command line argument.

**Comment by geekan** [comment]
We will try to provide a multi-language version within a week.

**Comment by magick93** [comment]
To add to this, it would be good if:
- user can specify language(s) and frameworks, eg, specify a frontent - vuejs, svelte, etc
- add requested 3rd party npm, pip etc modules to use - and include a github repo, or docs url
- include a link to developer docs, api docs for any relevant sources

**Comment by geekan** [comment]
This progress is slow, because the first two weeks are filled with other penetrative things. I try to finish writing this feature by 0804. This feature needs to be changed in 10 places, and there is some debugging work

**Comment by p971607** [comment]
> 这一进展缓慢，因为头两周充满了其他高度优先事项。我尝试在 0804 之前完成此功能的编写。此功能需要在 10 处更改，并且有一些调试工作

太棒了，高度高度高度期待

> 
太棒了 ！！！高度期待这项工作啊~~发出土拨鼠之尖叫~~！！

**Comment by iamalin** [comment]
> We will try to provide a multi-language version within a week.

Is there any schedule for this proposal?

**Comment by better629** [comment]
Since no further responses are needed, we will close it. Please reopen it if necessary.
