### ISSUE TITLE
Comment in chinese

### ISSUE THREAD

**Issue by martcpp** [geekan/MetaGPT#202]
Why are comment in code don in chinese they should be translation for ko chinese developer
@martcpp is very good at doing These I recommend you guy get him to these team he translate for bitcoin project .
@stellaHSR @geekan

**Comment by voidking** [comment]
Good job! I saw your PR https://github.com/geekan/MetaGPT/pull/156.

**Comment by martcpp** [comment]
PR #156 should be merge and others I will be making

**Comment by martcpp** [comment]
Same as PR #190

**Comment by stellaHSR** [comment]
merged
