### ISSUE TITLE
if possible let metagpt to write a program to let it self-upgrade

### ISSUE THREAD

**Issue by zhlei07** [geekan/MetaGPT#209]

**Comment by alitrack** [comment]
what does self-upgrade mean?

**Comment by wangjie5540** [comment]
maybe it needs evaluation to guide how to learn itself or tell it which or what is the end~

**Comment by zhlei07** [comment]
for now most of the code 

> maybe it needs evaluation to guide how to learn itself or tell it which or what is the end~

the guide can be the mathematical conjecture?

**Comment by geekan** [comment]
self-upgrade / self-evolve / bootstrap: optimize MetaGPT's code by itself

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
