### ISSUE TITLE
error: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'c:\\python311\\lib\\site-packages\\metagpt-0.1-py3.11.egg'

### ISSUE THREAD

**Issue by ran2014zx** [geekan/MetaGPT#212]
why do i have this error?
had this program since begining...
help

**Comment by NaheelSalman** [comment]
same here

**Comment by Brennan-Richards** [comment]
I am also experiencing this issue when trying to setup the tool for the first time. Happy to help however I can.

**Comment by voidking** [comment]
1. Make sure your python version is 3.9.x
2. Delete the egg file.
3. Execute `pip install -r requirements.txt`

**Comment by Brennan-Richards** [comment]
> 1. Make sure your python version is 3.9.x
> 2. Delete the egg file.
> 3. Execute `pip install -r requirements.txt`

In my case, this seems to have solved the original error. I was able to successfully run 'python setup.py install'. Thank you @voidking  @curiousbero !

**Comment by pcycccccc** [comment]
> 1. Make sure your python version is 3.9.x
> 2. Delete the egg file.
> 3. Execute `pip install -r requirements.txt`

谢谢！！我试了很多方法都没成功，就你这方法最靠谱！！好人！！
