### ISSUE TITLE
支持在现有的项目代码基础上添加新的功能实现吗？（Does it support modifying existing project codes？）

### ISSUE THREAD

**Issue by youqiang95** [geekan/MetaGPT#217]
除了生成项目代码外，支持在现有的项目代码基础上添加新的功能实现吗？例如，我用metaGPT生成了一个代码项目，过一段时间，我需要改变或添加某项功能，如何用mataGPT生成代码的变化部分

Besides generating project code, does it support adding new feature implementations to existing project code? For example, I generated a code project using metaGPT, and after a period of time, I need to change or add a certain feature. How to use mataGPT to generate the changed part of the code

**Comment by voidking** [comment]
当前是不支持的，这个需求在[roadmap](https://github.com/geekan/MetaGPT/blob/main/docs/ROADMAP.md)中了，和issue https://github.com/geekan/MetaGPT/issues/122 类似。

**Comment by better629** [comment]
refs to `https://docs.deepwisdom.ai/main/en/guide/in_depth_guides/incremental_development.html`
