### ISSUE TITLE
ProductManager not found in roles

### ISSUE THREAD

**Issue by asher-gtriip** [geekan/MetaGPT#219]
#Corrected code for __init__.py

"""
@Time    : 2023/5/11 14:43
@Author  : alexanderwu
@File    : __init__.py
"""

from metagpt.roles.role import Role
from metagpt.roles.architect import Architect
from metagpt.roles.project_manager import ProjectManager
from metagpt.roles.product_manager import ProductManager
from metagpt.roles.engineer import Engineer
from metagpt.roles.qa_engineer import QaEngineer
from metagpt.roles.seacher import Searcher
from metagpt.roles.sales import Sales
from metagpt.roles.customer_service import CustomerService

__all__ = [
    "Role",
    "Architect",
    "ProjectManager",
    "ProductManager",
    "Engineer",
    "QaEngineer",
    "Searcher",
    "Sales",
    "CustomerService",
]

**Comment by denniseilander** [comment]
I've opened a PR to fix this issue: https://github.com/geekan/MetaGPT/pull/221
