### ISSUE TITLE
Large projects

### ISSUE THREAD

**Issue by mishav78** [geekan/MetaGPT#226]
Does it code large projects correctly?

**Comment by voidking** [comment]
Theoretically there is no limit, but currently the generated large projects don't work well. There is some work in roadmap to do better.

**Comment by MightEnlightenYou** [comment]
> Theoretically there is no limit, but currently the generated large projects don't work well. There is some work in roadmap to do better.

I know that the similar project "Aider" uses Universal-Ctags to better keep track off and understand large code. Maybe that's something for the devs here to look into?

**Comment by geekan** [comment]
@MightEnlightenYou yes. write it later
