### ISSUE TITLE
幻觉攻击，halluciation attack，how to prevent fundational attack to this project?

### ISSUE THREAD

**Issue by yhyu13** [geekan/MetaGPT#227]
I ran the sample example in the readme,

gpt4 spit out 

curses=2.2
time=1.8 

in the py requirement.txt which not exists on pypi. It is possible that malicious attackers also run your given sample several times with different temperatures and collect a pile of hallucinated packages, and release them with api used in code but for malicious usage, and distributed before anyone else figured that out.

At least there should be a warning/disclaimer for synthetic code/package references in the readme. 

Hallucination attack is a real and identified risk for the current state of LLMs.

**Comment by voidking** [comment]
Good advice! Thanks for your reminding.
