### ISSUE TITLE
Resuming work after interruption 

### ISSUE THREAD

**Issue by newjxmaster** [geekan/MetaGPT#228]
I recently encountered an issue while using application related to connection errors and OpenAI's token limitations. When such an error occurs, the ongoing task gets interrupted. Can you guide me on how we can resume the work from where it stopped once the connection is restored or after the token limitation period has passed

**Comment by voidking** [comment]
There is currently no support for continuing where you left off. This is a work in roadmap.

**Comment by stellaHSR** [comment]
We will support it asap.

**Comment by manoocher** [comment]
@geekan thank you and all others who made this possible. Is there any solution to resume an interrupted run and resume where it was left?

**Comment by geekan** [comment]
@manoocher https://github.com/geekan/MetaGPT/pull/590 implement ser/deser for continue running

**Comment by better629** [comment]
refs to `https://docs.deepwisdom.ai/main/en/guide/in_depth_guides/breakpoint_recovery.html`
