### ISSUE TITLE
ImportError 当运行 startup.py

### ISSUE THREAD

**Issue by LGP0001** [geekan/MetaGPT#233]
当我尝试运行 `startup.py` 时，我遇到了一个 ImportError。我已按照 `requirements.txt` 中列出的依赖进行了安装，并确认我的Python版本满足项目的要求。

具体的错误消息如下：

2023-08-15 20:31:23.375 | INFO | metagpt.config:init:44 - Config loading done.
Traceback (most recent call last):
File "F:\metaGPT\metagpt\startup.py", line 7, in <module>
from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager, QaEngineer
ImportError: cannot import name 'ProductManager' from 'metagpt.roles' (F:\metaGPT\metagpt\metagpt\roles_init_.py)

我已经尝试重新安装所有依赖项，并确保 `pandas` 和其他必要的库已成功安装，但问题仍然存在。

请问有解决这个问题的建议吗？

环境配置：
- 系统：Windows 10
- Python版本：3.11

谢谢。

**Comment by voidking** [comment]
切换python3.9.x版本，或者尝试云端环境 https://deepwisdom.feishu.cn/wiki/Q8ycw6J9tiNXdHk66MRcIN8Pnlg
