### ISSUE TITLE
Preety much useless unless building snake in terminal

### ISSUE THREAD

**Issue by w4rpdr1v3** [geekan/MetaGPT#234]
- any specific instructions are ignored and reduced to basic understanding. it is like gpt for dummies. 
- any request for other language than python is ignored. can't even follow instructions for php.
- simply burning of gpt tokens for nothing. out of 10 projects none worked out of the box.

**Comment by fblgit** [comment]
agree.
it is able to run a flow of deliverables.. but the idea itself .. the implementation is just not good.
he doesnt check wether the code meets the requirements of the idea 5$ to the trash..

**Comment by JTCorrin** [comment]
agree. Was able to get it do spin up none-python projects by adjusting the prompts of the individual roles but ultimately the outputs are still shite.

agree also that the idea is good and offers a good starting point to build on

**Comment by fblgit** [comment]
if u read the promps, evaluations and actions made by the code_review.. is quite funny.. multiple iterations to forge a code .. that at the end is wrong, incomplete, similar to a skeleton. On top of that.. GPT4 is totally unable to create something in full.. due its "security measures".. so no matter if you give him all the piece .. he will output something incomplete. Definitively the fact of having at least always 1 bug/error in the code.. is the most habitual situation..  tho the tool maybe some day is usable.. as the completeness of the deliverables i quite good as a project foundation.. the only problem is the crap code output, sad implementaitons, or just ... nonsense.. 
I ask to create an embedding for a GPT transformer, he made a training loop for a Bert.. the embiddings module was not even near of what it was asked... 

I can resume the experience with this charade:
- I need a new box o send my toys back to england, it must be able to handle 10kg.
- $$$$$$$$$ tokens $$$$$$$$$$$$$
- result: a second hand broken holed box that is made of paper and cant hold even 1kg. It includes instructions, diagram, stories, tests and so for the box.
- fact: the box of paper broken, is useless.. and the fancy docs that it came with, are not gonna make up the fact that the required box is not delivered,,
