### ISSUE TITLE
gpt-4 does not exist or you do not have access to it

### ISSUE THREAD

**Issue by techstartupexplorer** [geekan/MetaGPT#237]
hello, 
i was trying to use gpt-4 since i have gpt4 plus subscription and gpt-3 has 4k+ limit. i always get the following error 

openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

any idea why can't make gpt-4 work with metagpt? while gpt3 works well.

OPENAI_API_MODEL: "gpt-4"
and tried other gpt-4 model same error.

**Comment by prlament** [comment]
Ensure that the API key you're using has the necessary permissions to access GPT-4.
https://api.openai.com/v1/models

**Comment by nevercast** [comment]
ChatGPT is different to OpenAI API. You need to be a paying customer of the API service, which requires you at least have billing information added. If you don't have gpt-4 yet, it may not have been rolled out to you. See this blog post for more info. 

https://openai.com/blog/gpt-4-api-general-availability

**Comment by TaylorTheDeveloper** [comment]
Additionally, you also need to have spent at least $1 to get on the api! https://stackoverflow.com/questions/76653119/openai-gpt-4-api-error-the-model-gpt-4-does-not-exist

**Comment by vbalko** [comment]
You probably dont have access to the model. You need to spend some money on api calls to get access to it.
