### ISSUE TITLE
Need mechanism for defect resolution

### ISSUE THREAD

**Issue by zedtech** [geekan/MetaGPT#239]
Yes, it has problems in generating code, but one possible corrective approach is to have a mechanism to provide a defect list and have it make improvements based on that. Also, I think it would be useful to have it (attempt) to generate a user manual. Another possibly useful approach to improving things would be to allow human editing/refinement of the requirements and design documents and regeneration of code.

**Comment by voidking** [comment]
Thank you very much for your suggestion. Some of the work you mentioned is already in the roadmap, and I hope to implement it as soon as possible.
