### ISSUE TITLE
Snake Game hard coded 

### ISSUE THREAD

**Issue by Techfluent-au** [geekan/MetaGPT#242]
## Selected Elements

Game Grid: The game grid is a rectangular...

Snake: The player controls a snake that moves across the grid...

Food: Food items (often represented as small objects or differently colored blocks)

Score: The player's score increases each time the snake eats a piece of food. The longer the snake becomes, the higher the score.

Game Over: The game ends when the snake collides with itself or an obstacle. At this point, the player's final score is displayed, and they are given the option to restart the game.

## HTML Layout
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Snake Game</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="game-grid">
        
    </div>
    <div class="food">
        
    </div>
</body>
</html>

## CSS Styles (styles.css)
body {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
    background-color: #f0f0f0;
}

.game-grid {
    width: 400px;
    height: 400px;
    display: grid;
    grid-template-columns: repeat(20, 1fr); /* Adjust to the desired grid size */
    grid-template-rows: repeat(20, 1fr);
    gap: 1px;
    background-color: #222;
    border: 1px solid #555;
}

.game-grid div {
    width: 100%;
    height: 100%;
    background-color: #444;
}

.snake-segment {
    background-color: #00cc66; /* Snake color */
}

.food {
    width: 100%;
    height: 100%;
    background-color: #cc3300; /* Food color */
    position: absolute;
}

/* Optional styles for a simple game over message */
.game-over {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 24px;
    font-weight: bold;
    color: #ff0000;
    display: none;

**Comment by voidking** [comment]
What is your specific question?
