### ISSUE TITLE
error: Setup script exited with error: command '/usr/bin/clang' failed with exit code 1

### ISSUE THREAD

**Issue by EsonGitHub** [geekan/MetaGPT#25]
parsed = self.parsers.get(option_name, lambda x: x)(value)
warning: no files found matching 'aiohttp' anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.lib' found anywhere in distribution
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.a' found anywhere in distribution
warning: no previously-included files matching '*.obj' found anywhere in distribution
warning: no previously-included files found matching 'aiohttp/*.html'
no previously-included directories found matching 'docs/_build'
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
error: Setup script exited with error: command '/usr/bin/clang' failed with exit code 1

**Comment by geekan** [comment]
Googled this: https://community.rstudio.com/t/xcrun-error-invalid-active-developer-path-library-developer-commandlinetools-missing-xcrun-at-library-developer-commandlinetools-usr-bin-xcrun-error-compilation-failed-for-package-mnormt/151534

Or wait https://github.com/geekan/MetaGPT/pull/16

**Comment by geekan** [comment]
Could you try the docker version?

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
