### ISSUE TITLE
Roadmap Tasks Claim of 7. Roles, FLock.io 

### ISSUE THREAD

**Issue by ray-ruisun** [geekan/MetaGPT#258]
Greetings, community!

We're excited to announce that our team [FLock.io](https://flock.io/#/) will be contributing to the following roadmap tasks:

- **7.v:** News Observer

- **7.vi**: Institutional Researcher

Stay tuned for updates!

**Comment by stellaHSR** [comment]
Great! I am excited to learn more about the roles you are going to develop.
