### ISSUE TITLE
Work with an existing workspace

### ISSUE THREAD

**Issue by danielgasser** [geekan/MetaGPT#267]
I have created quite a complex prompt and it works well so far (given there is enough MAX_TOKENS).
It creates the app but if I have to make corrections, adaptations or improvements, I have to have it run all from scratch again. Is there a possibility to take it from an existing workspace and tell it like "improve xyz, add xyz, change this or that library, etc"?

**Comment by voidking** [comment]
Not supported, this is a job in roadmap.
