### ISSUE TITLE
tenacity.RetryError: RetryError[<Future at 0x120a31890 state=finished raised InvalidRequestError>]

### ISSUE THREAD

**Issue by RocketStar** [geekan/MetaGPT#269]
Here are my config values ( with KEY masked).
OPENAI_API_BASE: "https://api.openai.com/v1"
OPENAI_API_KEY: "xxxxxxxxxxxxxxxxx"
OPENAI_API_MODEL: "gpt-3.5-turbo"

When I run the demo program,  it reports the following errors after running a while:
`File "/Users/jheng/miniconda3/envs/metagpt/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jheng/miniconda3/envs/metagpt/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jheng/miniconda3/envs/metagpt/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x120a31890 state=finished raised InvalidRequestError>]`

I am running on my Macbook. 

Any pointers?

**Comment by voidking** [comment]
Execute the following command to check whether you can accss OPENAI_API_BASE.
```bash
openai -b "https://api.openai.com/v1" api chat_completions.create -m gpt-3.5-turbo -g user "Hello world"
```

**Comment by RocketStar** [comment]
Here is the execution result:
`$ openai -b "https://api.openai.com/v1" api chat_completions.create -m gpt-3.5-turbo -g user "Hello world"
Hello! How can I assist you today?`

**Comment by zhangjianrong-tal** [comment]
why i run cmd:openai -b "https://api.openai.com/v1" api chat_completions.create -m gpt-3.5-turbo -g user "Hello world"
result is: 
![image](https://github.com/geekan/MetaGPT/assets/131732563/22c477cd-11e6-4184-940d-7fe2a9c2abab)

**Comment by better629** [comment]
Since no further responses are needed, we will close it. Please reopen it if necessary.
