### ISSUE TITLE
Is it possible to update projects that were previously generated?

### ISSUE THREAD

**Issue by arnopoulos** [geekan/MetaGPT#271]
I'm plying around with your repo and I can't seem to figure out how to update projects that have been previously generated or if that's currently possible.

**Comment by voidking** [comment]
Not supported, this is a job in roadmap.

**Comment by better629** [comment]
It's now supported, refs to `https://docs.deepwisdom.ai/main/en/guide/in_depth_guides/incremental_development.html`
