### ISSUE TITLE
Can I use engine mode to connect azure-gpt?

### ISSUE THREAD

**Issue by RainFung** [geekan/MetaGPT#278]
<img width="590" alt="image" src="https://github.com/geekan/MetaGPT/assets/23121539/3ef72f57-b82b-4890-83ca-9c5044927ff1">

```
response = openai.ChatCompletion.create(
  engine="gpt-4-chatbot-ui",
  messages = [{"role":"system","content":"You are an AI assistant that helps people find information."},
```
Officially supports engine mode, Can I use engine mode to connect azure-gpt?

**Comment by voidking** [comment]
@geekan @stellaHSR

**Comment by RainFung** [comment]
https://github.com/geekan/MetaGPT/pull/280

I fixed it. please cc
