### ISSUE TITLE
Token限制

### ISSUE THREAD

**Issue by AustinChen123** [geekan/MetaGPT#279]
我在使用GPT4模型時遇到了超出最大限制(8192tokens)的問題
我參考了其他issue並嘗試更換為gpt-4-32k
但我收到以下錯誤
openai.error.InvalidRequestError: The model `gpt-4-32k` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
我也在上述網址當中找到目前並沒有開放gpt-4-32k給所有用戶
或許可以新增一個total prompt的flag
在敘述過長的時候先進行縮減再傳入下一階段
當前的模式會導致metagpt直接中止
謝謝~

**Comment by geekan** [comment]
明白。已知问题。优化列表中

**Comment by HeroSizy** [comment]
Hi, is this issue resolved?

**Comment by geekan** [comment]
现在我们已经拥有了大量长上下文模型，这不再是个问题
