### ISSUE TITLE
duplicate code

### ISSUE THREAD

**Issue by jiangok-open** [geekan/MetaGPT#294]
I am using gpt-3.5-turbo-16k on MAC. The demo project is completed but the code has below issues:

1. all code in screen.py, snake.py is commented out.
2. screen.py and snake.py duplicate (exactly same) game.py.

Does this demo need gpt4 for generating correct code? Thanks.

**Comment by voidking** [comment]
The effect of gpt4 will be much better, but there is no guarantee that the generated code is error-free, and most of them need to be debugged by ourselves.

**Comment by geekan** [comment]
This problem actually comes from the poor Instruction Following of gpt-3.5-turbo. gpt-4 basically does not have this problem
