### ISSUE TITLE
TypeError: '>' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by pranavvr-lumiq** [geekan/MetaGPT#307]
I tried using the following prompt:

write up a data quality check rules demo for the Instacart Market Basket Analysis dataset from Kaggle. Do not write any code. This is a theoretical look. give detailed explanations for everything. I want a demo specific to this dataset, not a general explanation of dqc. The schema for the dataset is described as follows: The Kaggle Instacart Market Basket Analysis Dataset comprises several key tables. The "Orders" table features columns like "order_id," a unique identifier for orders, and "user_id," a corresponding user identifier. It also includes "eval_set," specifying the dataset split, and "order_number" denoting the order sequence. "Order_dow" signifies the day of the week, while "order_hour_of_day" indicates the hour of order placement. "Days_since_prior_order" reflects the duration since the previous order. The "Products" table contains "product_id," a unique product identifier, and "product_name," describing the product. "Aisle_id" and "department_id" link products to their respective aisles and departments. The "Order Products" table holds "order_id" and "product_id" as foreign keys, detailing the order sequence via "add_to_cart_order" and reorders with a "reordered" flag. Lastly, the "Aisles" table specifies "aisle_id" and "aisle," while the "Departments" table encompasses "department_id" and "department" names. These tables constitute the dataset's schema, facilitating comprehensive analyses of grocery shopping patterns and user preferences.

This is the error I recieved: TypeError: '>' not supported between instances of 'float' and 'str'

**Comment by shenchucheng** [comment]
Could you please provide more details?
1. Detailed steps to reproduce the issue.
2. Any error messages or logs you've encountered.

**Comment by alitrack** [comment]
your prompt is too long and have double quotes, if you want to try it, please replace double quotes with quotes, 

```bash
python startup.py "write up a data quality check rules demo for the Instacart Market Basket Analysis dataset from Kaggle. Do not write any code. This is a theoretical look. give detailed explanations for everything. I want a demo specific to this dataset, not a general explanation of dqc. The schema for the dataset is described as follows: The Kaggle Instacart Market Basket Analysis Dataset comprises several key tables. The 'Orders' table features columns like 'order_id,' a unique identifier for orders, and 'user_id,' a corresponding user identifier. It also includes 'eval_set,' specifying the dataset split, and 'order_number' denoting the order sequence. 'Order_dow' signifies the day of the week, while 'order_hour_of_day' indicates the hour of order placement. 'Days_since_prior_order' reflects the duration since the previous order. The 'Products' table contains 'product_id,' a unique product identifier, and 'product_name,' describing the product. 'Aisle_id' and 'department_id' link products to their respective aisles and departments. The 'Order Products' table holds 'order_id' and 'product_id' as foreign keys, detailing the order sequence via 'add_to_cart_order' and reorders with a 'reordered' flag. Lastly, the 'Aisles' table specifies 'aisle_id' and 'aisle,' while the 'Departments' table encompasses 'department_id' and 'department' names. These tables constitute the dataset's schema, facilitating comprehensive analyses of grocery shopping patterns and user preferences."

```
it works.

of course, the output may not what you want.

**Comment by alitrack** [comment]
your prompt is too long and have double quotes, if you want to try it, please replace double quotes with quotes, 

```bash
python startup.py "write up a data quality check rules demo for the Instacart Market Basket Analysis dataset from Kaggle. Do not write any code. This is a theoretical look. give detailed explanations for everything. I want a demo specific to this dataset, not a general explanation of dqc. The schema for the dataset is described as follows: The Kaggle Instacart Market Basket Analysis Dataset comprises several key tables. The 'Orders' table features columns like 'order_id,' a unique identifier for orders, and 'user_id,' a corresponding user identifier. It also includes 'eval_set,' specifying the dataset split, and 'order_number' denoting the order sequence. 'Order_dow' signifies the day of the week, while 'order_hour_of_day' indicates the hour of order placement. 'Days_since_prior_order' reflects the duration since the previous order. The 'Products' table contains 'product_id,' a unique product identifier, and 'product_name,' describing the product. 'Aisle_id' and 'department_id' link products to their respective aisles and departments. The 'Order Products' table holds 'order_id' and 'product_id' as foreign keys, detailing the order sequence via 'add_to_cart_order' and reorders with a 'reordered' flag. Lastly, the 'Aisles' table specifies 'aisle_id' and 'aisle,' while the 'Departments' table encompasses 'department_id' and 'department' names. These tables constitute the dataset's schema, facilitating comprehensive analyses of grocery shopping patterns and user preferences."

```
it works.

of course, the output may not what you want.
