### ISSUE TITLE
Error communicating with openai 

### ISSUE THREAD

**Issue by doomuch** [geekan/MetaGPT#31]
File "/Users/r/Documents/1-projects/MetaGPT/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.openai.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')]

I've checked that I have correct CA Bundle certificates and I can connect to api.openai.com easily

**Comment by geekan** [comment]
Could you try this: https://github.com/beidongjiedeguang/openai-forward ?
