### ISSUE TITLE
Use Guidance framework for more efficient agent communications

### ISSUE THREAD

**Issue by j-loquat** [geekan/MetaGPT#317]
Use Guidance framework for agent communications
https://github.com/guidance-ai/guidance

See their specific agent example conversation. 

This would allow each agent's output to be structured and controlled accordingly to their roles.
This YouTube video explains it well :
https://youtu.be/69bH4IHZivs?si=RkdCcQRARFT84bof

**Comment by geekan** [comment]
Not under consideration for now.

**Comment by LeaveNhA** [comment]
No offence but, I think you should consider. The output can be structured without the power/bits of the LLM models. This can be a huge, since I'm getting hard time to run the metagpt with a simple task. The output structure is wrong.

@j-loquat, if I invest to do this, can you help me to test it?

**Comment by LeaveNhA** [comment]
@geekan, is there any particular reason for not to consider it? Or is it complicated business decision for anything that we cannot see now?
