### ISSUE TITLE
This repository is over its data quota. 

### ISSUE THREAD

**Issue by cosmicr** [geekan/MetaGPT#319]
> `Error downloading object: docs/resources/tasks.mp4 (404699d): Smudge error: Error downloading docs/resources/tasks.mp4 (404699d040d29cc35dad8cff9961077ea608bed1c947bc930fff084960885a5e): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

I presume this file isn't important?

**Comment by weidwonder** [comment]
+1 新的clone都会报这个错误。
----
Found all new clones from this repo throw this error.

**Comment by shenchucheng** [comment]
@cosmicr @weidwonder Please try again.

**Comment by cosmicr** [comment]
yep seems to be working now thank you.
