### ISSUE TITLE
python setup.py install报错

### ISSUE THREAD

**Issue by zhangjianrong-tal** [geekan/MetaGPT#321]
![image](https://github.com/geekan/MetaGPT/assets/131732563/0054f2aa-21b9-4363-b014-446bdd1953a9)

**Comment by tpayne84** [comment]
Can confirm:
`error: httpx 1.0.0b0 is installed but httpx<1,>=0.23.0 is required by {'anthropic'}`

**Comment by 00sapo** [comment]
Same here with python 3.10 on linux

**Comment by shenchucheng** [comment]
It appears that the command `python setup.py install` may not be able to resolve dependencies properly. You can replace it with `pip install -e .`. Alternatively, you can create a wheel file and install it using pip. For example:
```bash
python setup.py bdist_wheel
pip install dist/metagpt-0.1-py3-none-any.whl
```

**Comment by josepmy** [comment]
End with an error:
I'm on intel Macosx

ERROR: Could not find a version that satisfies the requirement pylance==0.5.10 (from lancedb) (from versions: 0.0.2, 0.3.0, 0.3.1)
ERROR: No matching distribution found for pylance==0.5.10

Thoughts?

**Comment by shenchucheng** [comment]
> End with an error: I'm on intel Macosx
> 
> ERROR: Could not find a version that satisfies the requirement pylance==0.5.10 (from lancedb) (from versions: 0.0.2, 0.3.0, 0.3.1) ERROR: No matching distribution found for pylance==0.5.10
> 
> Thoughts?

@josepmy  Which command do you use, 'pip install -e .' or 'python setup.py install'?

**Comment by josepmy** [comment]
@shenchucheng pip install -r requirements.txt

**Comment by shenchucheng** [comment]
It seems that the Pylance package required by Lancedb is not supported on your platform. You can check the built distributions at https://pypi.org/project/pylance/0.5.10/

**Comment by josepmy** [comment]
@shenchucheng I try pip install pylance but need pyarrow, and pyarrow end with another error:

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyarrow
Failed to build pyarrow
ERROR: Could not build wheels for pyarrow, which is required to install pyproject.toml-based projects

**Comment by shenchucheng** [comment]
@josepmy Try running pip install -U pip setuptools wheel and then reinstall lancedb==0.1.16. If convenient, you can execute pip -V after upgrading pip and paste the output here.

**Comment by shenchucheng** [comment]
My friend successfully ran it on an Intel macOS with Python 3.9.7. Perhaps you should consider downgrading your Python version

**Comment by josepmy** [comment]
@shenchucheng I downgrade to 3.9.7 and same error:

ERROR: Ignored the following versions that require a different python version: 5.0a1 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement pylance==0.5.10 (from lancedb) (from versions: 0.0.2, 0.3.0, 0.3.1)
ERROR: No matching distribution found for pylance==0.5.10

**Comment by martcpp** [comment]
@josepmy what version are you using

**Comment by martcpp** [comment]
And what is try to use 3.11.4 it will work
Fit install requirements before Yuu run  setup
