### ISSUE TITLE
当我运行  python startup.py "贪吃蛇游戏" 时，报这个错误

### ISSUE THREAD

**Issue by EXYNOS9825** [geekan/MetaGPT#328]
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\DevCode\MetaGPT\startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager
ModuleNotFoundError: No module named 'metagpt'

**Comment by shenchucheng** [comment]
You can execute the command `pip install -e .` before running the program.

**Comment by Asmit-Rai** [comment]
Install the Module: If "metagpt" is a third-party package, open your command prompt or terminal and run:
pip install metagpt
Replace "metagpt" with the actual name of the package if it's different. This step installs the missing module.
