### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by adiahuja07** [geekan/MetaGPT#339]
Upon running the command -
192:metagpt adityaahuja$ python3 startup.py "write a cli snake game based on pygame"

This error is showing up. 
I haven't made any changes to the files. 
Any help if appreciated.

Traceback (most recent call last):
  File "startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager
  File "/Users/adityaahuja/metagpt/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "<fstring>", line 1
    (prompt=)
           ^
SyntaxError: invalid syntax

**Comment by shenchucheng** [comment]
Please retry with python3.9+.
