### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by inixfo** [geekan/MetaGPT#360]
I've tried several time but everytime I'm facing the same error. I don't have gpt-4 but I have tried gpt-3.5, gpt-3.5-turbo-16k-0613

(base) PS D:\metagpt> python startup.py "a simple cli blackjack game"
2023-09-24 21:23:03.224 | INFO     | metagpt.config:__init__:44 - Config loading done.
2023-09-24 21:23:07.539 | INFO     | metagpt.software_company:invest:39 - Investment: $3.0.
2023-09-24 21:23:07.542 | INFO     | metagpt.roles.role:_act:167 - Alice(Product Manager): ready to WritePRD
[CONTENT]
{
    "Original Requirements": "Develop a simple command-line interface (CLI) blackjack game.",
    "Search Information": "",
    "Requirements": "",
    "Product Goals": ["Create an engaging and enjoyable blackjack game", "Provide a user-friendly CLI interface", "Ensure the game is easy to understand and play"],
    "User Stories": ["As a player, I want to be able to start a new game of blackjack", "As a player, I want to be able to place bets and receive cards", "As a player, I want to be able to make decisions during the game, such as hitting or standing", "As a player, I want to be able to see my current hand and the dealer's hand", "As a player, I want to be able to see the outcome of the game and my winnings"],
    "Competitive Analysis": [],
    "Competitive Quadrant Chart": "quadrantChart\n    title Reach and engagement of campaigns\n    x-axis Low Reach --> High Reach\n    y-axis Low Engagement --> High Engagement\n    quadrant-1 We should expand\n    quadrant-2 Need to promote\n    quadrant-3 Re-evaluate\n    quadrant-4 May be improved\n    \"Competitor A\": [0.3, 0.6]\n    \"Competitor B\": [0.45, 0.23]\n    \"Competitor C\": [0.57, 0.69]\n    \"Competitor D\": [0.78, 0.34]\n    \"Competitor E\": [0.40, 0.34]\n    \"Competitor F\": [0.35, 0.78]\n    \"Competitor G\": [0.65, 0.45]",
    "Requirement Analysis": "",
    "Requirement Pool": [["P0","The game should allow the player to start a new game"], ["P0","The game should allow the player to place bets and receive cards"], ["P0","The game should allow the player to make decisions during the game"], ["P0","The game should display the player's current hand and the dealer's hand"], ["P0","The game should display the outcome of the game and the player's winnings"]],
    "UI Design draft": "The CLI interface should have a clear and concise layout. It should display the player's current hand and the dealer's hand, as well as any prompts or messages. The player should be able to input their decisions using simple commands, such as 'h' for hit and 's' for stand. The interface should also display the outcome of the game and the player's winnings.",
    "Anything UNCLEAR": ""
}
[/CONTENT]
2023-09-24 21:23:18.135 | INFO     | metagpt.provider.openai_api:update_cost:89 - Total running cost: $0.005 | Max budget: $3.000 | Current cost: $0.005, prompt_tokens: 896, completion_tokens: 561
2023-09-24 21:23:18.141 | INFO     | metagpt.roles.role:_act:167 - Bob(Architect): ready to WriteDesign
[CONTENT]
{
    "Implementation approach": "For the implementation of the CLI blackjack game, we will use the following open-source tools:\n\n1. Click: Click is a Python package for creating beautiful command-line interfaces. It provides an easy way to define command-line commands and options, as well as handling user input and output. We will use Click to create the CLI interface for our blackjack game.\n\n2. Random: The random module in Python provides functions for generating random numbers. We will use the random module to shuffle the deck of cards and deal cards to the player and the dealer.\n\n3. Colorama: Colorama is a Python package that makes it easy to add color to the output in the command-line interface. We will use Colorama to add color to the text in our blackjack game, such as highlighting the player's hand and the dealer's hand.\n\n4. Tabulate: Tabulate is a Python package for creating ASCII tables. We will use Tabulate to display the player's current hand and the dealer's hand in a table format.\n\n5. Pyfiglet: Pyfiglet is a Python package for creating ASCII art from text. We will use Pyfiglet to create a stylish title for our blackjack game.\n\nBy using these open-source tools, we can easily implement a CLI blackjack game that is engaging, user-friendly, and easy to understand and play.",
    "Python package name": "cli_blackjack_game",
    "File list": ["main.py"],
    "Data structures and interface definitions": '
    classDiagram
        class Card{
            +rank: str
            +suit: str
            +value: int
        }

        class Deck{
            -cards: List[Card]
            +shuffle(): None
            +deal_card(): Card
        }

        class Hand{
            -cards: List[Card]
            +add_card(card: Card): None
            +get_value(): int
        }

        class Player{
            -name: str
            -hand: Hand
            -balance: int
            +place_bet(amount: int): None
            +win_bet(amount: int): None
            +lose_bet(amount: int): None
            +hit(deck: Deck): None
            +stand(): None
            +display_hand(): None
        }

        class Dealer{
            -hand: Hand
            +hit(deck: Deck): None
            +stand(): None
            +display_hand(): None
        }

        class Game{
            -deck: Deck
            -player: Player
            -dealer: Dealer
            +start_game(): None
            +play_round(): None
            +end_game(): None
        }

        Card "1" -- "1" Deck: belongs to
        Hand "1" -- "1" Player: belongs to
        Hand "1" -- "1" Dealer: belongs to
        Player "1" -- "1" Game: belongs to
        Dealer "1" -- "1" Game: belongs to
        Game "1" -- "1" Deck: has
        Game "1" -- "1" Player: has
        Game "1" -- "1" Dealer: has
    ',
    "Program call flow": '
    sequenceDiagram
        participant M as Main
        participant G as Game
        participant P as Player
        participant D as Dealer
        participant H as Hand
        participant C as Card
        participant DK as Deck

        M->>G: start game
        G->>P: place bet
        P->>G: win/lose bet
        G->>P: hit
        P->>DK: deal card
        DK->>C: create card
        P->>H: add card
        P->>P: get value
        P->>G: stand
        G->>D: hit
        D->>DK: deal card
        DK->>C: create card
        D->>H: add card
        D->>D: get value
        G->>G: compare hands
        G->>P: display hand
        G->>D: display hand
        G->>G: end round
        G->>M: end game
    ',
    "Anything UNCLEAR": "The requirements are clear to me."
}
[/CONTENT]
2023-09-24 21:23:35.515 | INFO     | metagpt.provider.openai_api:update_cost:89 - Total running cost: $0.012 | Max budget: $3.000 | Current cost: $0.007, prompt_tokens: 1076, completion_tokens: 920
C:\Users\iamah\AppData\Roaming\npm\mmdc
C:\Users\iamah\AppData\Roaming\npm\mmdc.cmd
2023-09-24 21:23:35.658 | INFO     | metagpt.utils.mermaid:mermaid_to_file:43 - Generating D:\metagpt\workspace\cli_blackjack_game\resources\competitive_analysis.pdf..
Traceback (most recent call last):
  File "D:\metagpt\startup.py", line 72, in <module>
    fire.Fire(main)
  File "C:\Users\iamah\miniconda3\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iamah\miniconda3\Lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iamah\miniconda3\Lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\metagpt\startup.py", line 68, in main
    asyncio.run(startup(idea, investment, n_round, code_review, run_tests, implement))
  File "C:\Users\iamah\miniconda3\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\iamah\miniconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iamah\miniconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\metagpt\startup.py", line 47, in startup
    await company.run(n_round=n_round)
  File "D:\metagpt\metagpt\software_company.py", line 60, in run
    await self.environment.run()
  File "D:\metagpt\metagpt\environment.py", line 67, in run
    await asyncio.gather(*futures)
  File "D:\metagpt\metagpt\roles\role.py", line 240, in run
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "D:\metagpt\metagpt\roles\role.py", line 209, in _react
    return await self._act()
           ^^^^^^^^^^^^^^^^^
  File "D:\metagpt\metagpt\roles\role.py", line 168, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\metagpt\metagpt\actions\design_api.py", line 210, in run
    await self._save(context, system_design)
  File "D:\metagpt\metagpt\actions\design_api.py", line 202, in _save
    await self._save_prd(docs_path, resources_path, context)
  File "D:\metagpt\metagpt\actions\design_api.py", line 172, in _save_prd
    await mermaid_to_file(quadrant_chart, resources_path / "competitive_analysis")
  File "D:\metagpt\metagpt\utils\mermaid.py", line 61, in mermaid_to_file
    process = await asyncio.create_subprocess_shell(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iamah\miniconda3\Lib\asyncio\subprocess.py", line 208, in create_subprocess_shell
    transport, protocol = await loop.subprocess_shell(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iamah\miniconda3\Lib\asyncio\base_events.py", line 1661, in subprocess_shell
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iamah\miniconda3\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError

**Comment by Zakk-Yang** [comment]
it has been solved by setting up python env as 3.11.4 and pip install -r requirements.txt from my side

**Comment by nanoaktx** [comment]
fix #360 worked for me.
