### ISSUE TITLE
. environment for key and variable 

### ISSUE THREAD

**Issue by martcpp** [geekan/MetaGPT#371]
Why is there ko .env variable for storage sou keys to protect user from potentially crime or is not not jedd want to work on that

**Comment by iorisa** [comment]
Could you please provide more details? I'm not quite sure what you mean by 'ko .env'.

**Comment by syaikhipin** [comment]
It means that the config.yaml will be turned into .env on the top file

**Comment by geekan** [comment]
https://github.com/theskumar/python-dotenv

**Comment by better629** [comment]
Since no further responses are needed, we will close it. Please reopen it if necessary.
