### ISSUE TITLE
upgrading the installing guided to a set easy setup on the readme.md

### ISSUE THREAD

**Issue by martcpp** [geekan/MetaGPT#381]
i want update the installation guide with step to eg
installing using virtual environments virtual and anacondas
this issues should be assigned to me and label hacktober let me wok on it

**Comment by iorisa** [comment]
Nice

**Comment by martcpp** [comment]
Still waiting for it to be assigned before I start working on it @geekan

**Comment by better629** [comment]
Since no further responses are needed, we will close it. Please reopen it if necessary.
