### ISSUE TITLE
Simple Website Fail

### ISSUE THREAD

**Issue by BAHLZ** [geekan/MetaGPT#393]
I can't seem to get even the simplest website to work. I can see it building files, html, css.. everything looks good but anytime i attempt to use the docker file to build a container, the container fails with different issues depending on the request.

Also, the dockerfile and requirements.txt are in separate folders, is this by design?

**Comment by iorisa** [comment]
Did you use Playwright to crawl the website?

**Comment by BAHLZ** [comment]
No
