### ISSUE TITLE
GPT4好贵，如何接入其它模型呢

### ISSUE THREAD

**Issue by heiheiheibj** [geekan/MetaGPT#403]
比如Qwen、Baichuan2等...

**Comment by heiheiheibj** [comment]
哪怕能接GPT3.5也行
谢谢

**Comment by iorisa** [comment]
只要是openai接口规范的模型都是可以接的。
如果要使用GPT3.5，修改config.yaml中的OPENAI_API_MODEL就行了。

**Comment by hothubby** [comment]
Agree!

**Comment by haochuan-li** [comment]
能不能call本地serve的model呢？比如用TGI和vllm

**Comment by heiheiheibj** [comment]
> 只要是openai接口规范的模型都是可以接的。 如果要使用GPT3.5，修改config.yaml中的OPENAI_API_MODEL就行了。

谢谢

**Comment by HuntZhaozq** [comment]
只修改config.yaml中的OPENAI_API_MODEL和API_Base就可以了吗？没有别的需要修改的地方吗

> 只要是openai接口规范的模型都是可以接的。 如果要使用GPT3.5，修改config.yaml中的OPENAI_API_MODEL就行了。

**Comment by reginold** [comment]
但gpt3。5写出来的基本不能用， 和4 没法比呀

**Comment by heiheiheibj** [comment]
> 但gpt3。5写出来的基本不能用， 和4 没法比呀

唉，GPT4太贵了，公司也不给报销 ：P

**Comment by calvinweb** [comment]
感觉可以上langchain当 支持一堆llm可以直接用

**Comment by stellaHSR** [comment]
Currently, we support ChatGLM/Spark, pls refer to https://github.com/geekan/MetaGPT/blob/main/metagpt/provider/zhipuai/zhipu_model_api.py
https://github.com/geekan/MetaGPT/blob/main/metagpt/provider/spark_api.py

**Comment by heiheiheibj** [comment]
thx

> Currently, we support ChatGLM/Spark, pls refer to https://github.com/geekan/MetaGPT/blob/main/metagpt/provider/zhipuai/zhipu_model_api.py https://github.com/geekan/MetaGPT/blob/main/metagpt/provider/spark_api.py
