### ISSUE TITLE
Single-agent GPT-4 baselines so under-reported in general.

### ISSUE THREAD

**Issue by sieu-n** [geekan/MetaGPT#418]
I believe the single-agent GPT-4 baselines in the paper are significantly under-reported. Please correct me if I missed something 😊

**1. HumanEval**

https://github.com/saschaschramm/chatgpt#performance

Though I agree that small variances due to prompting, few-shot examples, formatting etc. are very hard to control, the numbers are very odd. 

- The 67% HumanEval reported in your paper (and the GPT-4 Technical Report) is far from what you get using the API/ChatGPT.
- In particular, the **baseline** HumanEval score for `gpt-4-0613` is **86.59%**, and for `gpt-3.5-turbo-0613` it is 71.34%. 
- There could be differences in the evaluation procedure, but it seems that the inherent capabilities of GPT-4 with a simple framework are much capable. At a minimum, your work should include baseline results for the 0613 model using your evaluation framework, or discuss related work. 
- Not to mention comparisons with other single-agent works on improving the coding capabilities of GPT which report much higher scores (e.g. reflection)

**2. program development**

Is gpt-4 *really* incapable of generating such simple programs? Especially considering that there are dozens of public implementations of snake game or 2048 on Github?

These are tasks claimed to fail, according to Table 2. However, I noticed that most apps can be successfully created without any complex framework, often using a single prompt. 

I simply pasted the official prompt in Table 6. Since ChatGPT responses are typically short, if the model suggests the current code is incomplete, I responded `continue` until the code is complete. 

|   Task    | Result | Conversation url | 
| --------- | ---    | ---------------  |
| 2048-web  | ✅     | [link](https://chat.openai.com/share/24bd875e-64dc-48f5-8eb9-713c398535df) |   
|  2048-py  | ✅     | [link](https://chat.openai.com/share/83818bfd-dec7-41a6-8edc-c65b1bd7a4c9) | 
|   snake   | ✅     | [link](https://chat.openai.com/share/46c4287c-a7fe-40b8-a1fa-de14d8d46df3)     |  
| tank-game-cont | ✅ | [link](https://chat.openai.com/share/5221714a-7251-4a84-b304-5fd4f72d5fb9) | 
|   brick   | ✅     | [link](https://chat.openai.com/share/22bbc1d1-bc94-447f-afc8-4304ab942c12)     |  
|  flappy   | ❌     | [link](https://chat.openai.com/share/ed67939a-14ee-4843-b2d5-08e3fcf2bcb3)     |  
|   excel   | ✅     | [link](https://chat.openai.com/share/597463c1-8b0d-4fa2-a644-849aa68ad2db)     | 
|    crud   | ✅     | [link](https://chat.openai.com/share/3736879e-9044-4833-a3ab-6f68c1a2675b)     | 

The generated code can also be found in my [git](https://github.com/sieu-n/metagpt-baselines).

I haven't tested using the agent framework, so I believe that your results could be true, but this just makes me think that the proposed method isn't so convincing...

**Comment by stellaHSR** [comment]
Hi, thx! There are five different time zones among our collaborating team members, which makes collaboration somewhat challenging. We are making efforts to facilitate this, and we hope to release the results soon.

**Comment by gdmcdonald** [comment]
Some good points to consider here.

**Comment by geekan** [comment]
1. This is a very good discussion. So far, reports on the performance of different APIs of GPT-4 vary greatly, ranging from official 67 to 86. However, actual tests generally cannot reach the 86 indicator, and it is difficult for us to reproduce the results of these repos. The actual results we test are often very different from the results of the repo. In some repos, GPT-4's 100% correct results can only obtain an accuracy of less than 20% in our test (after 10 retries) , cannot be reproduced, so we still use the data from the official OpenAI paper
2. In the repo generated by "continue", taking the first one as an example, it still does not actually generate the function isGameOver, the code is not written correctly (meaning it cannot run), and the generated CSS only has one color. This is different from the actual requirements of 2048; other examples have similar problems

We have reached an extremely high HumanEval score internally and will make it public later. Welcome to pay attention

**Comment by shatealaboxiaowang** [comment]
> 1. This is a very good discussion. So far, reports on the performance of different APIs of GPT-4 vary greatly, ranging from official 67 to 86. However, actual tests generally cannot reach the 86 indicator, and it is difficult for us to reproduce the results of these repos. The actual results we test are often very different from the results of the repo. In some repos, GPT-4's 100% correct results can only obtain an accuracy of less than 20% in our test (after 10 retries) , cannot be reproduced, so we still use the data from the official OpenAI paper
> 2. In the repo generated by "continue", taking the first one as an example, it still does not actually generate the function isGameOver, the code is not written correctly (meaning it cannot run), and the generated CSS only has one color. This is different from the actual requirements of 2048; other examples have similar problems
> 
> We have reached an extremely high HumanEval score internally and will make it public later. Welcome to pay attention

Hi, Dear:
When testing the code generation task with the agent, did you use any external tools ? especially web search ?
Curious how do you achieve highg scores on humaneval, is there any implementation logic in the project code ?
thank you!
