### ISSUE TITLE
How to generate/print the list of prompt?

### ISSUE THREAD

**Issue by mrharishkumar** [geekan/MetaGPT#435]
Hi

Thanks for writing the amazing library. While using it for creating a snake game, i am trying to print/log all the prompts fired by the library in sequential order during the process of generating the code.

Is this possible at the moment? If yes, how can I do it.
This will be incredibly helpful for the explanation of the code generation procedure.

Thanks in anticipation.

**Comment by iorisa** [comment]
You can add code related to printing the prompt in the `_aask` function and the `_aask_v1` function in `metagpt/actions/action.py`. All role actions inherit from this class and utilize these two functions to call the LLM.

**Comment by mrharishkumar** [comment]
Thank you, @iorisa, for your response. It has been very informative and has given me a much clearer understanding of MetaGPT. I can now print these prompts. Considering this issue resolved.
