### ISSUE TITLE
Overall cost does not match up

### ISSUE THREAD

**Issue by vagi8** [geekan/MetaGPT#439]
So the cost shown in my cli is a bunch of

> metagpt.provider.openai_api:update_cost:89 - Total running cost: $0.196 | Max budget: $3.000 | Current cost: $0.016, prompt_tokens: 4660, completion_tokens: 491
> metagpt.provider.openai_api:update_cost:89 - Total running cost: $0.214 | Max budget: $3.000 | Current cost: $0.018, prompt_tokens: 5165, completion_tokens: 615
> metagpt.provider.openai_api:update_cost:89 - Total running cost: $0.180 | Max budget: $3.000 | Current cost: $0.015, prompt_tokens: 4684, completion_tokens: 326
> ...

A bunch of such lines show the cost. but they add up to more than the cost shown in my openAI account. I am happy but wanted to know the calculation and what do each cost show above mean.

**Comment by iorisa** [comment]
This is a cost estimation based on the number of tokens exchanged between MetaGPT and the Language Model (LLM), and it's provided solely as a reference metric. The actual expenses will be determined by the official settlement. You can find this code snippet in the `_calc_usage` function in `metagpt/provider/openai_api.py`.
