### ISSUE TITLE
pip install -e . 安装报错`ERROR: Could not find a version that satisfies the requirement yaml~=0.2.5 (from metagpt) (from versions: none) ERROR: No matching distribution found for yaml~=0.2.5`

### ISSUE THREAD

**Issue by lplzyp** [geekan/MetaGPT#445]

**Comment by otchlan** [comment]
For now I deleted in yaml~=0.2.5 in requirements.txt and process go to the end

**Comment by rusenask** [comment]
yeah you can comment it out, maybe just do `pip install pyyaml` on the side to be safe 😄

**Comment by stellaHSR** [comment]
We have made changes to the requirements.txt file. You can either pull the updated file or update it manually.
