### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'str' and 'str' 

### ISSUE THREAD

**Issue by FromNigeria** [geekan/MetaGPT#453]

**Comment by iorisa** [comment]
ChatGPT says: 

>The error message "TypeError: unsupported operand type(s) for -: 'str' and 'str'" indicates that you are trying to subtract two strings, which is not a valid operation in Python.
>
>To resolve this error, you should check your code to ensure that you are performing operations that are appropriate for the data types involved. If you are trying to concatenate or manipulate strings, use the `+` operator for concatenation, not the `-` operator, which is used for subtraction.

Can you try to catch this exception and provide the stack trace information?
Something like this:
```
        try:
            ......
        except Exception as e:
            logger.exception(f"exception:{e}, traceback:{traceback.format_exc()}")
```

**Comment by FromNigeria** [comment]
I have shared my Google Colab link below,can you check the code and see if
you can add that for me
