### ISSUE TITLE
`log_and_reraise` is not defined in openai_api.py

### ISSUE THREAD

**Issue by erdem** [geekan/MetaGPT#454]
I recently set up the project and encountered an error stating that; 

```
NameError: name 'log_and_reraise' is not defined
```

After investigating, I found the issue originates from the openai_api.py module, specifically [this line](https://github.com/geekan/MetaGPT/blob/main/metagpt/provider/openai_api.py#L233). 

It appears that `log_and_reraise` is being used as a decorator argument, but it's not defined or imported in the module.

**Comment by ManbasJi** [comment]
I also encountered the same problem

**Comment by antunsz** [comment]
@erdem it was solved in this commit some days ago https://github.com/geekan/MetaGPT/commit/4b122903f4b87ceb2e5cef19dc8906f48ffd9cdb 👍🏼

**Comment by erdem** [comment]
Thanks for the update! Closing the issue then.
