### ISSUE TITLE
Adding Contributors section to the readme.md 

### ISSUE THREAD

**Issue by mohitd404** [geekan/MetaGPT#467]
Why Contributors section:- A "Contributors" section in a repo gives credit to and acknowledges 
the people who have helped with the project, fosters a sense of community, and helps others
 know who to contact for questions or issues related to the project.

**Issue type**

- [✅] Docs

Expected Behaviour:- 

![3](https://github.com/geekan/MetaGPT/assets/146939900/6689c0f1-c77a-47e5-b786-5b7b7cfbb448)

**Comment by mohitd404** [comment]
@ kindly assign this issue to me ! I would love to work on it ! Thank you !

**Comment by mohitd404** [comment]
@stellaHSR I have made the changes kindly review !!

**Comment by martcpp** [comment]
Can you share outcome of change using pictures @mohitd404
