### ISSUE TITLE
Adding code-of-conduct File to the repo !

### ISSUE THREAD

**Issue by mohitd404** [geekan/MetaGPT#468]
code-of-conduct:- We propose adding a comprehensive Code of Conduct to our repository to ensure 
a safe, respectful, and inclusive environment for all contributors and users. This code will 
serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a 
wider range of perspectives.

**Issue type**

- [✅] Docs

@ kindly assign this issue to me ! I would love to work on it ! Thank you !

**Comment by mohitd404** [comment]
@stellaHSR  kindly assign this issue to me ! I would love to work on it ! Thank you !

**Comment by stellaHSR** [comment]
Hi, thank you! We would like to have the code of conduct document included in our repository.

**Comment by mohitd404** [comment]
@stellaHSR I have made the changes kindly review it !
