### ISSUE TITLE
Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by mayilin0714** [geekan/MetaGPT#470]
Issue Description / 问题描述
Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Steps to Reproduce / 复现步骤
cd MetaGPT && docker build -t metagpt:custom .

Error Screenshots or Logs / 错误截图或日志

<img width="1060" alt="image" src="https://github.com/geekan/MetaGPT/assets/71692462/57f54258-4999-48f2-8035-fb1ff5d47456">

**Comment by voidking** [comment]
The error indicate that your network can not access to docker hub.
You need to config a proxy.
