### ISSUE TITLE
Exceeded token limit - Contacting the developer of metagpt

### ISSUE THREAD

**Issue by gnovelli** [geekan/MetaGPT#477]
[error.txt](https://github.com/geekan/MetaGPT/files/13256111/error.txt)

It looks like the code encountered an error due to exceeding the token limit set by the model. This happened when attempting to generate a completion using the OpenAI API, specifically for the model that has a maximum context length of 8192 tokens. However, the request included 8298 tokens, which is beyond the allowed limit.

The error trace is showing that the problem occurred in an asynchronous call within a Python script that is part of a larger application, perhaps one that is simulating a software company environment where an "engineer" role is trying to generate code through a `WriteCode` action.

Here's a breakdown of the issue:

1. The `write_code` method in `write_code.py` is called to generate some code.
2. This method makes an asynchronous request to the OpenAI API to get a response.
3. The request fails because the combined length of the messages and the expected completion exceeds the model's token limit.
4. Tenacity, a library for retrying failed operations, attempts to retry the operation, but it keeps failing because the token limit issue is not resolved.
5. Eventually, Tenacity stops retrying and raises a `RetryError`, which is not caught, causing the whole application to crash.

To fix this issue, you would need to:

- Reduce the size of the input prompt or the expected length of the completion so that the total number of tokens does not exceed the model's limit of 8192 tokens.
- Catch and handle the `InvalidRequestError` exception to ensure the application does not crash, possibly by adjusting the input and retrying.
- If the input cannot be reduced, consider breaking down the task into smaller parts that can be processed within the token limit and then combine the results. 

If you're looking to adjust the script, it would involve catching the exception where the `write_code` method is called and then trimming the input. If you have access to the code, you can modify the relevant part of the script to handle this case. **Otherwise, you may need to contact the developer of the application if you're not able to modify the code yourself.**

**Comment by martcpp** [comment]
Will modify this today check back Later thanks
