### ISSUE TITLE
Is Langchain considered?/是否考虑过使用langchain作为后端

### ISSUE THREAD

**Issue by calvinweb** [geekan/MetaGPT#478]
这个想法很不错 但是看了下代码 似乎是从llm抽象层就开始是自己造轮子了，感觉意义不大。 使用Langchain作为后端的话可以省不少时间，把经历集中在功能上

**Comment by iorisa** [comment]
MetaGPT是面向算法同学的单机版控制台程序开发框架，简单的功能模块利于算法开发同学上手。
 算法同学可以轻松改造里面的任何一个模块、流程。
 集成langchain反而会增加这种改造的难度，所以一开始这个方案就被否了。

**Comment by flychatin** [comment]
这个能换成百度文心一言接口吗

**Comment by calvinweb** [comment]
> 这个能换成百度文心一言接口吗

暂时没见到langchain支持文心 但是其实适配不难

**Comment by calvinweb** [comment]
> MetaGPT是面向算法同学的单机版控制台程序开发框架，简单的功能模块利于算法开发同学上手。 算法同学可以轻松改造里面的任何一个模块、流程。 集成langchain反而会增加这种改造的难度，所以一开始这个方案就被否了。

我的意思是使用langchain的llm/vectorstorage抽象层，而不是用整个langchain那一套

**Comment by scriptboy1990** [comment]
> > MetaGPT是面向算法同学的单机版控制台程序开发框架，简单的功能模块利于算法开发同学上手。 算法同学可以轻松改造里面的任何一个模块、流程。 集成langchain反而会增加这种改造的难度，所以一开始这个方案就被否了。
> 
> 我的意思是使用langchain的llm/vectorstorage抽象层，而不是用整个langchain那一套

只使用这两个功能，为啥不自己搞一套。。。。

**Comment by calvinweb** [comment]
> > > MetaGPT是面向算法同学的单机版控制台程序开发框架，简单的功能模块利于算法开发同学上手。 算法同学可以轻松改造里面的任何一个模块、流程。 集成langchain反而会增加这种改造的难度，所以一开始这个方案就被否了。
> > 
> > 
> > 我的意思是使用langchain的llm/vectorstorage抽象层，而不是用整个langchain那一套
> 
> 只使用这两个功能，为啥不自己搞一套。。。。

因为lc的较为完善 且支持大量模型

**Comment by geekan** [comment]
各位好，我们暂时还没有长期支持LangChain的计划。
