### ISSUE TITLE
SoftwareDev Dataset

### ISSUE THREAD

**Issue by XZH-HZX** [geekan/MetaGPT#482]
Very cutting edge work, we noticed the SoftwareDev data set mentioned in the latest version of the paper, where can I access the data set?

**Comment by seehi** [comment]
We will prioritize updating the complete evaluation methods and relevant usage instructions for this dataset, and provide the dataset later.

**Comment by wangruo91** [comment]
> We will prioritize updating the complete evaluation methods and relevant usage instructions for this dataset, and provide the dataset later.

Hello, is there any progress on this dataset? Thanks！

**Comment by huangd1999** [comment]
Hello, is there any progress on this dataset?

**Comment by JuicyOrange666** [comment]
Hello, is there any progress on this dataset?
