### ISSUE TITLE
如何细化需求？

### ISSUE THREAD

**Issue by sd797994** [geekan/MetaGPT#5]
只用一句话去创建整个项目从商业设计上来讲是不靠谱的除非是很简单的逻辑比如“创建一个js版本的贪食蛇”。但是当我们要依赖AI去设计更大规模的系统时，我建议还是需要增加更加复杂的交互式设计通过AI去收集多轮对话的需求以及更多的细节让整个项目的生成变得更加可靠。如果是真的考虑商业化落地的话

**Comment by geekan** [comment]
是的。在todo list上，请等待1-2天

**Comment by geekan** [comment]
https://github.com/geekan/MetaGPT/blob/main/docs/ROADMAP.md

这是目前的ROADMAP，其中Complete the design and implementation of module breakdown任务与此对应

**Comment by WangShuXian6** [comment]
目前我是直接使用详细的产品需求去给到MetaGPT,几百个字没问题~~
