### ISSUE TITLE
why generated code is always "python" and "Flask"

### ISSUE THREAD

**Issue by mtrabelsi** [geekan/MetaGPT#517]
why generated code is always "python" and "Flask"?
I use gpt4, and I clearly specified reactJS project, then it keeps generating python/flask projects, which is very weird!!!

**Comment by seehi** [comment]
Multi-programming-language support is already on our roadmap, you can check the details here: https://github.com/geekan/MetaGPT/blob/main/docs/ROADMAP.md.

The MetaGPT framework based on the think-act paradigm has proven its programming capabilities in the Python language. If you want to try it yourself, you can modify the prompts of two actions in metagpt/roles/engineer.py file of Engineer class to change the output programming language:
- metagpt/actions/write_code.py
- metagpt/actions/write_code_review.py

**Comment by geekan** [comment]
try latest code.
