### ISSUE TITLE
TPM rate limited

### ISSUE THREAD

**Issue by FAndSec** [geekan/MetaGPT#523]
This error can be found when running:

openai.error.RateLimitError: Rate limit reached for gpt-4 in organization org-uVqpjtJiKqvVJMVfvpaounIh on tokens per min (TPM): Limit 10000, Used 8554, Requested 3082. Please try again in 9.816s. Visit https://platform.openai.com/account/rate-limits to learn more.

Do we have a TPM (Tokens per Minute) setting?

**Comment by geekan** [comment]
we've RPM setting so far, but no TPM setting
