### ISSUE TITLE
使用Chat-GLM3开源模型报错

### ISSUE THREAD

**Issue by QingChengLineOne** [geekan/MetaGPT#526]
我将模型替换为Chat-GLM3，在运行的时候报错：
![image](https://github.com/geekan/MetaGPT/assets/111961874/bdcdef32-2fd2-4328-8521-dc3bc3331ea7)

**Comment by QingChengLineOne** [comment]
> @QingChengLineOne what's the error log and your configuration?
这是我的key.yaml的配置文件
![image](https://github.com/geekan/MetaGPT/assets/111961874/7b12f2c3-3d48-44e3-8fce-f6fc3373dbbb)

**Comment by geekan** [comment]
https://github.com/geekan/MetaGPT/pull/500 fix this. Would you plz try again?
