### ISSUE TITLE
upgrade openai version

### ISSUE THREAD

**Issue by Undertone0809** [geekan/MetaGPT#529]
I think we should upgrade the OpenAI version to `>1.0.0`. Using the new APIs to call openai service and recevice latest features such as assistant APIs.

**Comment by weburnit** [comment]
yeah... no idea why metagpt is still having 0.28.x
it's annoying with openai.error package

**Comment by aleibz98** [comment]
There is a pull request ready for that: https://github.com/geekan/MetaGPT/pull/530

**Comment by geekan** [comment]
now main branch is 1.6.0 #519
