### ISSUE TITLE
BUG: research report 文件名问题

### ISSUE THREAD

**Issue by QIN2DIM** [geekan/MetaGPT#560]
保存报告时，程序将 topic 作为 report markdown 文件名的一部分。应在程序运行前检查 topic 是否包含不合法的字符。

**Comment by geekan** [comment]
你能举个具体的例子吗？

**Comment by QIN2DIM** [comment]
https://github.com/geekan/MetaGPT/blob/73411d21ebfcf723f5f1158acddb142f98846ccb/metagpt/roles/researcher.py#L99-L103

已知的不合法字符：
```python
inv = {"\\", "/", ":", "*", "?", "<", ">", "|"} 
```

如果topic 包含换行符 `\n`，大概率就挂掉了
