### ISSUE TITLE
python startup.py  'create a Tetris game' 

### ISSUE THREAD

**Issue by taype** [geekan/MetaGPT#568]

**Comment by taype** [comment]
environment：windows 10 python11
LLM：zhipu
The following problem occurs, please see the attachment.
[error.json](https://github.com/geekan/MetaGPT/files/13686244/error.json)
main information:
│ d:\metagpt\metagpt\metagpt\actions\action_node.py:275 in _aask_v1                                │
│                                                                                                  │
│   272 │   │   │   parsed_data = OutputParser.parse_data_with_mapping(content, output_data_mapp   │
│   273 │   │                                                                                      │
│   274 │   │   logger.debug(parsed_data)                                                          │
│ > 275 │   │   instruct_content = output_class(**parsed_data)                                     │
│   276 │   │   return ActionOutput(content, instruct_content)                                     │
│   277 │                                                                                          │
│   278 │   def get(self, key):                                                                    │
│

**Comment by mahimairaja** [comment]
Can you please share the python version and the metagpt version you used? @taype

**Comment by taype** [comment]
> Can you please share the python version and the metagpt version you used? @taype

yes, 
python version :Python 3.11.5
metagpt : I use git clone https://github.com/geekan/MetaGPT.git .  so it would newest version

**Comment by better629** [comment]
Maybe you can use gpt-4 to have a try, the zhipu problem we will follow up.

**Comment by taype** [comment]
got it. I will try this project later.
