### ISSUE TITLE
When running the latest version, I encountered a problem that I could not call llm,2023-12-4 v0.4.0 does not have this problem

### ISSUE THREAD

**Issue by elephone** [geekan/MetaGPT#569]
When I was running the latest version, I encountered a problem that I could not call llm. v0.4.0 of 2023-12-4 could not call llm without this problem, but no error was reported. The result is as follows:
![0b547fd86f96222c363d22777a927ff](https://github.com/geekan/MetaGPT/assets/5245692/862e30f6-dad7-4278-aaa5-0330aa684329)

But Commits on Dec 4, 2023's version doesn't have that problem

**Comment by shenchucheng** [comment]
Please try metagpt==0.5.1.
