### ISSUE TITLE
编码角色不工作（Engineer Role didn't work）

### ISSUE THREAD

**Issue by real-big-fish** [geekan/MetaGPT#604]
**Bug description**

I encountered an issue while using metaGPT. When I used the prompt "metaGPT "make a cli snake game"," the engineer role did not work and failed to generate any code. Eventually, partial files were generated by the code reviewer role. All other roles are functioning properly.
我在使用metaGPT的时候，遇到了问题，使用例子“metaGPT “make a cli snake game”，engineer角色不工作，生成不了代码，最终由代码审查角色生成了部分文件。其他角色都工作正常。  

**Bug solved method**

**Environment information**

- LLM type and model name:
- System version: OpenAI gpt-4-1106-preview
- Python version: conda Python 3.11.5

- packages version: megaGPT realse 0.5
- installation method: pip3 install -e.

**Screenshots or logs**

[cmd_output.rtf.zip](https://github.com/geekan/MetaGPT/files/13748361/cmd_output.rtf.zip)
[cli_snake_adventure.zip](https://github.com/geekan/MetaGPT/files/13748402/cli_snake_adventure.zip)

**Comment by real-big-fish** [comment]
[cli_snake_adventure.zip](https://github.com/geekan/MetaGPT/files/13748392/cli_snake_adventure.zip)
这个是最终生成的项目代码，this is the snake project.

**Comment by geekan** [comment]
Hello, try to install the latest main branch and try again
BTW, what version of GPT do you use?

**Comment by real-big-fish** [comment]
version: gpt-4-1106-preview
 use the lateest main branch and it still can not work properly ...

**Comment by real-big-fish** [comment]
> Hello, try to install the latest main branch and try again BTW, what version of GPT do you use?

version: gpt-4-1106-preview
use the lateest main branch and it still can not work properly ...

**Comment by geekan** [comment]
Excuse me, are there still problems in the latest version?

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
