### ISSUE TITLE
关于长期记忆和向量存储的问题

### ISSUE THREAD

**Issue by prinzchao** [geekan/MetaGPT#609]
https://github.com/geekan/MetaGPT/tree/ga_game

我看到这个移植版的斯坦福小镇源码，记忆好像是二次开发实现的。

请问如果我想找一个比较成熟的向量储存框架用于长期记忆，是否metagpt这边有推荐的稳定方案，用什么外部数据库或者什么现成框架可以实现，感谢～

**Comment by geekan** [comment]
我们现在默认使用原始的faiss，坦白来说，向量数据库的效果还是一个核心问题，或者长期来看还是更多dot

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
