### ISSUE TITLE
pip install -e . successful but pip show Package(s) not found: metagpt

### ISSUE THREAD

**Issue by mrocker** [geekan/MetaGPT#618]
**Bug description**
Checkout source code from git

Run: "pip install -e ." in MetaGPT dir
Return: 
===
Installing collected packages: metagpt
Running setup.py develop for metagpt
Successfully installed metagpt
===
Run: "pip show metagpt"
Return: "WARNING: Package(s) not found: metagpt"

Run examples, Return: "ModuleNotFoundError: No module named 'metagpt'"

**Environment information**
MacOS 14.2.1 on M1 chip.
pip 23.3.2 from /Users/nick.cheng/Library/Python/3.9/lib/python/site-packages/pip (python 3.9)

- installation method: pip install from source

**Screenshots or logs**

<img width="459" alt="截屏2023-12-25 12 14 38" src="https://github.com/geekan/MetaGPT/assets/633190/f57d5b7c-6831-4d79-ab18-e596d42e870b">
[install.log](https://github.com/geekan/MetaGPT/files/13764047/install.log)

**Comment by geekan** [comment]
我尝试了几次安装与卸载操作，但是没法复现这个场景。查看你的日志，发现头部的“Defaulting to user installation because normal site-packages is not writeable”日志，或许检查一下对应路径，以及这个路径是否被python sys path所正确引用？

**Comment by DreamWalker1412** [comment]
Hello, I have the same problem and am struggling with it these days. My environment is Win10, the git repository is in the "D:\Project\MetaGPT" directory, and when I install it in conda using the "pip install -e ." command, it also fails to find the package "metagpt". When I use the "git install -e ." command in the conda environment, I also have the problem of not finding the package "metagpt".

After using "pip uninstall metagpt" and then "pip install metagpt" it works fine, but not the customized version I want.

Here is the error message:

![image](https://github.com/geekan/MetaGPT/assets/54876578/7a9b1a66-2680-4a21-82eb-d2c40f3890ba)

**Comment by mrocker** [comment]
> I tried installing and uninstalling a few times, but I couldn't reproduce the scene. Check your logs and find the "Defaulting to user installation because normal site-packages is not writeable" log in the header, maybe check the corresponding path, and whether this path is correctly referenced by the python sys path?

Did some research. it is a setuptools bug. cannot find the right library path.

===Log===
    Checking .pth file support in /Users/nick.cheng/Library/Python/3.9/lib/python3.9/site-packages
    /Library/Developer/CommandLineTools/usr/bin/python3 -E -c pass
    TEST FAILED: /Users/nick.cheng/Library/Python/3.9/lib/python3.9/site-packages does NOT support .pth files
    bad install directory or PYTHONPATH

    You are attempting to install a package to a directory that is not
    on PYTHONPATH and which Python does not read ".pth" files from.  The
    installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:

        /Users/nick.cheng/Library/Python/3.9/lib/python3.9/site-packages

    and your PYTHONPATH environment variable currently contains:

        ''

    Here are some of your options for correcting the problem:

    * You can choose a different installation directory, i.e., one that is
      on PYTHONPATH or supports .pth files

    * You can add the installation directory to the PYTHONPATH environment
      variable.  (It must then also be on PYTHONPATH whenever you run
      Python and want to use the package(s) you are installing.)

    * You can set up the installation directory to support ".pth" files by
      using one of the approaches described here:

      https://setuptools.pypa.io/en/latest/deprecated/easy_install.html#custom-installation-locations


    Please make the appropriate changes for your system and try again.

**Comment by geekan** [comment]
@mrocker Checking from your comment, it seems that you can simply add PYTHONPATH to solve this problem. 

- In linux/macos, you can use `export PYTHONPATH=$PYTHONPATH:/YOUR/PATH` 
- In Windows, you can refer to this [link](https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-so-it-finds-my-modules-packages) to fix it 

In addition, it seems that this is a problem specific to the `pip install -e .` command. You may be able to avoid the problem by using `pip install .`

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
