### ISSUE TITLE
Help with the Config file for LM Studio

### ISSUE THREAD

**Issue by jbuck95** [geekan/MetaGPT#627]
I get a similar Error, can you maybe share your Config File/Explain how you configured it if you got it running with LM Studio? 

`File "C:\Users\Jan\miniconda3\envs\metagpt\Lib\site-packages\metagpt-0.5.2-py3.11.egg\metagpt\config.py", line 92, in get_default_llm_provider_enum
    raise NotConfiguredException("You should config a LLM configuration first")
metagpt.config.NotConfiguredException: You should config a LLM configuration first`

_Originally posted by @jbuck95 in https://github.com/geekan/MetaGPT/issues/459#issuecomment-1868595427_

**Comment by deronkel82** [comment]
same error here!

**Comment by technolinker** [comment]
same here

**Comment by geekan** [comment]
It seems that this problem has not been reported in the latest version. If there are still problems, feel free to reopen
