### ISSUE TITLE
Add ability to use LM Studio API host

### ISSUE THREAD

**Issue by khill-fbmc** [geekan/MetaGPT#658]
**Feature description**
[The LM Studio](https://lmstudio.ai/) application has the ability to host local models with an API like OpenAI

> Local Inference Server
> Start a local HTTP server that behaves like OpenAI's API.

**Your Feature**
Here is the LM Studio server starting up...
![image](https://github.com/geekan/MetaGPT/assets/107003416/f7c00dfd-c832-48cd-8cce-c42981856644)

This example from LM Studio works...
![image](https://github.com/geekan/MetaGPT/assets/107003416/bb79a143-704e-4462-9002-d060acb82cff)

I have been fiddling around with trying to get `http://localhost:1234/v1` working instead of OpenAI in the MetaGPT config, but it keeps failing.
![image](https://github.com/geekan/MetaGPT/assets/107003416/83f1034b-86ac-4fe3-920d-e726ff48819d)

It appears to be ignoring my custom URL and still failing on the lack of an API key
![image](https://github.com/geekan/MetaGPT/assets/107003416/d0ebcc9a-bf05-4fc7-8425-dc6cafdac4f8)

**Comment by better629** [comment]
@khill-fbmc Hi, we use different field names if you use the self-hosted llm. Please refs to the `https://docs.deepwisdom.ai/main/en/guide/tutorials/integration_with_open_llm.html#openai-compatible-interface`. And suggest to use `dev` branch, we will have a update in main later.

configuration fields  
```
OPEN_LLM_API_BASE: 'http://106.75.10.65:8001/v1'
OPEN_LLM_API_MODEL: 'llama2-13b'
```
