### ISSUE TITLE
requirements.txt seems to always be empty

### ISSUE THREAD

**Issue by csimokat** [geekan/MetaGPT#670]
**Bug description**

When running metagpt the final results seem to always result in an empty requirements.txt which then leaves the user to go through the various .py files to go looking for what the requirements might be. This even happens in the 2048 challenge game example in the install instructions.

**Bug solved method**

**Environment information**

- LLM type and model name: gpt-4-1106-preview
- System version: Ubuntu 22.04 (I also observed this in a Windows 10 environment I was also testing)
- Python version: conda python 3.9

- packages version:
- installation method: Followed install guide in the repo for conda + pip install

**Screenshots or logs**

**Comment by voidking** [comment]
Thanks for your report. I have reproduced the problem. We will fix it.

**Comment by voidking** [comment]
The latest version has fixed the problem.
