### ISSUE TITLE
config读取顺序出错

### ISSUE THREAD

**Issue by nicekate** [geekan/MetaGPT#719]
setup是这样写的：
MetaGPT will read your setup in this priority order: config/key.yaml > config/config.yaml > environment variable

但MetaGPT / metagpt/ config.py的代码部分，顺序是environment variable是最优先的：

![CleanShot 2024-01-08 at 18 13 17@2x](https://github.com/geekan/MetaGPT/assets/45737948/6bf40624-8c5f-4516-b8f4-7aaef61aa945)

**Comment by SuperbDong** [comment]
先读取的env，然后如果有yaml文件会更新这个config
