### ISSUE TITLE
支持阿里云的SDK吗？

### ISSUE THREAD

**Issue by all-iot** [geekan/MetaGPT#723]
**Feature description**

**Your Feature**

**Comment by better629** [comment]
which one? qwen or ?

**Comment by all-iot** [comment]
<img width="1629" alt="image" src="https://github.com/geekan/MetaGPT/assets/6176582/72c985b1-0cef-44ec-95a6-a83285a6b5e2">

load [DashScope SDK](https://help.aliyun.com/zh/dashscope/developer-reference/install-dashscope-sdk) first ,then could switch anyone in this list
