### ISSUE TITLE
Proxy Setting for other LLM

### ISSUE THREAD

**Issue by zzzzzz5530041** [geekan/MetaGPT#746]
**Feature description**
Google Gemini怎么设置代理啊?

**Your Feature**
希望支持Google Gemini的代理.

**Comment by zzzzzz5530041** [comment]
please help to support Gemini proxy setting .thanks

**Comment by voidking** [comment]
运行代码前，本地配置全局代理。例如：
```bash
export http_proxy=http://127.0.0.1:7890
export https_proxy=http://127.0.0.1:7890
```

**Comment by gaoshan5211** [comment]
试试在配置文件 config.yaml 里增加 GLOBAL_PROXY: 这个配置

**Comment by zzzzzz5530041** [comment]
> 试试在配置文件 config.yaml 里增加 GLOBAL_PROXY: 这个配置

我错了。应该用https，谢谢能连上gemini了。

**Comment by zzzzzz5530041** [comment]
issue got fixed. thanks

**Comment by zzzzzz5530041** [comment]
> 试试在配置文件 config.yaml 里增加 GLOBAL_PROXY: 这个配置

这个我加上了还是没用。 上面的兄弟的方法可以用。。谢谢你
