### ISSUE TITLE
raised JSONDecodeError

### ISSUE THREAD

**Issue by HuZixia** [geekan/MetaGPT#749]
**Bug description**

Executing python code：python startup.py "写个类似今日头条的推荐系统"

Error reported as follows：raised JSONDecodeError
<img width="1438" alt="image" src="https://github.com/geekan/MetaGPT/assets/38995480/86c42c32-dc26-4f07-bae3-095d040ec88a">

So, the error caused by incorrect json format. At the same time, I find the json format is different elsewhere, as follows:
<img width="1438" alt="image" src="https://github.com/geekan/MetaGPT/assets/38995480/972e61f0-8044-45cc-8862-7414d0f5f743">

Now, there are two questions, one is how to fix the bug, the other is why json format annotations are different? Is it random?

**Bug solved method**

**The first question can fix by setting "`REPAIR_LLM_OUTPUT: true`" in key.yaml. The program runs normally after modification.**

<img width="1433" alt="image" src="https://github.com/geekan/MetaGPT/assets/38995480/bab0649f-f531-416d-be0c-ee53602f62b1">

**The Second question, why json format annotations are different? Is it random? I don't know the answer. Please tell me if you know anything.**

**Environment information**

- LLM type and model name: gpt-4-1106-preview
- System version: macOS Sonoma Version 14.2.1
- Python version: Python 3.11

**Comment by voidking** [comment]
json is from LLM, so it is random. We have to handle it to make it more standardized.
