### ISSUE TITLE
think_act model bug

### ISSUE THREAD

**Issue by JetElves** [geekan/MetaGPT#751]
think 返回数在role中被忽略也许会导致问题 如果think已经返回-1了而让然接着进行act 可能会导致结果出问题

![image](https://github.com/geekan/MetaGPT/assets/78555903/8bd96f5e-c9ab-43ab-8e5b-2fb1bba3bee9)
我用橙色的圈圈起来了 我认为当think == -1 时行动循环应该退出

在role.py下的大约325行

**Comment by voidking** [comment]
@geekan @garylin2099 辛苦帮评估下这个逻辑

**Comment by garylin2099** [comment]
在_think内有`self._set_state(next_state)`，当next_state是-1是，self.rc.todo会变成None，在这个循环内正常推出
