### ISSUE TITLE
NotConfiguredException

### ISSUE THREAD

**Issue by zhengknight** [geekan/MetaGPT#753]
找到别人的提问了，这个可以删了
![1](https://github.com/geekan/MetaGPT/assets/9544952/17628339-2d04-4db5-ac21-4b3ad4b371fb)
按照配置，设置星火大模型，报错，没有配置，啥情况啊
 File "d:\repos\metagpt\metagpt\config.py", line 118, in get_default_llm_provider_enum
    raise NotConfiguredException("You should config a LLM configuration first")
metagpt.config.NotConfiguredException: You should config a LLM configuration first

**Comment by voidking** [comment]
目前dev分支才支持星火，后续合入main就完全支持了。
