### ISSUE TITLE
SubscriptionRunner

### ISSUE THREAD

**Issue by hotbbsun** [geekan/MetaGPT#754]
import asyncio
from metagpt.subscription import SubscriptionRunner
from metagpt.roles import Searcher
from metagpt.schema import Message

async def trigger():
    while True:
        yield Message("the latest news about OpenAI")
        await asyncio.sleep(1)

async def callback(msg: Message):
    print(msg.content)

# async def main():
#     aa = trigger()
#     async for i in aa:
#         await callback(i)
async def main():
    pd = SubscriptionRunner()
    await pd.subscribe(Searcher(), trigger(), callback)
    await pd.run()

asyncio.run(main())
在创建Runner时候报错，0.6.3版本
Traceback (most recent call last):
  File "e:\tmp\metatest\OSSWatcher .py", line 44, in <module>
    asyncio.run(main())
  File "C:\Users\888888\.conda\envs\mp\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\uweih034\.conda\envs\mp\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\888888\.conda\envs\mp\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "e:\tmp\metatest\OSSWatcher .py", line 40, in main
    pd = SubscriptionRunner()
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\888888\.conda\envs\mp\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\888888\.conda\envs\mp\Lib\site-packages\pydantic\_internal\_mock_val_ser.py", line 47, in __getattr__
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: `SubscriptionRunner` is not fully defined; you should define `Environment`, then call `SubscriptionRunner.model_rebuild()`.

For further information visit https://errors.pydantic.dev/2.5/u/class-not-fully-defined

**Comment by hotbbsun** [comment]
Environment
pb = SubscriptionRunner()

**Comment by z4656207** [comment]
同问

**Comment by z4656207** [comment]
> Environment pb = SubscriptionRunner()
Can you explain how it was resolved?

**Comment by hotbbsun** [comment]
已经解决只需要代码这样写就OK了

1. from metagpt.environment import Environment
2. Environment
3. pb = SubscriptionRunner()
Environment 单独占一行
就可以解决问题

**Comment by z4656207** [comment]
> 已经解决只需要代码这样写就OK了
> 
> 1. from metagpt.environment import Environment
> 2. Environment
> 3. pb = SubscriptionRunner()
>    Environment 单独占一行
>    就可以解决问题

非常感谢
