### ISSUE TITLE
in the method role._init_actions, instantiation Action giving the name ""

### ISSUE THREAD

**Issue by chenlovehx** [geekan/MetaGPT#762]
**Bug description**

![现有代码](https://github.com/geekan/MetaGPT/assets/32660675/114de6aa-dc34-481f-b039-e726f44a3d38)

if I extends Action and give the name, this instantiation method will cover my name.

**Bug solved method**
![修改代码](https://github.com/geekan/MetaGPT/assets/32660675/828a5dc9-6227-48ac-a792-9b3fd8cf210a)

**Environment information**

- LLM type and model name:
- System version:windows
- Python version:3.9.12

- packages version:0.6.4
- installation method: pip install

**Screenshots or logs**

**Comment by geekan** [comment]
The latest dev branch has modified this default initialization code, you can give it a try
