### ISSUE TITLE
Role 中使用的 Message 的 role 属性含义 和 OpenAILLM 中处理 Message 时对 role 属性含义理解不一致的问题

### ISSUE THREAD

**Issue by xugaoliang** [geekan/MetaGPT#778]
Role 中的 Message 的 role 属性通常赋值为 Role.profile ，其值如：SimpleCoder, AgentCreator 等。

OpenAILLM 中处理 Message 时，直接使用了 role 属性，但此时 role 要求应为 system,user, assistant 中的一种。

两者对 role 字段含义的不同解释将导致错误

**Comment by voidking** [comment]
会导致什么错误？有没有例子？

**Comment by geekan** [comment]
@garylin2099 Can you look at this question?

**Comment by garylin2099** [comment]
Already fixed in latest version
