### ISSUE TITLE
新建key.yaml之后 自定义的OPENAI_API_BASE不起作用

### ISSUE THREAD

**Issue by fengyunzaidushi** [geekan/MetaGPT#783]
**Bug description**

新建key.yaml之后 自定义的OPENAI_API_BASE不起作用

**Bug solved method**

修改openai_api.py
kwargs = {"api_key": self.config.openai_api_key, "base_url": self.config.openai_base_url} 修改为
`kwargs = {"api_key": self.config.openai_api_key, "base_url": self.config.OPENAI_API_BASE}`

**Environment information**

- LLM type and model name:
- System version:
- Python version:

- packages version:
- installation method: 

**Screenshots or logs**

**Comment by voidking** [comment]
你使用的是最新版的MetaGPT吗？如果是最新版的话，你需要参考下config.yaml进行配置，OPENAI_API_BASE 变为了 OPENAI_BASE_URL

**Comment by geekan** [comment]
The latest config module has been refactored into config2, which has undergone major changes.
