### ISSUE TITLE
Human Engagement不生效

### ISSUE THREAD

**Issue by Yevanchen** [geekan/MetaGPT#795]
![image](https://github.com/geekan/MetaGPT/assets/152952909/51eaddc4-fd89-49a6-a9d2-f4617c1a6f7b)
我尝试运行博客站关于Human Engagement的源代码，在运行到
team.hire(
        [
            SimpleCoder(),
            SimpleTester(),
            SimpleReviewer(),
            SimpleReviewer(is_human=True)
        ]
    )

中的SimpleReviewer(is_human=True) 系统并没有停止进程提供用户输入，而是直接使用了 PROMPT_TEMPLATE: str = """
    Context: {context}
    Review the test cases and provide one critical comments:
    """

    name: str = "SimpleWriteReview"
    默认的prompt请求llm

**Comment by voidking** [comment]
```python
team.hire(
[
SimpleCoder(),
SimpleTester(),
SimpleReviewer(is_human=True)
]
)
```
Try this.

**Comment by Yevanchen** [comment]
> ```python
> team.hire(
> [
> SimpleCoder(),
> SimpleTester(),
> SimpleReviewer(is_human=True)
> ]
> )
> ```
> 
> Try this. 试试这个。

Thank you for your response. I have tried it but it doesn't work. Do I need to rewrite the _act method? I saw it mentioned on a blog site, have you successfully run it before?

**Comment by geekan** [comment]
@garylin2099 Can you take a look at this question? It doesn't seem to be what it was designed to do

**Comment by garylin2099** [comment]
fixed in https://github.com/geekan/MetaGPT/pull/717
