### ISSUE TITLE
Is there any way to run it in docker? Can you guys make it?

### ISSUE THREAD

**Issue by ngeorgj** [geekan/MetaGPT#8]
It would be great to have this on docker!

**Comment by geekan** [comment]
Provide within 24 hours as much as possible

**Comment by Drefrank** [comment]
yeah that would be Awesome

**Comment by geekan** [comment]
waiting to merge https://github.com/geekan/MetaGPT/pull/16

**Comment by geekan** [comment]
Docker version has been provided. Check README and try it
