### ISSUE TITLE
源码安装不能调试

### ISSUE THREAD

**Issue by liujun3660105** [geekan/MetaGPT#808]
**Bug description**
git clone 克隆源码后，执行pip install -e .进行源码安装。之后执行python examples/build_customized_agent.py，可以正常运行，但是当在源码中进行print或者logger.info 时，再次运行，并不会执行打印。感觉都没有走进源码里。
但是通过pip list查看，metaGPT的包确实是链接到我自己的代码仓库里
<img width="808" alt="image" src="https://github.com/geekan/MetaGPT/assets/30195228/5ab09ee3-9261-4200-9836-7dff2bc0ade6">

**Bug solved method**

**Environment information**

- LLM type and model name:
- System version:mac OS
- Python version:3.11.7

- packages version:0.6.0
- installation method: pip install -e .

**Screenshots or logs**

**Comment by voidking** [comment]
使用Debug模式运行build_customized_agent.py，看一下新增的 print或者logger.info 代码有没有执行。

**Comment by geekan** [comment]
pip uninstall metagpt && pip install -e . 或许可以修复这个问题。但一般而言，这个问题是由于多个库同时存在带来的
