### ISSUE TITLE
思考与行动这篇文档什么时候可以更新下

### ISSUE THREAD

**Issue by sunlongjian** [geekan/MetaGPT#813]
https://docs.deepwisdom.ai/zhcn/guide/tutorials/agent_think_act.html
这篇文章 想更多的了解这里的机制，我看挺久了一直都是空着的

**Comment by voidking** [comment]
这个还未完成，可以先参考下《MetaGPT智能体开发入门》教程。
第三章：MetaGPT框架组件介绍 1.4 实现一个更复杂的Agent：技术文档助手
这一节讲了一些关于思考和行动的内容，还有代码分析。
https://deepwisdom.feishu.cn/wiki/KhCcweQKmijXi6kDwnicM0qpnEf
