### ISSUE TITLE
第一次使用遇到错误：winError 32：进程无法访问 求解

### ISSUE THREAD

**Issue by yayaya-pro** [geekan/MetaGPT#86]
![image](https://github.com/geekan/MetaGPT/assets/55486657/bf05187a-06cd-44b0-a785-1b899133e316)

**Comment by yayaya-pro** [comment]
python setup.py install这步产生的

**Comment by geekan** [comment]
[FAQ](https://deepwisdom.feishu.cn/wiki/MsGnwQBjiif9c3koSJNcYaoSnu4) 17

**Comment by ddwinhzy** [comment]
将python版本降级在3.10
