### ISSUE TITLE
system design 文档里Program call flow尾巴经常出问题

### ISSUE THREAD

**Issue by DinoLiww** [geekan/MetaGPT#88]
system design 文档里Program call flow尾巴经常出问题，经常多出''',造成语法解析出错

**Comment by geekan** [comment]
LLM有时候会被其他的上下文误导，比如前面有'''，它后面就会跟着'''
我还没有想到这个问题的较好解法，有没有合适的提议？

**Comment by DinoLiww** [comment]
除了code review，加一个doc review，对应markdown文件里的常犯错误，做一个verification checking，自然就能消除了
工程打法去最后清场

**Comment by geekan** [comment]
这个方法或许会推高整体的成本，并且也是概率性的解法，很难达到100%的问题解决

**Comment by better629** [comment]
Since no further responses are needed, we will close it. Please reopen it if necessary.
