### ISSUE TITLE
生成代码经常在文件头引用有问题

### ISSUE THREAD

**Issue by DinoLiww** [geekan/MetaGPT#89]
生成代码经常在文件头引用有两个问题：
1. from wrong_packagename.CLASSNAME import xxxx
2. 自身生成class引用经常出问题，没有声明引用  from xxxx import Xxxx

**Comment by geekan** [comment]
是的。幻觉仍然有很大比例，我们会在未来的特性发布中逐步缩小这些问题，但由于语言模型本身的概率性质，很难说它能被彻底解决

**Comment by DinoLiww** [comment]
这些拿工程方法来解决，不需要什么都依赖LLM来搞定
后面上几层code review 层面的code verification, 把常见问题扔里面去过滤调整下

**Comment by geekan** [comment]
debug & fix，是的，GPT-4的代码解释器思路

**Comment by wangjie5540** [comment]
> 这些拿工程方法来解决，不需要什么都依赖LLM来搞定 后面上几层code review 层面的code verification, 把常见问题扔里面去过滤调整下

的确，解决这个问题的两个思路：
1. 降低大模型的幻觉概率
2. 使用工程envaluation的方式，如果出现异常，交给大模型去重新思考

**Comment by stellaHSR** [comment]
run code and 检查导包和环境版本，再进行代码纠正

**Comment by better629** [comment]
Since no further responses are needed, we will close it. Please reopen it if necessary.
