### ISSUE TITLE
Running the same prompt will repeatedly overwrite project files in the workspace 

### ISSUE THREAD

**Issue by Rchenyu** [geekan/MetaGPT#895]
Running the same prompt will repeatedly overwrite project files in the workspace without assigning new names, making it difficult to compare differences between results generated multiple times.

<img width="617" alt="image" src="https://github.com/geekan/MetaGPT/assets/21169767/c21c20b2-95eb-4183-b28a-aa34bc04f657">

**Comment by iorisa** [comment]
If the `--inc` or `--project-path` parameters are not explicitly used to indicate an incremental iteration, the newly created project will default to overwrite mode—overwriting projects with the same name.
To avoid overwriting existing projects, use `--project-name` to set a unique project name for the newly created project.

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
