### ISSUE TITLE
Error after supplementing prompt requirements

### ISSUE THREAD

**Issue by Rchenyu** [geekan/MetaGPT#896]
**Bug description**

I always encounter an issue with MetaGPT not installing the necessary **package.json**  dependencies for Vue, even after multiple uses of the prompt with requirement descriptions. Therefore, when I requested MetaGPT to add dependencies to ensure that the Vue project runs locally, it resulted in an error after running.

<img width="996" alt="image" src="https://github.com/geekan/MetaGPT/assets/21169767/5e10c66d-e5fb-47c8-9635-d073b5887e13">

**Bug solved method**

**Environment information**

- LLM type and model name:
- System version:
- Python version:

- packages version:
- installation method: 

**Screenshots or logs**

**Comment by iorisa** [comment]
Improper use of ' " ' resulted in incorrect parameter splitting.
<img width="1667" alt="截屏2024-03-04 16 26 42" src="https://github.com/geekan/MetaGPT/assets/46912756/449700f4-5a1f-43fd-addb-c351f1fc1eea">
