### ISSUE TITLE
The instructions and usage of --help need to be added to the official documentation.

### ISSUE THREAD

**Issue by Rchenyu** [geekan/MetaGPT#897]
**Feature description**

The instructions and usage of **--help** need to be added to the official documentation. I saw some issues mentioning that the instructions cannot be used.
**Your Feature**

<img width="1439" alt="image" src="https://github.com/geekan/MetaGPT/assets/21169767/cb683a02-d54d-488f-a79b-ac8e56815ba5">
<img width="997" alt="image" src="https://github.com/geekan/MetaGPT/assets/21169767/99631a49-f7cd-48a8-877e-088d93919c60">

**Comment by iorisa** [comment]
fixed: https://github.com/geekan/MetaGPT-docs/pull/104
