### ISSUE TITLE
 AttributeError: module 'setuptools.errors' has no attribute 'CompileError'

### ISSUE THREAD

**Issue by 2012013382** [geekan/MetaGPT#907]
**Bug description**
On my mac, I did pip install metagpt. But it shows the following errors.

![image](https://github.com/geekan/MetaGPT/assets/6192946/b187ce9c-4ba3-45b9-950c-58dc0896d2d4)

**Comment by iorisa** [comment]
Can you provide the complete logs?
This might depend on the Python version.

**Comment by geekan** [comment]
Since no reply was received, this issue is closed, if needed open it again
