### ISSUE TITLE
There is a bug of zhipuai llm while using metagpt on ubuntu22.04 under the environment of WSL2 of windows11 Home edition

### ISSUE THREAD

**Issue by techResearcher2021** [geekan/MetaGPT#917]
**Bug description**
In the system of ubuntu 22.04 under the environment of WSL2 of windows11 Home edition.
With the test cli ```$ metagpt "Write a cli snake game"```, the program reports a bug as shown:
**| ERROR    | metagpt.utils.common:log_it:476 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 0.615(s), this was the 1st time calling it. exp: Request failed, msg: {"error":{"code":"1003","message":"Authorization Token已过期，请重新生成/获取。"}}, please ref to `https://open.bigmodel.cn/dev/api#error-code-v3`**

**But it reports no bug under the environment of installing ubuntu 22.04 directly!**

**Bug solved method**
Installing the linux system directly.

**Environment information**
- LLM type and model name: zhupuai, glm-4
- System version: ubuntu 22.04 under WSL2 of windows 11 Home edition
- Python version: 3.11.7

Dependent packagess：
- packages version: metagpt v0.7-release
- installation method: pip3 install -e .

**Comment by better629** [comment]
can you re-generate a new api_key and try in the same environment first ?

**Comment by techResearcher2021** [comment]
> can you re-generate a new api_key and try in the same environment first ?
I have tried to generate a new api_key, and funded to my account, but it comes the same bug. And I have tried the key with the zhipuai official api call example, and it succeeded.

**Comment by better629** [comment]
It's strange, the error-message seems to be zhipu api auth problem. Can you send a wechat id to my email of the count and later take a look on your environment remotely ?

**Comment by better629** [comment]
As discussed offline, the problem can't reproduce with same env. It's zhipu api auth problem probably.

**Comment by better629** [comment]
updated reason.

zhipu use jwt to encode api-key and has a expired ttl of 3 minutes.
Due to the user's system localtime is not same with the `Beijing time`, so it cause a token expiration error.
So, check your system time if you meet the same problem.
