### ISSUE TITLE
如何实现使LLM输出符合格式要求的SOP或Json？

### ISSUE THREAD

**Issue by lemon-little** [geekan/MetaGPT#921]
# 如何实现使LLM输出符合格式要求的SOP或Json？

您好，以下是我对问题的描述：

在metagpt内，Agent通信使用sop、json格式数据，这种情况下要求LLM的输出需要严格符合格式，请问如何要求LLM输出严格按照制定的json格式进行输出的？能否讲讲思路？也希望指出metagpt对sop、json解析或处理的代码部分，万分感谢！

**Comment by better629** [comment]
refs to `metagpt/actions/action_node.py` and see the part implementation of SOP like `metagpt/actions/write_prd_an.py`. It will instruct to generate multi json fields of `WritePRD`.
