### ISSUE TITLE
GLM4一直报错

### ISSUE THREAD

**Issue by laiqinghan** [geekan/MetaGPT#924]
2024-02-22 16:50:26.666 | ERROR    | metagpt.utils.common:log_it:476 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 80.109(s), this was the 5th time calling it. exp: 1 validation error for PM_NODE_AN
  Value error, Missing fields: {'Full API spec', 'Required Python packages', 'Required Other language third-party packages'} [type=value_error, input_value={'Required JavaScript pac...ation and development.'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/value_error

**Comment by yuerf** [comment]
the same problem

**Comment by CaffreySun** [comment]
me too

**Comment by better629** [comment]
see `https://docs.deepwisdom.ai/main/en/guide/tutorials/integration_with_open_llm.html#main-issues-with-open-source-model-command-output`

add `repair_llm_output` in `config2.yaml` like
```
llm:
    xxx

repair_llm_output: true
```
