### ISSUE TITLE
Multi modal LLM integration

### ISSUE THREAD

**Issue by revupst** [geekan/MetaGPT#936]
**Feature description**

Is there any plan for multi modal LLM integration?

e.g. OpenAI image generation API

**Your Feature**

**Comment by better629** [comment]
text2image see `https://github.com/geekan/MetaGPT/blob/main/metagpt/provider/openai_api.py#L301`

`chat-with-image` see `https://github.com/geekan/MetaGPT/blob/main/examples/llm_vision.py`
