### ISSUE TITLE
Create 2048 game is the only thing that runs when using llama2

### ISSUE THREAD

**Issue by colewales** [geekan/MetaGPT#954]
**Bug description**
Using the latest metagpt=0.7.3 when running with this config2.yaml:

llm:
  api_key: not-needed
  api_type: ollama
  base_url: http://localhost:11434/api
  model: llama2:13b

No matter what I input into the query I get metagpt trying to create 2048 game.

**Environment information**
Windows 11
Python 3.11.4
metagpt 0.7.3
- LLM type and model name: ollama & llama2:13b

- installation method: pip install metagpt

**Screenshots or logs**

2024-03-02 19:49:39.324 | INFO     | metagpt.roles.role:_act:399 - Alice(Product Manager): to do WritePRD(WritePRD)
2024-03-02 19:49:39.327 | INFO     | metagpt.actions.write_prd:run:86 - New requirement detected: Generate a simple hello world python script
  Sure, I'd be happy to help! Here is the generated content for the given context:

[CONTENT]
{
"Language": "en_us",
"Programming Language": "Python",
"Original Requirements": "Create a 2048 game",
"Project Name": "game_2048",
"Product Goals": [
"Create an engaging user experience",
"Improve accessibility, be responsive",
"More beautiful UI"
],
"User Stories": [
"As a player, I want to be able to choose difficulty levels",
"As a player, I want to see my score after each game",

Aborted.

**Comment by geekan** [comment]
@Kohl-Watson 
Models such as llama2 tend to fail to follow instructions at small scales (e.g. 13B/7B). This problem is known and needs to be scaled up to solve the problem
- We haven't found a reliable way to run it on a small scale yet, but we'll put it on the todo list. There are some models with small-scale solutions (such as DeepSeek 6.7B) that look attractive

**Comment by theRockPaperScissors** [comment]
Same issue when I run instructions using Meta-Llama-3-8B
