### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by psmoros** [geekan/MetaGPT#967]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@lyutoon) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by iorisa** [comment]
fixbug: https://github.com/geekan/MetaGPT/pull/970
