### ISSUE TITLE
hopefully it can support Llama2 70B model 

### ISSUE THREAD

**Issue by hohoCode** [geekan/MetaGPT#97]
Thanks for this project. Hopefully it can support Llama2 70B model or anything from huggingface. This would be useful for commercial usage.

**Comment by wangjie5540** [comment]
That's right, commercial usage needs Llama2

**Comment by ishaan-jaff** [comment]
Addressed here: https://github.com/geekan/MetaGPT/pull/114

**Comment by better629** [comment]
refs to `https://docs.deepwisdom.ai/main/en/guide/tutorials/integration_with_open_llm.html`
