### ISSUE TITLE
`utils.text.reduce_message_length` Not reducing text length

### ISSUE THREAD

**Issue by azurewtl** [geekan/MetaGPT#979]
**Bug description**
I come across this issue.
```python
  File "/Users/azure/Documents/Workspace/Datasci/lib/python3.10/site-packages/metagpt/utils/text.py", line 31, in reduce_message_length
    raise RuntimeError("fail to reduce message length")
RuntimeError: fail to reduce message length
```

**Bug solved method**
Digging into the code, I assume `utils.text.reduce_message_length()` only check if the token is short enough.
If it's too long, it simply raise exception, instead of shorten it.
Following it the code in `utils.text.reduce_message_length()`
```python
def reduce_message_length(
    msgs: Generator[str, None, None],
    model_name: str,
    system_text: str,
    reserved: int = 0,
) -> str:
    max_token = TOKEN_MAX.get(model_name, 2048) - count_string_tokens(system_text, model_name) - reserved
    for msg in msgs:
        if count_string_tokens(msg, model_name) < max_token or model_name not in TOKEN_MAX:
            return msg

    raise RuntimeError("fail to reduce message length")
``` 

- LLM type and model name:
- System version:MetaGPT 0.7.4
- Python version: Python 3.10.13

Is it a feature that is not implemented yet, or I can try to create a PR to fix it

**Comment by iorisa** [comment]
Thank you for your feedback.
The issue isn't caused by `reduce_message_length`, but rather by incorrect usage of the `reserved` parameter when using `reduce_message_length`.
In the v0.6-release branch, the source code looks like this：
```python
prompt = reduce_message_length(gen_msg(), model_name, system_text, CONFIG.max_tokens_rsp)
```
However, in the v0.7-release branch, the source code looks like this：
```python
prompt = reduce_message_length(gen_msg(), model_name, system_text, 4096)
```
The `reserved` parameter is assigned a constant value of 4096, which could result in `max_token = TOKEN_MAX.get(model_name, 2048) - count_string_tokens(system_text, model_name) - reserved` being constantly less than 0.
You can submit a PR to replace `4096` with `config.llm.max_token`：
<img width="937" alt="截屏2024-03-11 15 27 32" src="https://github.com/geekan/MetaGPT/assets/46912756/f1769d9c-07ff-4127-a88b-58925716356b">
<img width="1087" alt="截屏2024-03-11 15 29 00" src="https://github.com/geekan/MetaGPT/assets/46912756/1e956774-9b09-45d8-a9c9-fb6495eb05f1">

Or, you can wait until I submit a PR to fix this issue in a few days.

**Comment by azurewtl** [comment]
> Thank you for your feedback. The issue isn't caused by `reduce_message_length`, but rather by incorrect usage of the `reserved` parameter when using `reduce_message_length`. In the v0.6-release branch, the source code looks like this：
> 
> ```python
> prompt = reduce_message_length(gen_msg(), model_name, system_text, CONFIG.max_tokens_rsp)
> ```
> 
> However, in the v0.7-release branch, the source code looks like this：
> 
> ```python
> prompt = reduce_message_length(gen_msg(), model_name, system_text, 4096)
> ```
> 
> The `reserved` parameter is assigned a constant value of 4096, which could result in `max_token = TOKEN_MAX.get(model_name, 2048) - count_string_tokens(system_text, model_name) - reserved` being constantly less than 0. You can submit a PR to replace `4096` with `config.llm.max_token`： <img alt="截屏2024-03-11 15 27 32" width="937" src="https://private-user-images.githubusercontent.com/46912756/311618856-f1769d9c-07ff-4127-a88b-58925716356b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDkxMTIsIm5iZiI6MTcxMDE0ODgxMiwicGF0aCI6Ii80NjkxMjc1Ni8zMTE2MTg4NTYtZjE3NjlkOWMtMDdmZi00MTI3LWE4OGItNTg5MjU3MTYzNTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA5MjAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZWRhM2Y1NGRjZjAzYzg0MTc4MzU5NjlmYzk4NDlmMDA5MzNlMDQ0MzAzYjA4NTAwODY3NDFlNTE4NDZjNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bixt6MRcoB3wNUPkV_XwvuyoXX-byhdn6QCLyft6IuM"> <img alt="截屏2024-03-11 15 29 00" width="1087" src="https://private-user-images.githubusercontent.com/46912756/311619183-1e956774-9b09-45d8-a9c9-fb6495eb05f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDkxMTIsIm5iZiI6MTcxMDE0ODgxMiwicGF0aCI6Ii80NjkxMjc1Ni8zMTE2MTkxODMtMWU5NTY3NzQtOWIwOS00NWQ4LWE5YzktZmI2NDk1ZWIwNWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA5MjAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZTA2ZWU5ZTFiNmNmMzY2NTEyMmQwMDdkNmQ4ZDE1YzFkMDdkNTlhNmI2MGMxM2EyNzU4N2E3ZGRlMzkwNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hn9ubQPpDI9r2TClafPN8b_LWhettxUuW1L5K-gzPRk">
> 
> Or, you can wait until I submit a PR to fix this issue in a few days.

I get it, `reduce_message_length` truncate msg instead of compacting it.
Does it make sense to recursively feed msg to refine and compact chain to make it shorter??
Also, why should `reserve` been set to `config.llm.max_token`? 
Doesn't `config.llm.max_token` should equals to `TOKEN_MAX.get(model_name, 2048)` literally？
In this case should I set `reserve = 0`?

**Comment by azurewtl** [comment]
STEP1:  `max_token` is calculated by `token_max - token_of_sys - reserved`
```python
max_token = TOKEN_MAX.get(model_name, 2048) - count_string_tokens(system_text, model_name) - reserved
```
STEP2: msg is compared with `max_token`, so this `max_token` represents the max token allowed by llm.
```python
for msg in msgs:
    if count_string_tokens(msg, model_name) < max_token or model_name not in TOKEN_MAX:
        return msg
```
Therefore, I propose `reserved` means the token reserved for other use. It has nothing to do with `config.llm.max_token(maximum length of the response generated by the LLM)`

`reduce_message_length` is only used by researcher, and after I modified reserve=0, it works.

**Comment by azurewtl** [comment]
In `metagpt/actions/research.py` line: 137
```python
prompt = reduce_message_length(gen_msg(), model_name, system_text, 0)
logger.debug(prompt)
queries = await self._aask(prompt, [system_text])
```
seems like the reduced result if fed into llm as `prompt`, so there is not need for extra `reserved `

**Comment by iorisa** [comment]
```python
max_token = TOKEN_MAX.get(model_name, 2048) - count_string_tokens(system_text, model_name) - reserved
```
is equal to 
```
available_for_prompt = max_io_size_of_model - system_text_used - preallocated_for_response
```
"prompt" corresponds to the first parameter, and "system_text" corresponds to the second parameter below：
```python
await self._aask(prompt, [system_text])
```
