### ISSUE TITLE
求助：运行之后卡住报错

### ISSUE THREAD

**Issue by yayaya-pro** [geekan/MetaGPT#98]
![image](https://github.com/geekan/MetaGPT/assets/55486657/e4fc362b-42fc-4921-b3f5-f1412d6dff77)
![image](https://github.com/geekan/MetaGPT/assets/55486657/9120a199-b924-42bd-9c36-e00ced0c6d5c)
![image](https://github.com/geekan/MetaGPT/assets/55486657/1e3d7975-6ad2-4fc5-b9a7-8be4f579150e)

**Comment by apas008** [comment]
改成这个试试OPENAI_PROXY: "http://127.0.0.1:7890"

**Comment by voidking** [comment]
参考下 faq 8 https://deepwisdom.feishu.cn/wiki/MsGnwQBjiif9c3koSJNcYaoSnu4

**Comment by TerryFYL** [comment]
我的方案是查找自己电脑上的代理ip（图1）。然后将其替换到配置文档里（图2），成功！
图1：![image](https://github.com/geekan/MetaGPT/assets/45841061/0c82a404-dee0-4d52-abb7-d3f28a6a9a20)
图2：![image](https://github.com/geekan/MetaGPT/assets/45841061/6e6e8a05-7d0b-42e6-a30e-3456b3ea6b1e)

**Comment by yayaya-pro** [comment]
感谢你们的回答，产生了新的问题
![image](https://github.com/geekan/MetaGPT/assets/55486657/68600f18-b8bf-4ace-92e7-c9a912f30154)

**Comment by JustinZhangGIS** [comment]
在运行示例的时候报了这个错误
Traceback (most recent call last):
  File "D:\GitProject\metagpt\startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager, QaEngineer
  File "D:\GitProject\metagpt\metagpt\roles\__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "D:\GitProject\metagpt\metagpt\roles\role.py", line 12, in <module>
    from pydantic import BaseModel, Field
  File "pydantic\__init__.py", line 2, in init pydantic.__init__
  File "pydantic\dataclasses.py", line 48, in init pydantic.dataclasses
    # +=========+=========================================+
  File "pydantic\main.py", line 120, in init pydantic.main
TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
