### ISSUE TITLE
use baidu qianfan error

### ISSUE THREAD

**Issue by automlcode** [geekan/MetaGPT#982]
**Bug description**
llm.api_type
  Input should be 'openai', 'anthropic', 'spark', 'zhipuai', 'fireworks', 'open_llm', 'gemini', 'metagpt', 'azure' or 'ollama' [type=enum, input_value='qianfan', input_type=str]

**Environment information**

- LLM type and model name:
- System version: mac osx 14.2.1
- Python version: 3.11.7

- packages version:
  metagpt 0.7.4
- installation method: pip install -i https://pypi.tuna.tsinghua.edu.cn/simple metagpt

**Comment by iorisa** [comment]
The Metagpt 0.7.x version does not yet support qianfan. 
To try it out, switch directly to the main branch.

**Comment by automlcode** [comment]
OK，3Q
